### ISSUE TITLE
Meadow rapid console spam; server grinds to a halt

### ISSUE THREAD

**Issue by roleester** [satisfyu/Let-s-Do-Hub#10]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.8

### Issue Description

When playing the game, the console can be occasionally spammed with a specific meadow error. On this last instance, the console was spammed so consistently and quickly, that the game grinded to a halt because it appears the server couldn't keep up anymore.

I've reported this issue a few weeks ago or so before on the Discord but I don't think I got a response. It was unobstructive then to the gameplay experience and we got no crashes, however this latest time I've attached the logs where the error is spammed so constantly that the server grinded to a halt as aforementioned.

### Steps to Reproduce

1. Play the game (it does not appear to require any particular actions to happen).
2. Wait for the console spam to occur.

### Logs

https://mclo.gs/2xYvOtm

I would use your suggested https://pastebin.com/ but every time I try to copy/paste my browser crashes, and the site doesn't appear to give an option to upload a file directly. My apologies. 

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Slightly improved the whole Forge Networking Part. Will therefore be fixed in 1.2.9.
