### ISSUE TITLE
Problem with bakery module

### ISSUE THREAD

**Issue by ROy94218** [satisfyu/Let-s-Do-Hub#100]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.20.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The crash report shows that there is a problem with the bakery. I have tried to lower the bakery and module core API and also tried to lower the version, but I still can’t find the reason.

### Steps to Reproduce

[crash-2024-06-25_23.27.23-server.txt](https://github.com/user-attachments/files/16101054/crash-2024-06-25_23.27.23-server.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update to 1.1.12.1.
