### ISSUE TITLE
Hops Conflict with Croptopia.

### ISSUE THREAD

**Issue by MichaelStreet1** [satisfyu/Let-s-Do-Hub#101]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Hops in the brewery mod do not integrate with Fabric Seasons and have item conflicts with Croptopia's Hops /Hops Seeds. 

( In other words there are two hops/hops seeds when both mods are installed and the hops/hops seeds from Brewery do not give you a breakdown of which season they grow best in). 

Not really an issue, just hoping it can be tweaked to work the same way HerbalBrews does.

### Steps to Reproduce

Find both Hops and Hops Seeds naturally generating in a world with Croptopia and Brewery installed. 

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
There are no plans for implementing compat with croptopia.
