### ISSUE TITLE
Use Water Bottles/Something Stackable Even for Tea Making

### ISSUE THREAD

**Issue by Tori-Trace** [satisfyu/Let-s-Do-Hub#103]
### Mod Name and Version

Herbal Brews

### Suggestion Details

I would appreciate if the recipies for teas in Herbal Brews extended toward water bottles.  I would love it even more if there was something I could stack and use, like maybe "Tea Cups" that can fill with water, dissappear when used in brews and then return empty when you drink a tea like bowls do for stew.  

### Expected Benefits

Water bottles would be useful to extending the logic of adding water when making recipies.  Having a stackable water source would allow players to make tea reserves for tea shops without needing to stand over the kettle, replacing the empty buckets every time a tea is made.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
That would cause conflicts with stacks and the stackremainder. Therefore this is currently not planned.
