### ISSUE TITLE
Blooming Nature woods not working in furnace

### ISSUE THREAD

**Issue by vivagabe** [satisfyu/Let-s-Do-Hub#104]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Cannot make any blooming nature wood into charcoal.

### Steps to Reproduce

Place wood in furnace and does not burn.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Already fixed inDev. Was due to a missing tag.
