### ISSUE TITLE
blocks not dropping when broken in 1.1.5 beachparty

### ISSUE THREAD

**Issue by EevyernDracaneon** [satisfyu/Let-s-Do-Hub#105]
playing on a 1.20.1 world with the most recent version of Fabric Beachparty, but some blocks do not drop items, and/or don't have favored tools:

List of broken blocks:
-palm hanging sign
-palm sign
-coconuts (unsure if this one is intended)
-deck chair (just has no favored tool)
-hammock
-palm torch

**Comment by satisfyu** [comment]
Fixed in 1.1.7
