### ISSUE TITLE
[Game crashed] Rendering screen  java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by UnnamedWei** [satisfyu/Let-s-Do-Hub#106]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.14

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

Game crashed when opened the Fermentation Barrel GUI
[crash-2024-07-09_11.28.46-client.txt](https://github.com/user-attachments/files/16137694/crash-2024-07-09_11.28.46-client.txt)

### Steps to Reproduce

-Finished the mead
-Open the GUI
-Crashed

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update your mods.

**Comment by satisfyu** [comment]
Alright, thank you. I'll look further into this the upcoming week. Re-opened this issue.

**Comment by JensenJ** [comment]
Alright thanks,
Did you mean to close this again already?
