### ISSUE TITLE
BloomingNature entirely prevents small trees from growing

### ISSUE THREAD

**Issue by aiakared** [satisfyu/Let-s-Do-Hub#108]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Attempting to restrict the height of an oak (or birch) tree's growth entirely prevents it from growing. If this is intentional behavior it should probably be a config option because it breaks some tree farms.

### Steps to Reproduce

Put a block above ~7 blocks above an oak or birch sapling and try to grow a tree with bone meal.
![ldbm_repro](https://github.com/satisfyu/Let-s-Do-Hub/assets/70045485/f595f99c-59ff-4825-9c5f-5eadf2b341d9)
![ldbm_repro_vanilla](https://github.com/satisfyu/Let-s-Do-Hub/assets/70045485/0c5bda42-51e1-40d2-aa93-cb360b17606d)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thats actually a feature of BloomingNature. 

They have been overriden by default. However, next version will include a config where you can disable these features. For now it's only possible with a custom datapack.
