### ISSUE TITLE
cake station dosnt work 1.20.1 lets do bakery

### ISSUE THREAD

**Issue by monkeybee11** [satisfyu/Let-s-Do-Hub#11]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.8

### Issue Description

cant right click the cake station to make cakes :( 

### Steps to Reproduce

right click cake station block (im playing fabric not sure if that matters)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please check out the wiki: 
https://github.com/satisfyu/Bakery/wiki/Blocks#Caking-Station

Theres briefly explained how to use the caking station :)

**Comment by monkeybee11** [comment]
oh...ok that changed from the last time me used the mod XD sry bout that

**Comment by satisfyu** [comment]
All good. :D Have fun baking!
