### ISSUE TITLE
Bug: Vinery / Wine Aging

### ISSUE THREAD

**Issue by AwesomePlays** [satisfyu/Let-s-Do-Hub#110]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.26

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

(1) the `Year of Production` tool-tip is not set for an existing item, despite having aged several years;
(2) the `Year of Production` tool-tip is incorrectly set (at the age of a matured wine) for all future wine/s;
(3) for *__all future wines__ obtained via the creative inventory*, the effect level is set by default at that which you would expect from a matured wine; 
(4) Vinery appears to age the wine at 16d/year, irrespective of the actual config, likely because of `VineryConfig.DEFAULT.getConfig()` (default config); and
(5) The maximum effect level that a wine can give appears to be 6 (likely because it is set at 5, and not 4; `Effect Level = 1 + Actual Level`). 

### Steps to Reproduce

**Tool-tip**
1. From the creative inventory (or as preferred), select any wine.
2. Store that wine in a chest or other inventory.
3. Run: `/time set 80d`
4. In that chest or other inventory, look at the wine's tool-tip.

**Creative Inventory**
1. As 1-3 (Tool-tip), but search for any wine in the creative inventory, and observe the level increase.

**Config**
1. As 1-2 (Tool-tip), but change `Days per Year` (Config) to 1 (or, really, any other easily attainable number).
2. Run: `/time set (config number+1)d`

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Items from the creative menu do not receive NBT data and therefore no Wine Aging. It behaves the same as when you pull an Explorer's Map from the menu.
