### ISSUE TITLE
[Bug] Eating a Food Item with an Effect in the Offhand Causes a Crash

### ISSUE THREAD

**Issue by dandy-is-lion** [satisfyu/Let-s-Do-Hub#115]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.13

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Eating a food item with an Effect like Regen II (crafted with a Vinery Cherry Wine for a Mushroom Soup), or with No Effects if you got it from the creative inventory, in your offhand will cause a crash. I recall this also happening with mods like Sophisticated Backpacks that have an Auto-Feeding upgrade. It seems these food items have leftovers when eaten (becoming a regular Mushroom Soup in this case) that have nowhere to go when it's eaten anywhere that's not the hotbar like the offhand or another inventory.

![2024-07-17_06 04 16](https://github.com/user-attachments/assets/1ae28756-56e7-44c8-82c8-13789bb365b2)
![2024-07-17_06 12 13](https://github.com/user-attachments/assets/562b9b86-7142-417e-8997-fbb02fbdd70b)

- Vinery: 1.4.26
- Candlelight: 1.2.13
- API: 1.2.15
- Forge: 47.3.0

### Steps to Reproduce

1. Craft a Candlelight food item with an effect (either in a Cooking Pot with Vinery Wines or from the Creative Inventory)
2. Switch to Survival and develop some hunger
3. Eat the food item from the offhand

### Logs

https://pastebin.com/x33gfTAR

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I'll just make sure the inventory slot is within valid bounds before accessing it - this should actually fix this issue.

**Comment by satisfyu** [comment]
Tested it and seems to work. :)
