### ISSUE TITLE
[Bug] Titles of Crafting Menus Become Offset When Using JEI or EMI

### ISSUE THREAD

**Issue by dandy-is-lion** [satisfyu/Let-s-Do-Hub#117]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.13

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When selecting a recipe from a bookmark in JEI or EMI, either to view or to push the items in to the Crafting Menu like a Cooking Pot, the Title of the Menu becomes offset and it's additive each time. Tested with Candlelight and Bakery, both latest versions.

![2024-07-17_07 09 36](https://github.com/user-attachments/assets/8e5774eb-0cfa-4147-8c9a-9cc7442b6dea)
![2024-07-17_07 09 15](https://github.com/user-attachments/assets/828ee198-20ff-491b-850c-31e9cc3bcec3)

### Steps to Reproduce

1. Open the Crafting Menu of any Candlelight or Bakery kitchen item like a Cooking Pot
2. Select any item in the JEI (bookmarked or search item)
3. Navigate back out and the title will be shifted to the right or up each time

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in the next release, thank you. :)
