### ISSUE TITLE
You can't hear the radio if it was already playing when you joined the server

### ISSUE THREAD

**Issue by Blayung** [satisfyu/Let-s-Do-Hub#118]
### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

You can't hear the radio if it was already playing when you joined the server.

### Steps to Reproduce

1. Turn the radio on.
2. Leave the server.
3. Join the server.
4. Can't hear it unless you restart it.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue.

**Comment by Blayung** [comment]
Dupe to what? I can't see it.

**Comment by Blayung** [comment]
The issue you have opened is about a crash, it's diffrent.

**Comment by Blayung** [comment]
And that's the only mention of the radio in all issues.

**Comment by Blayung** [comment]
![](https://github.com/user-attachments/assets/e8ed68f6-d6c0-4c79-ab68-8d8b48303530)

**Comment by Blayung** [comment]
@satisfyu

**Comment by satisfyu** [comment]
Both of these issues are caused by the exact same reason.

**Comment by Blayung** [comment]
It doesn't look similar, but ok.

**Comment by satisfyu** [comment]
Both issues are due to faulty networking calls
