### ISSUE TITLE
Big barrel duplication glitch

### ISSUE THREAD

**Issue by silenced-Ego** [satisfyu/Let-s-Do-Hub#12]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.6

### Issue Description

When a big barrel is broken by a piston, it drops 2 big barrels instead of 1.

### Steps to Reproduce

Place down a big barrel, place down a piston directly next to it and pointing towards it, activate the piston

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by silenced-Ego** [comment]
The same bug also exists for the big cherry table in the vinery mod

**Comment by satisfyu** [comment]
Fixed in #1.1.7

https://github.com/satisfyu/Brewery/commit/995dd4c0d5a1aa64cfdc1debd522d30ae94dc471
