### ISSUE TITLE
[HerbalBrews] Earl grey tea and Jasmine tea

### ISSUE THREAD

**Issue by Ureiah** [satisfyu/Let-s-Do-Hub#122]
### Mod Name and Version

HerbalBrews

### Suggestion Details

Add the bergamot plant to be mixed with black tea leaves to make earl grey tea. Jasmine is made similar to the lavender tea in mod. Both are really popular tea types. My European friend was very confused that earl grey  wasn't a thing and was greatly saddened. I think jasmine would be a nice addon for AtlA fans.

### Expected Benefits

More challenge to get and grow the plants. Maybe new effects for them? It's a small addition, but it would be great if it happens.

### Potential Drawbacks

Additional coding, artwork, and effort on the owner of the mod.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Do you have some ideas for effects? :) Would be quite easy to implement.

**Comment by satisfyu** [comment]
I've added it to my To-Do List, thank you.
