### ISSUE TITLE
The Let's do Meadow bucket doesn't work with the Let's do Bakery sink

### ISSUE THREAD

**Issue by WoWnik** [satisfyu/Let-s-Do-Hub#125]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.13

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

The Let's do Meadow bucket doesn't work with the Let's do Bakery sink

### Steps to Reproduce

Try to use a wooden bucket on the sink

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.3.20
