### ISSUE TITLE
Config options for Blooming Nature

### ISSUE THREAD

**Issue by InfinitysDaughter** [satisfyu/Let-s-Do-Hub#126]
### Mod Name and Version

BloomingNature

### Suggestion Details

I love the flora and fauna but can we get a config option to remove the extra grass and ferns? I understand its to make the world more "overgrown" feeling but in some places its a lot, especially if you have other mods that add extra flora.

### Expected Benefits

More options more bettah? But seriously. Like I said above, it would make it easier to meld with other flora mods.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Already done and coming with v1.0.8 :)

**Comment by InfinitysDaughter** [comment]
Awesome!!!! Thank you so much!!!!
