### ISSUE TITLE
Sugar Rush effect lasts after timer runs out

### ISSUE THREAD

**Issue by Dumpling00** [satisfyu/Let-s-Do-Hub#127]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When eating sweets, in this case chocolate cookies, the sugar rush and speed boost is correctly given, but the effect isn't cleared after the timer ends. Tried clearing the effect via console command, said there are no effects applied - drinking milk didn't fix this, I was still granted with the speed boost. Effects lasted even after logging out and back in, even after restarting the client.
Dying and respawning fixed the issue.

### Steps to Reproduce

Eat any food that gives the bakery:sweets effect, wait the timer out, experience the effect still being active.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by coily610** [comment]
Yes, I also encountered the same situation

**Comment by satisfyu** [comment]
Fixed in 1.1.15
