### ISSUE TITLE
Auto Coconut breaker

### ISSUE THREAD

**Issue by ShyNieke** [satisfyu/Let-s-Do-Hub#128]
### Mod Name and Version

Let's Do Beach

### Suggestion Details

It would be cool if dispensers could shoot out coconuts to have a cool vanilla way of automating the breaking of coconuts.

### Expected Benefits

This would allow Coconut farms to be able to automatically split open the coconuts when they are shot against solid walls. maybe if it hits a mob or player it could even give them a few seconds of nausea alongside a tick of damage ;)

### Potential Drawbacks

If you don't want players to be able to make auto coconut farms this could be considered a drawback

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Implemented. :)
