### ISSUE TITLE
Cooking Pot: Can't use bottles as containers [CandleLight]

### ISSUE THREAD

**Issue by SeraphinFosfato** [satisfyu/Let-s-Do-Hub#129]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.3.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I'm playing in a mostly cooking based modpack, where the only two mods in the list are "Farmers Delight" and the full [Let's Do] Package. I've also installed a working integration of Candlelight to farmers delight, but apparently I can't place bottle or jars in the Cooking pot of Candle Delight (wich is the only one able to do jams and other high cuisine stuff).

### Steps to Reproduce

Install these 3 mods (with the respective depencies):

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
https://www.curseforge.com/minecraft/mc-mods/lets-do-addon-compat
https://www.curseforge.com/minecraft/mc-mods/lets-do-candlelight

### Logs

the log was too big, but I wasn't brave enough to remove things on my own as I could potentially remove important feeds from the consol, so instead I've uploaded it on Mediafire: https://www.mediafire.com/file/2lufu5w1icvp436/Seraphon.zip/file

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
This is because the CookingPan and the CookingPot only accept Bowls as containers. Therefore, any recipes added by other mods that use a different type of container do not work.

I will change it to a tag - however, this still does not provide full functionality. Other mod developers will need to adjust their recipes accordingly to use this tag.
