### ISSUE TITLE
[Meadow] No more Meadow Biomes, Chickens, Cows and Sheep in the latest version

### ISSUE THREAD

**Issue by twoface99** [satisfyu/Let-s-Do-Hub#130]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.18

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

After installing the latest version of the Meadow mod (and DoAPI) all sheep, cows and chicken have reverted back to their standard Minecraft counterpart.

The Meadow biomes have also been changed back to standard Minecraft and Region Unexplored biomes.
Meadow biomes will no longer show up using /locate biome nor using the Nature Compass.

When using the old version 1.3.4 everything is fine.

Creating a new world using the newest version does not fix this issue.

If needed, I can provide a full list of all the Mods I am using. The mod list has stayed the same, only the mod version have been updated.

### Steps to Reproduce

1. Install latest version of Meadow and DoAPI
2. Join a world a make a new one
3. Search for Meadow biomes
4. Search for new breeds of chicken, sheep and cows
5. Don't find what you are looking for

---When upgrading from an older version---

1. Install old version of Meadow and DoAPI
2. Join a world or create a new one
3. Search for Meadow Bioms and new animal breeds
4. Find what you are looking for
5. Update to latest version
6. No more Meadow biomes or breeds

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Subbiomes have being removed and features are being placed with noise now so you don't need terrablender as a dependency anymore. This was also properly documented in the changelogs. 

Also cow and chicken variants have been removed - this was also documented in the changelogs.

**Comment by twoface99** [comment]
Well that's embarrassing.

Thought I read all the change logs, must have missed this. Sorry about that :)

Thanks for the quick reply!
