### ISSUE TITLE
Leaf Decay in both World Generated and Sapling-Grown Trees for BloomingNature

### ISSUE THREAD

**Issue by iBryguy** [satisfyu/Let-s-Do-Hub#131]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Some, if not most or all, leaves of trees added by BloomingNature decay despite having their associated tree's wood nearby. This impacts BloomingNature's custom tree types, as well as the new variants for existing Minecraft trees. 

Only trees generated naturally or from saplings are affected; leaves placed manually are unaffected. Trees with leaves close to, or immediately adjacent too, logs seem to be less affected. (Most Aspen trees and Swamp Oak trees seem essentially unaffected, presumably for this reason). 

I've attached a small video demonstrating the issue with various trees. Each clip has been sped up so that the leaf decay can be viewed in a reasonable time-frame. Certain mods can speed up this process, but for the purpose of testing I used minimal mods. (i.e., BloomingNature and the mods it required).
https://github.com/user-attachments/assets/0466d893-8236-4e26-9cd3-c06c9c7e2a36

### Steps to Reproduce

1. Find or grow trees added by BloomingNature.
2. Watch as leaves begin to decay, without any user interaction with the tree's leaves or logs.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've just fixed that today for the upcoming release. :)
