### ISSUE TITLE
Consumes all milk bottles

### ISSUE THREAD

**Issue by TonyD6** [satisfyu/Let-s-Do-Hub#133]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.15

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When making stawberry pudding with milk bottles from farmers delight it consumes all bottles for one pudding instead of just one

### Steps to Reproduce

Make strawberry pudding with milk bottles from farmers delight. It will eat the whole stack instead of just one

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Because the stack remainder is not aligned with whole stacks but only with milk buckets, which are not stackable. :) 

I currently have no plans to implement this, but I have added it to my to-do list."
