### ISSUE TITLE
No explanation of silo in the wiki

### ISSUE THREAD

**Issue by CircusSeal** [satisfyu/Let-s-Do-Hub#135]
I clicked on the wiki link on the [Let's Do] Brewery page on Curseforge to figure out if I should make a wooden or copper silo, but there is no silo entry on the wiki, despite saying there is in the table of contents on the right.

**Comment by satisfyu** [comment]
As stated on the first page of the wiki, it refers to version 2.0.0 of brewery:
https://github.com/satisfyu/Brewery/wiki

> This wiki refers to the following version of Brewery: 2.0.0

Version 2.0.0 doesn't contain a silo anymore.
