### ISSUE TITLE
Where can I find barley?

### ISSUE THREAD

**Issue by CircusSeal** [satisfyu/Let-s-Do-Hub#136]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I can't figure out where to find barley. I'm scouring various biomes and looking in village chests. Do they spawn in a specific biome?

I downloaded this mod after creating my world, but this is true even in new chunks.

### Steps to Reproduce

Run around for a while.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Throw Beetroot Seeds on a Stonecutter. They don't spawn naturally. You can also find them inside Villages. Will be changed in the Farm&Charm compat release.
