### ISSUE TITLE
wood not wooding right? 

### ISSUE THREAD

**Issue by caligator** [satisfyu/Let-s-Do-Hub#137]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

https://discord.com/channels/1078796799185277079/1267866480796762158/1267866480796762158 continued from here;

issues with logs in this mod seem to be that the logs are not tagged, they can not be stripped by an axe, and the planks seem to be missing tags too as they can not be used to make vanilla recipes like chests. 

### Steps to Reproduce

right click a blooming nature log with an axe to try and strip it

try and make a campfire with the logs

try and make a chest with the planks

used on alpine and fir logs, but noted in EMI to be missing recipes, even for other LD expansions.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in 1.0.8.
