### ISSUE TITLE
New spruce trees leaves decaying

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#138]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The spruce leaves on the new spruce trees are decaying despite the logs being present, causing a lot of items (sapling, sticks) to drop
![Screenshot_2631](https://github.com/user-attachments/assets/772373fe-055a-4eef-8279-8a6156fc1236)

### Steps to Reproduce

Enter any forest containing the new spruce trees and observe the amount of entities in F3

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed. Once and for all. Will release it probably tomorrow.
