### ISSUE TITLE
[WilderNature] raccoons are halfway in the ground

### ISSUE THREAD

**Issue by glittermutt** [satisfyu/Let-s-Do-Hub#139]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

i am not sure why but all raccoons are halfway in the ground. im using the server modpack
![2024-08-04_19 35 04](https://github.com/user-attachments/assets/9f394d7a-48e7-47b4-91f8-4313a7f88005)

### Steps to Reproduce

1. spawn a raccoon
2. das it :3

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed. BloomingNature is still inDev. 📦
