### ISSUE TITLE
[Candlelight] I'm trying to make "Mousse au Chocolate", but it's giving me "Chocolate Truffle".  Tried both cooking pots.  

### ISSUE THREAD

**Issue by ninjaeon** [satisfyu/Let-s-Do-Hub#14]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.11

### Issue Description

I'm trying to make "Mousse au Chocolate", but it's giving me "Chocolate Truffle".  Tried both cooking pots.  

letsdo-candlelight-fabric-1.2.11
letsdo-bakery-fabric-1.1.8
letsdo-API-fabric-1.2.9-fabric
letsdo-addon-compat-fabric-v1.4.1

### Steps to Reproduce

Place recipe ingrediants into cooking pots on top of oven.

"Chocolate Truffle" is made instead of "Mousse au Chocolate", despite "Butter" being included as one of the ingrediants.
![javaw_1Oxv2aGPQ0](https://github.com/satisfyu/Let-s-Do-Hub/assets/10052279/f5b8b008-9a58-4c76-a91e-2700f4099467)
![javaw_8aJI3bIraN](https://github.com/satisfyu/Let-s-Do-Hub/assets/10052279/14d5bd2f-36ed-4bb8-942c-f0891bc52153)

### Logs

https://mclo.gs/RD2yC8y

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in the next Updae.
