### ISSUE TITLE
[WilderNature] messed up animal compendium ui

### ISSUE THREAD

**Issue by glittermutt** [satisfyu/Let-s-Do-Hub#140]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

the book ui is a lil messed up
![2024-08-04_19 35 08](https://github.com/user-attachments/assets/898b8e74-9fe0-46d2-af52-89902ae3e6b5)
![2024-08-04_19 35 18](https://github.com/user-attachments/assets/1843e61c-3750-4fe8-bde9-0f73b6833e54)

### Steps to Reproduce

1. open the animal compendium
2. profit :3

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
It's still an inDev version and the book is still a heavy WIP. :)
