### ISSUE TITLE
[WilderNature] dogs & turkeys have missing animations

### ISSUE THREAD

**Issue by glittermutt** [satisfyu/Let-s-Do-Hub#141]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

using the latest modpack again :3 the mod is super cute, just reporting any issues i encounter to hopefully help
https://github.com/user-attachments/assets/e05d7e61-accf-40cd-9d3f-c8808f513c83

### Steps to Reproduce

1. look at turkeys and dogs
2. thas it! :D

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed. It's still an inDev version. :)
