### ISSUE TITLE
Boats cause game to crash

### ISSUE THREAD

**Issue by awhlimbo** [satisfyu/Let-s-Do-Hub#142]
### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Everytime we place the boat for one of my friends their game crashes completely 

### Steps to Reproduce

place boat near someone 

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey

thank you for your bug report. :) 

This bug is actually related to the doAPI which has its own bug tracker: 
https://github.com/Team-Let-s-Do/DoAPI/issues

Theres already an open issue about this.
