### ISSUE TITLE
[Furniture] breaks the crafting tables from Variant Vanilla Blocks

### ISSUE THREAD

**Issue by temyy** [satisfyu/Let-s-Do-Hub#143]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

when both mods are installed, trying to use any of the wood variant crafting tables from vvb causes the gui to flash quickly and then disappear right away. video attached

https://github.com/user-attachments/assets/bb83f864-0f31-4c4f-b58b-88efd742677f

### Steps to Reproduce

1. have both [VVB](https://modrinth.com/mod/variant-vanilla-blocks) and Furniture installed at the same time
2. load up a world
3. place down any of the variant crafting tables (acacia, bamboo, birch etc.)
4. right click on it

### Logs

https://mclo.gs/xDbXXbg

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.0.1
