### ISSUE TITLE
Mirrors have same crafting recipe

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#144]
### Minecraft Version

Fabric 1.20.1

### Mod

Furniture

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

All mirrors still have the same recipe thus overlapping each other (8 sticks and 1 tinted glass). We can't choose which one to craft, it just gives random one when we put items in crafting table (every time same mirror).

### Steps to Reproduce

Well, i looked this up in jei :D

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Ha! You didn't find this issue during your playtesting :P

**Comment by Tefnya** [comment]
![Screenshot_20240807-190923_Discord](https://github.com/user-attachments/assets/7793bbe9-b09e-4628-ac42-c7e07400cada)
Pretty sure i did σωσ

**Comment by satisfyu** [comment]
Let's Do: Correct reading 👎

**Comment by satisfyu** [comment]
Fixed in 1.0.1
