### ISSUE TITLE
[Camping] Few issues of Let's do Camping

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#145]
### Minecraft Version

Fabric 1.20.1

### Mod

Camping

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) Hiking backpack is named "iking" (you deleted colorcode letter "a" some time ago).
2) Back parts of all tents (any of 4 blocks in the back) have no loottables.
3) We can put backpacks both in chestplate and trinkets slots (and thus can have 2 of them stacked on top of each other). I guess this is unintentional, cause why otherwise would trinkets be a required dependancy.
4) When enderpack or enderbag are in trinkets slot we can't open them. Instead for some reason we can open them from any other inventory slot.
5) After relogging placed backpack blocks do not recognize changes to their inventory, description below.

### Steps to Reproduce

It happens only under certain conditions which are unlikely to happen, but i'll still report this. (it can be done with any item, but example is for you to see what happens, so i use a stack of items)
1. Place any backpack (excluding ender ones).
2. Put stack of items inside, close the world and open it again.
3. Open a backpack, one of two things happens: 1) Items are still inside; 2) Items disappeared.
4. If items are still **inside**: rearrange them and add another item inside (without picking up backpack).
5. Close the world and open it again.
6. When we open a backpack we see previous item arrangement with one stack of items without added item.

It seems that placed backpack doesn't update its inventory and returns it to previous state.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by jason13official** [comment]
Fixes players being able to equip multiple backpacks via Trinkets in Fabric.
https://github.com/satisfyu/Camping/commit/7f07e5c780ec182999294beb64d8ba21ae082221

Fixes the Enderpack opening from the wrong slots, now only opens from chestplate and trinket slot.
https://github.com/satisfyu/Camping/commit/350b2b9546bda6b9e53e0cb5de60d693d9842afc

**Comment by jason13official** [comment]
Fixes(?) container data not being saved and loaded in BackpackBlockEntity (needs testing)
https://github.com/satisfyu/Camping/commit/ece279739c3efcdaa00b41c6f50615e45ff4d7e4

**Comment by satisfyu** [comment]
Fixed in 1.0.1
