### ISSUE TITLE
[Furniture] Shading/Texture Suggestion

### ISSUE THREAD

**Issue by Looodon** [satisfyu/Let-s-Do-Hub#146]
### Mod Name and Version

[Let's Do] Furniture? 

### Suggestion Details

------------------------------
**EDIT: discovered lamps need you to shift+right click to turn on, it would be nice if right clicking alone is enough**
------------------------------

Hey,
The mod is a 10/10, been loving it! I just wanted to raise some things I found when testing it. I don't know if this is classified as an issue or suggestion, but I've experienced some shading/texture inconsistencies. 

**Shadow Textures:**
It's not only the furniture in the image, other furniture can replicate this. My suggestion here is it would be nice if there was more consistency with the shading/textures (i like the softer ones more) & consistency with the rotation

![Example](https://github.com/user-attachments/assets/37b8b751-1182-4eb8-b772-c7e6d330cb39)

Low Importance:
1) It would be nice to be able to turn off the trash bag feature in the config
2) The lamps don't seem to be emitting light for me, I don't know if I'm missing something

### Expected Benefits

Shadow & texture consistency

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Ill dig deeper into the shading issue later today / tomorrow. :) 

Lamps have to be turned on by shift right clicking with an empty hand (if i remember correctly)

**Comment by satisfyu** [comment]
I've changed most models so they match the rotation. 

Also most models using the soft texture now. :) So i'll mark this here as implemented. Thank you!
