### ISSUE TITLE
[Camping] Sleeping Bags in Tents

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [satisfyu/Let-s-Do-Hub#147]
### Mod Name and Version

[Let's Do] Camping

### Suggestion Details

This mod is a breath of fresh air as it's been really hard for me to find camping utilities, in a game like Minecraft even.
I was really surprised to see that you can't place sleeping bags in tents, which seems a bit counter intuitive.

### Expected Benefits

It would be neat if this was possible; I think texture clippings would be acceptable so long as they're on the inside of the tent.

PS: I have no idea what the Multitool does.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
That was actually due to the size of it. So i've just left it over for decorative purposes. :) 

Multitool actually combines a shear, axe and flint and steel

**Comment by Dumpling00** [comment]
Would like to chime in and suggest the ability to make it so sleeping bags don't reset your spawn point, like some other sleeping bag mods do! 

As for the tents, a way to close them could be cool - It could provide safety from mobs when camping outside. Don't think we necessarily need to sleep in them, but I do think they could serve a bit more as a temporary base, and it's hard to do anything with it without the ability to place any block inside of them.
Were they to be closed, they could be a nice temporary way to trap mobs and animals while rounding them / not having fences and leashes available.

**Comment by Robynstar** [comment]
Definitely seconding the sleeping bag not setting your spawn point!

**Comment by satisfyu** [comment]
Sleeping Bags wont set a Spawnpoint anymore with the next update.
