### ISSUE TITLE
Minecraft will not launch with Lets Do mods

### ISSUE THREAD

**Issue by Beambeam1** [satisfyu/Let-s-Do-Hub#15]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.15

### Issue Description

When I try to launch minecraft through modrinth with Lets Do mods installed, it stops for some reason. Works fine with Lets Do mods deactivated. I tried installing "[Let's Do Addon] Compat" but it didn't work.

### Steps to Reproduce

Install Lets Do mods and launch minecraft with modrinth

### Logs

Logs : https://pastebin.com/7jBeugK1

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please downgrade doAPI to 1.2.9 - it's clearly marked as incompatible.
