### ISSUE TITLE
[WilderNature] bounty board placing itself down and causing ghost blocks everywhere

### ISSUE THREAD

**Issue by temyy** [satisfyu/Let-s-Do-Hub#150]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

holding a bounty board in your hand will cause the board to be placed all over the place and cause ghost blocks, video attached
if this is not reproducible on a minimal instance/in dev environment ill do a binary search

https://streamable.com/tiu8xy

### Steps to Reproduce

give yourself a bounty board with the mod installed and look around

### Logs

https://mclo.gs/efQFv0s

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Haven't being able to reproduce this. 

Tested inDev, in a mid sized modpack and on a clean install

**Comment by temyy** [comment]
gotcha, will do a binary search today to figure out the cause

**Comment by temyy** [comment]
seems to be an issue with [Dynamic Crosshair](https://modrinth.com/mod/dynamiccrosshair) or its [Compat](https://modrinth.com/mod/dynamiccrosshaircompat) addon, issue stopped happening after removing those. still conducting further searches

**Comment by satisfyu** [comment]
Ah! 

I remember a similar bug like with Dynamic Crosshair when using the vinery stem

**Comment by satisfyu** [comment]
https://github.com/Crendgrim/DynamicCrosshair/issues/73

Looks like the same issue to me.

**Comment by satisfyu** [comment]
Will be fixed in the next version. :) Thank you!
