### ISSUE TITLE
[Camping] Grill crash

### ISSUE THREAD

**Issue by oof100200** [satisfyu/Let-s-Do-Hub#151]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Using a grill to cook food crashes the server

### Steps to Reproduce

cook food
crash

### Logs

https://pastebin.com/N88vdNCm

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.0.1
