### ISSUE TITLE
[WilderNature] Owl bug

### ISSUE THREAD

**Issue by Ixchavalatarius** [satisfyu/Let-s-Do-Hub#152]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.1 Forge

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When owls spawned using the spawn eggs or the summon command owl's head snaps to look to the side and down and is completely frozen, if hit it will flutter to the ground as normal and then briefly look straight before snapping to aforementioned positioned, but otherwise cannot be interacted with.

Also does not respond to being right clicked. When fed meat, hearts appear as if tamed but can no longer be made to sit or wander and will not follow. WTHIT shows owner as ??? (as it does with all untamed mobs in my instance) even when hearts have shown from feeding meat and also when killed chat message informing of pet's death shows.

 (have yet to find one naturally spawned so unsure if bug occurs then as well)

### Steps to Reproduce

Summoned owl via command or using spawn eggs achieved the same result.
Punched mob to see if this would fix the issue but it did not.
LetsDo API is on the latest version 

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Owls are sleeping during the day. Thats their sleeping pose.

**Comment by satisfyu** [comment]
I've played around it for quite a while and it's indeed working as intended.

During the Day, Owls are sleeping and wont be bothered by anything. During the Night they will wake up and be active. 

https://github.com/satisfyu/WilderNature/wiki/Animals#Owl
