### ISSUE TITLE
[WilderNature] Quite a few issues

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#154]
### Minecraft Version

Fabric 1.20.1

### Mod

BloomingNature

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) All board tiers from 2 up to 5 do not have their titles displayed properly, instead it is just `wildernature.tier*` translation line. 
2) There is tier 2 contract for 35 zombies, which lacks description.
![Lang_entries](https://github.com/user-attachments/assets/33173c17-13bb-4e27-95f5-703f6274b1b1)
3) Hunt 5 Cassowaries contract `Little critters, sharp claws` in game requires to defeat just 1.
4) Cassowaries is misspelled Cassowarys.
5) `Blunderbuss hunter` contract's description states we need to hunt 40 red wolves, but when we take it - actual number is 50.
6) `They are stealing my nuts!` contract for hunting squirrels counts red wolves instead.
7) `Sea sharpshooter` doesn't give any reward. (missed "t" in "contract" in json file)
8) `Blunderbuss Fisher` - same thing as above ^^^
9) For killing elder guardian `Horror of the Seas` according to loottables we are supposed to get blunderbuss, but in contract loot there is just feather.
10) Boars have suspiciously small hitbox (almost like minisheep).
![not_so_mini](https://github.com/user-attachments/assets/11343716-3967-49f9-a6ce-8255c48e26d6)
11) Red wolf hitbox is quite tall.
![tall_boi](https://github.com/user-attachments/assets/5b239780-ee65-4a59-8963-3e6b67ab9ee5)
12) Grown up raccoons have their hitbox higher than their model, and shadow inside the texture. (it also probably causes baby raccoons to levitate)
![10_missed_calls_from_Newton](https://github.com/user-attachments/assets/6baaaa23-6d79-4d43-b267-445ac5069cd2)
13) Pelicans don't deal any damage when attacking.
14) After we tame red wolf or dog and command them to not follow the player technically they do it, but there is no following animation or clear indication that they wait or sit.
15) Red wolves have some kind of protection: they take around 50% less damage from first hit. Is it a bug or is it intentional? (probabaly second, but still) 
16) `Manhunt` probably shouldn't count player killing himself. Also maybe not allow it appear in singleplayer, cause we can't pick up new contract until we finish the current one. I thought about system of dumping contracts in exchange for xp from assigned board, but then it ruins the point of 3 rerolls. (Also i forgot to check what happens if we lose or destroy the contract)
17) Game quit to main menu after i took `Lunar's greatest nightmare` quest. Couldn't reproduce it again, but i'll send the latest log.

### Steps to Reproduce

16)Player can complete `Manhunt` by unaliving self with arrows or trident, possibly other things.
idk what else to describe

### Logs

Also since i am sending the log and not the crashlog, if it is of any help i wanna say i am using tlauncher. I know a lot of people don't like it and i even saw them refuse to help others who use it, so i am not telling things like that often. But i have no idea how logs work, so maybe it'll help:

https://pastebin.com/hNhdBfz9

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
It's intended that Pelicans deal no to little damage only. :)

**Comment by satisfyu** [comment]
1 - 12 are fixed 
13 is intended 
14 is coming with a later update 
15 is intended too 
16 - they shouldnt take this quest on singleplayer :P

**Comment by satisfyu** [comment]
Everything that required a fix was resolved in version 1.0.2. Thank you for the detailed bug report. :)
