### ISSUE TITLE
[Furniture] Streetlamps don't sit on fences/walls

### ISSUE THREAD

**Issue by Zykana** [satisfyu/Let-s-Do-Hub#155]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Streetlamps won't allow placement on blocks such as fences and walls, even on the top surface.

### Steps to Reproduce

Try placing either streetlamp type on top of a fence or wall.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by cqjdzy** [comment]
I don t think it and the palm leaves have the properties of leaves, this could be due to the nbt.
