### ISSUE TITLE
Broken/Missing Blocks: Clothing and Cloche

### ISSUE THREAD

**Issue by ArcherBear** [satisfyu/Let-s-Do-Hub#156]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.0.

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The necktie is acessible via creative but cannot be worn to complete the outfit,
The cloche doesnt seem to work, cann't be placed or used on food? What is its purpose?

### Steps to Reproduce

Downloaded the compact for candlelight and everything else works, looking at logs and community for answers but nobody has run into this yet??

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You can place the gloche on top of placed plates / bowls. 

The Necktie can be combined with a Shirt to get a Formal Shirt.
