### ISSUE TITLE
[Camping] Backpack Problems

### ISSUE THREAD

**Issue by Kamas50** [satisfyu/Let-s-Do-Hub#157]
### Minecraft Version

1.20.1 NeoForge

### Mod

Camping

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1. Equipped backpacks cannot be opened with a key on the keyboard, this also applies to those equipped in the Curios slot.
2. Ender backpacks do not have a unique GUI texture. When I made a resource pack with a dark theme, I saw that it was in the files.
3. The name of the Ender backpacks opened from the inventory does not have a purple tint
4. Copying a Dark End backpack from the world by pressing the mouse wheel gives a light version
5. None of the backpacks equipped in the Curios slot have a texture or sound when equipped
6. Goodybag and Wanderer Bag cannot be equipped in the Curios slot
7. Wanderer Bag has no texture even when equipped in a normal slot

### Steps to Reproduce

Described above

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Kamas50** [comment]
Some of these problems were described by another person, but not all or not in such detail.

**Comment by DuskCrow19** [comment]
I was about to write something similar cause of the same issues...

**Comment by satisfyu** [comment]
There is simply no curios integration yet. 

We only have support for Trinkets at the moment.

**Comment by satisfyu** [comment]
1. / 5.  are because of the missing curios implementation. 
2. I've made the texture but never used it - it currently uses the same texture as Minecrafts Enderchest

All other Issues should be fixed. I've added an additional text to the project description about curios.
