### ISSUE TITLE
[Furniture] Blocks hitboxes don't match their models

### ISSUE THREAD

**Issue by This1Potato** [satisfyu/Let-s-Do-Hub#158]
### Minecraft Version

Forge 1.20.1

### Mod

Furniture

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![imagen_2024-08-08_180401555](https://github.com/user-attachments/assets/535a7c6f-1b5d-4d02-8218-4c3f95840a2e)

This is pretty much it: Fish tanks _and_ clocks don't have full hitboxes, which allows for merging blocks like this. Gramophones don't experience this issue.

### Steps to Reproduce

Even though its possible to put blocks within those spaces, for clocks you have to do it with the help of a block on the side of the clock. Fish tanks though allow you to build anyways.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
That was honestly left out deliberately due to the required effort. Other mods (like Handcrafted and Chipped, to name two) handle it the same way.

I might change this in the future but this unfortunately doesn't have a high priority. Sorry. :(

**Comment by Cicopath** [comment]
I know this is not planned and it's a closed issue, but Chipped and Handcrafted use certain block properties as seen in the pictures (this doesn't account for designs of the blocks that are "sticking out"). Maybe Furniture could implement a similar system some time in the future?

![image](https://github.com/user-attachments/assets/fe44be4a-4846-4c0e-8fc6-50a9e427b5af)
![image](https://github.com/user-attachments/assets/918ecedd-fd3f-49cf-8b33-ad59d7d1e561)
![image](https://github.com/user-attachments/assets/feda6533-30cc-47e8-8e94-4bf4a4227103)


![image](https://github.com/user-attachments/assets/6d5c7c6a-5a04-4fda-830e-edb2baaa511b)
![image](https://github.com/user-attachments/assets/42444188-20c8-4361-bf3c-a6a6b65c9660)
![image](https://github.com/user-attachments/assets/6fd4004c-5f18-432f-8b63-336a08f94c64)
