### ISSUE TITLE
Legacy Brewfesthat crashes client with new Brewery - farm&charm compat mod

### ISSUE THREAD

**Issue by shinei01** [satisfyu/Let-s-Do-Hub#159]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

 2.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

After swapping the Legacy mods with the new Compat versions the client crashes in reason of not rendering the "old" brewfesthat.

### Steps to Reproduce

Swapping Legacy with compat version mod

Be in the same chunk as the "old" brewfesthat was.

getting kicked of multiplayer server

### Logs

[crash-2024-08-09_00.46.35-client.txt](https://github.com/user-attachments/files/16554058/crash-2024-08-09_00.46.35-client.txt)
[debug-1.log](https://github.com/user-attachments/files/16554073/debug-1.log)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in 2.0.1 :) Sorry for the oversight
