### ISSUE TITLE
[WilderNature] Tier 3 contract oversights and hanging banners being air.

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#160]
### Minecraft Version

Fabric 1.20.1

### Mod

BloomingNature

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) `Bigger big game hunter` states we need to hunt 100 bisons, but after taking contract the number is 50. (judging by similar contract correct number is 50)
2) Also it can't be completed, cause in contract json file it says "minecraft:bison" instead of "wildernature:bison".
3) `Small game hunter`(red_wolf_with_bow) has wrong loot in json file: blunderbass_master instead of bow_masterclass.
4) `Master wolf trapper` contract has wrong **description** and **title** in json file: "_masterclass" is missing.
5) With jade installed it says all 3 **hanging** banners are air, but they still drop themselfs when broken and act normal.
![Air](https://github.com/user-attachments/assets/b710875d-0cbc-4f2f-9463-82602c0d5fec)

### Steps to Reproduce

~

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Everything that required a fix was resolved in version 1.0.2. Thank you for the detailed bug report. :)
