### ISSUE TITLE
GAME BREAKING BUG

### ISSUE THREAD

**Issue by SafeOfArsenal** [satisfyu/Let-s-Do-Hub#161]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

THERE IS A EXTRA SPACE IN THE DESCRIPTION. UNPLAYABLE!!!!!
![image](https://github.com/user-attachments/assets/a2042db1-b02c-46b9-958a-ef9fec5900ca)
![image](https://github.com/user-attachments/assets/bfd37b8f-561c-490b-a0bd-5491c87b9594)

### Steps to Reproduce

first sentence under features

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
*insert shaking my head meme here*
