### ISSUE TITLE
[Furniture]Serious bug: display can copy items

### ISSUE THREAD

**Issue by BradClc** [satisfyu/Let-s-Do-Hub#162]
### Minecraft Version

1.20.1 forge

### Mod

Furniture

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

 furniture:display can copy items.
 When you have more than one item in your hand, after you put it in furniture:display, you can take it back multiple times. The number of items you take back in a single time is based on the number of items in your hand before you put it in display. 

### Steps to Reproduce

just do as my desciption

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I fixed the bug by making sure only one item goes into the display at a time and the player's inventory is properly updated when they add or take items
