### ISSUE TITLE
[Candlelight] Craftingrecipes are swaped

### ISSUE THREAD

**Issue by shinei01** [satisfyu/Let-s-Do-Hub#163]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

 2.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The craftingrecipe of the glass and wine glass are swaped

### Steps to Reproduce

it's not really a problem and if you know that it's fine 

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed this for the next release

**Comment by satisfyu** [comment]
Fixed in 1.0.1
