### ISSUE TITLE
[Camping] Tent showing wrong colour in Jade tooltip

### ISSUE THREAD

**Issue by Robynstar** [satisfyu/Let-s-Do-Hub#164]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.01

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When looking at my white tent (tested with other colours too) the Jade tooltip shows the red icon:
![2024-08-09_23 05 13](https://github.com/user-attachments/assets/a40eb366-5c88-4d1e-aff4-dac1b42efd35)
Except for when selecting the two front right blocks:
![2024-08-09_23 06 50](https://github.com/user-attachments/assets/eef67031-0e24-4fc6-8976-9d531ea5007e)

### Steps to Reproduce

Install Jade https://www.curseforge.com/minecraft/mc-mods/jade/files/5493390
Install Camping
Place a tent
Look at it

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Jade is colorblind 👀

**Comment by satisfyu** [comment]
Will be fixed in the next update.

**Comment by satisfyu** [comment]
Fixed in 1.0.2
