### ISSUE TITLE
[Farm and Charm] Giving yourself any item Creative mode gives the Harvest of the Wild achievement

### ISSUE THREAD

**Issue by Robynstar** [satisfyu/Let-s-Do-Hub#165]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

This is a very odd one. If you have Farm and Charm, start a new creative world, give yourself any item, you will get the "Harvest of the Wild" achievement...
![2024-08-09_23 22 49](https://github.com/user-attachments/assets/0d25d657-cd8f-4f96-804b-455a9aa94482)
I initially had this happen with the Camping tent, so I tried crafting one in survival mode instead (in a new creative world) but the achievement did not fire.
In another new world I tried switching the gamemode to survival and back then giving myself the item, but still got the achievement.
So I made another new world and thought I would try crafting it in creative mode... and got the achievement as soon as I gave myself a crafting table and so found out it was actually any item that caused it.
I did also try another new world set to survival mode with cheats on, immediately switched to creative mode and gave myself an item, ta-da achievement

### Steps to Reproduce

Install Farm
Start a new world
Give yourself any item in creative mode
See Harvest of the Wild achievement

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be "fixed" in the next update.
