### ISSUE TITLE
[Wilder Nature] Tetra - Crash on creating new world

### ISSUE THREAD

**Issue by niftybottle** [satisfyu/Let-s-Do-Hub#166]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.1 - Forge (Wilder Nature), Forge 47.3.0, Tetra 6.4.0, mutil 6.1.1 (Tetra dependency), Architectury 9.2.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) When Wilder Nature (forge version) and Tetra are both installed, Minecraft will crash when attempting to make a new world. 
2) It also will fail to load a previously existing world, complaining about data pack error. Using the "safe mode" vanilla only data pack will still fail, declaring the world corrupt.
3) As a side note, Wilder Nature is not available to select on the related mod dropdown on this form

### Steps to Reproduce

Have both Wilder Nature and Tetra installed on forge for Minecraft 1.20.1. Click on single player on the main menu, click create new world.

### Logs

https://pastebin.com/GVWihe3h - Crash Log
https://pastebin.com/jTAE6b9b - Latest.log
https://pastebin.com/5wFNCgFH - Debug.log

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.0.3
