### ISSUE TITLE
[BloomingNature] Tree Cutting mods incompatible with bloomingnature trees + Leaves not decaying

### ISSUE THREAD

**Issue by Dragunsblood** [satisfyu/Let-s-Do-Hub#167]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

tried multiple mods and datapacks for felling trees in one go, and found that the new trees are incompatible with them. additionally, trees broken manually do not have their leaves decay at all.

### Steps to Reproduce

download a tree felling mod or data pack (like treecapitator/tree harvester)
attempt to break tree using axe
tree does not break in one go
break tree manually
leaves do not decay

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by FinnArt** [comment]
I'm also having the same issue, hoping there's a way to fix this :(
