### ISSUE TITLE
[Vinery] Server crashes every time the Winemaker tries to spawn.

### ISSUE THREAD

**Issue by SaladSupreme** [satisfyu/Let-s-Do-Hub#168]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.27

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

My server keeps randomly crashing, and by the looks of it, its everytime the wandering winemaker tries to spawn, the server crashes. He was able to spawn twice successfully, but its been about 5 times when the server crashed because of it.

### Steps to Reproduce

When the mod tries to spawn it, the server crashes.
Spawning him and the mule in manually does not replicate the crash.

### Logs

https://pastebin.com/gZc7eTJN

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I need a full crashlog. The one you have uploaded is not complete.

**Comment by satisfyu** [comment]
I am closing this issue due to a lack of information.
