### ISSUE TITLE
[Camping] Mod Incompatability with Applied Energistics 2

### ISSUE THREAD

**Issue by TecmagDiams** [satisfyu/Let-s-Do-Hub#169]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Conflict with Applied Energistics 2 & [Let's Do] Camping
I have tested now with just these two mods and get the crash (while as long as ONE of them is disabled my large mod pack loads)

**Minecraft Version**: 1.20.1
**Forge Version**: 47.3.5
**[Let's Do] Camping Version**: letsdo-camping-forge-1.0.1
**Applied Energistics 2 Version**: appliedenergistics2-forge-15.2.11

### Steps to Reproduce

1. Install both [Let's Do] Camping **and** Applied Energistics 2 (with dependencies)
2. Attempt to run

### Logs

https://pastebin.com/iP5tN1v1

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.0.2
