### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by benio1394** [satisfyu/Let-s-Do-Hub#17]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.11

### Issue Description

The game crash on initializng

### Steps to Reproduce

Probably everything necessary is in pastebin link

### Logs

https://pastebin.com/z2Jq8DYS

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Downgrade DoAPI to 1.2.9. 

https://modrinth.com/mod/do-api/version/AvzyS3V7
