### ISSUE TITLE
[Furniture] 

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#170]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

You can place blocks inside of a fish tank.
![image](https://github.com/user-attachments/assets/a6c5b489-dd96-4800-a6f0-bea6b7b9c3e8)
![image](https://github.com/user-attachments/assets/24eb11fd-9490-4b4c-8f76-d5c4e1333e35)

Note: I am playing with multiple mods. I did not try this with the Furniture mod itself.

### Steps to Reproduce

1. Download Furniture 1.0.2 & dependents, and install Fabric 1.20.1-0.16.0
2. Launch Minecraft with the mods, and open or create a new world
3. Place a Copper Tank or Iron Tank
4. Place a block inside the right side of the tank by simply looking at a block it is touching and right-clicking the side blocked by the tank

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue. 

https://github.com/satisfyu/Let-s-Do-Hub/issues/158
