### ISSUE TITLE
Startup crash due to error from camping

### ISSUE THREAD

**Issue by atkabdlh** [satisfyu/Let-s-Do-Hub#173]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

both 1.0.0 and 1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Here's the crash error
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'camping'!

Removed camping and minecraft can launch without problems.

### Steps to Reproduce

1. Updated all my mods to 1.20.1 (sorry for the other unrelated mods)
2. Launch Minecraft 1.20.1 by using Fabric

### Logs

https://mclo.gs/tHeHdpR

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You're missing trinket API. :)

**Comment by atkabdlh** [comment]
i see thank you!
