### ISSUE TITLE
[Farm and Charm] Mincer recipes for gold and iron horse armour give wrong nuggets

### ISSUE THREAD

**Issue by Robynstar** [satisfyu/Let-s-Do-Hub#174]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Gold armour is giving iron nuggets, and iron armour is giving gold nuggets.
![2024-08-11_00 04 51](https://github.com/user-attachments/assets/4133e98e-af8e-4464-a657-6e006e97eb5b)
![2024-08-11_00 05 28](https://github.com/user-attachments/assets/094a1b10-9179-4e5b-94ff-5e552c657f93)

### Steps to Reproduce

Install Farm and Charm
I guess install JEI as well.
Click through the mincer recipes.
Or just try putting the armours into the mincer, I have confirmed they do actually give the wrong ones.
![2024-08-11_00 16 31](https://github.com/user-attachments/assets/f939b2af-b493-479a-b3a5-0b8349789a3c)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in 1.0.1.
