### ISSUE TITLE
Problem [Let's Do] WilderNature

### ISSUE THREAD

**Issue by Maxiik2** [satisfyu/Let-s-Do-Hub#175]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![Снимок экрана 2024-08-10 012144](https://github.com/user-attachments/assets/2634697c-a4ff-48b7-a7bf-5332717fd6e2)
![Снимок экрана 2024-08-10 012209](https://github.com/user-attachments/assets/7c0290b3-1c55-4614-aede-f513f09c055a)
![Снимок экрана 2024-08-10 012251](https://github.com/user-attachments/assets/acd4ffb5-bcb3-4089-bfa3-8d9f5f5033ad)
![Снимок экрана 2024-08-10 012223](https://github.com/user-attachments/assets/46d69aa6-34b1-4966-968d-d7af13d5fa1b)
a problem with the patron's crafting , the book has errors

### Steps to Reproduce

open a book

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update WilderNature to 1.0.1 - the recipe was fixed in the last update. 

The Compendium clearly shows that it's still a WIP.
