### ISSUE TITLE
[Vinery] Apple Press multiblock works as 2 separate Apple Presses one on top of the other

### ISSUE THREAD

**Issue by cj09bruno** [satisfyu/Let-s-Do-Hub#176]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.27

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Apple press is actually 2 separate machines, the bottom block one, and the top another, this makes it a bit of a pain to use, is this intended ?

a consequence of this is that only the bottom can be use with hoppers to remove the apple mash from the apple Press.

### Steps to Reproduce

1- Look at bottom block of apple press and right click to open lower instance, the opposite to open the top instance

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've changed it so you can only interact with the lower part.

**Comment by cj09bruno** [comment]
> I've changed it so you can only interact with the lower part.
I appreciate you looking into it. 

Have a great day.

**Comment by satisfyu** [comment]
Published.
