### ISSUE TITLE
[Furniture] Music disc volume doesn't scale with distance

### ISSUE THREAD

**Issue by DmitriBogdanov** [satisfyu/Let-s-Do-Hub#177]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Volume of music discs "Pride" and "Let's Do Theme' doesn't respect distance from the jukebox.

#### Issue:

Place any disc in the vanilla jukebox and fly away. The sound should get quieter with distance, but it stays the same volume (aka loud).

#### Here's why it happens:

Files `./assets/furniture/sounds/cphs_pride.ogg` and `./assets/furniture/sounds/letsdo_theme.ogg` should be saved as `Mono` rather than `Stereo`.

Minecraft doesn't know how to properly handle volume for `Stereo` audio files, `Mono` is the correct format used by vanilla recordings. Weird quirk, so it's frequently missed.

### Logs

No need for logs in this context.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by brisingraerowing** [comment]
This explains why I randomly hear these in my world (Sophisticated Backpacks Jukebox Upgrade on a mob).

**Comment by satisfyu** [comment]
Oh my God - thank you so much for this explanation!

This issue has been haunting me for so long, and I could never figure out why it was happening like this
