### ISSUE TITLE
[Candlelight] Other modded rings stick out of jewelry box

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#178]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Modded rings from other mods stick out of the jewelry box if the ring design is too large and the box is closed. It's not a game-breaking issue, just unsightly is all. This is only an issue if you dislike the sight and plan to add compatibility with other modded rings. Below is an image of a Jewelry RPG Series Citrine Ring in the jewelry box.
![image](https://github.com/user-attachments/assets/d51759f6-00e2-4c2c-8d30-d0f0bd374afe)

### Steps to Reproduce

1. Download Candlelight and another mod that add a large ring
2. Make sure the mods that add rings are compatible via the `candlelight:rings` item tag
3. Launch Minecraft and open up/create a world
4. Place the large ring in the closed jewelry box

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in 2.0.1. Thank you.
