### ISSUE TITLE
[Farm and Charm] Tea jugs duplicate bottles and mincer has few wrong recipes

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#179]
### Minecraft Version

Fabric 1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) "Farmland finery" advancement triggers when we use pitchfork on fertilized soil, but it is supposed to be hoe.
2) There are two mincer recipes for stripped crimson log. One of them is supposed to be for **crimson log** (stem) and other one is for **crimson wood** (hyphae).
3) Same goes for stripped **warped** stems and hyphae. ^^^
4) Mincer recipe for **deepslate** iron ore has **usual** iron ore instead.
5) When we right-click with glass bottle on any tea jug, bottles don't get consumed. (or rather they get consumed and immediately returned back)
6) If we have exactly 1 tea cup in hand and we drink it, it doesn't return empty bottle.
7) I am not sure Cluck effect is working. When applied to chicken or player it does nothing: no feathers nor eggs.

### Steps to Reproduce

~

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be all fixed - beside of 1.. Thats happening because the Pitchwork also counts as a Hoe.
