### ISSUE TITLE
Cake Station wont work

### ISSUE THREAD

**Issue by UsagiMoon19** [satisfyu/Let-s-Do-Hub#18]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.20.1

### Issue Description

Hi so I added your mod lets do bakery to my smp server and the cake station wont work like when we click it, it wont open how do we fix this?

### Steps to Reproduce

Idk I just want to know how to fix it

### Logs

I cant really show you thats its not working

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Bakery/wiki/Blocks#Caking-Station

Caking Station works without an GUI.

**Comment by UsagiMoon19** [comment]
> https://github.com/satisfyu/Bakery/wiki/Blocks#Caking-Station
> 
> Caking Station works without an GUI.

ok so how do I make it work?

**Comment by satisfyu** [comment]
As described in the wiki:

> The starting product to begin the manufacturing process is always a Cake Dough. Make sure your off-hand is free, and you hold the Cake Dough in your main hand - then click on the Caking Station to place raw cake batter.
> 
> Now you have the following options:
> 
> Use Jam to make a cake Use a knife to cut the raw cake batter and then process it into cupcakes with Jam Use a knife first and then a Rolling Pin to cut and roll the raw cake batter and then process it into cookies with Jam Upon completion, you can dismantle and pick up the respective end product.
