### ISSUE TITLE
[BloomingNature] Swamp Oak Saplings Grow with Oak Logs and Leaves

### ISSUE THREAD

**Issue by basestar237** [satisfyu/Let-s-Do-Hub#181]
### Minecraft Version

1.20.1

### Mod

Blooming Nature

### Mod Version

1.0.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Placed Swamp Oak Saplings grown into trees that visually look like the larger swamp oak trees, but with vanilla oak logs and leaves.

### Steps to Reproduce

1. Place a Swamp Oak Sapling
2. Bonemeal Sapling / Wait for Sapling to Grow
3. Tree grows as a large tree using vanilla Oak Logs and Leaves, not Swamp Oak Logs and Leaves.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've fixed it inDev.
