### ISSUE TITLE
[Furniture] Fish tank becomes invisible after relogging.

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#182]
### Minecraft Version

Fabric 1.20.1

### Mod

Furniture

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Fish tank becomes invisible after relogging into the game. Happens with both iron and copper ones.
![2024-08-12_12 16 43](https://github.com/user-attachments/assets/50b33935-aad8-4482-ad31-914634c54597)

### Steps to Reproduce

If it won't happen on first try, try placing it other directions

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Dumpling00** [comment]
Chiming in - this doesn't only happen after relogging, but even after moving far away enough from the fish tanks and then coming back to them!

**Comment by satisfyu** [comment]
Found the issue - just need to get a working fix for it :)

**Comment by satisfyu** [comment]
Fixed! Ill upload the fixed version later today.
