### ISSUE TITLE
[WilderNature] Raccoon crash

### ISSUE THREAD

**Issue by TobiasX128** [satisfyu/Let-s-Do-Hub#183]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.2

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

actually an issue with wildernature but no option to report a bug with it.
Something to do with raccoon on serverside I believe

### Steps to Reproduce

unknown

### Logs

https://pastebin.com/tgwwPf9A

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev

**Comment by satisfyu** [comment]
Fixed in 1.0.3
