### ISSUE TITLE
[BloomingNature] Leaves Decaying on Birch and Chestnut trees (v1.0.9)

### ISSUE THREAD

**Issue by Hanley793** [satisfyu/Let-s-Do-Hub#184]
### Minecraft Version

Forge 1.20.1

### Mod

BloomingNature

### Mod Version

1.0.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The Leaves Surrounding Birch logs in the birch forest biome decay, this wasn't an issue on the previous version instead the issue was related to spruce trees but now seems to have shifted onto birch trees. Problem seems to be the same case with chestnut trees in the plains biome.

### Steps to Reproduce

Just looking at the leaves decay.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. Might take a bit until the next version gets released.
