### ISSUE TITLE
[Camping] Multitool doesnt consistently drop two blocks tall plants

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#185]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Yes I'm not actually using the latest version but it wasn't reported in the changelogs
The multitool doesn't seem to drop all 2 blocks tall plants when broken with it, the only example I could find was with Small firs from Meadows, will update if I find more cases.

### Steps to Reproduce

Break a small fir tree with a multitool

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Added an additional check for tall plants.
