### ISSUE TITLE
Game crashing 

### ISSUE THREAD

**Issue by rpmaur** [satisfyu/Let-s-Do-Hub#186]
### Minecraft Version

1.20.1 forge

### Mod

Farm and Charm

### Mod Version

1.0.1 

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

It's the first time I've reported an error so I'm not sure what information I should provide but my game crashes every time I try to enter with this mod downloaded, I've already downloaded all the other ''lets of the mods'' and none of them had this problem. I don't know if it's not compatible with something else I'm using or what. I tried to download the old version too but it didn't work aswell

### Steps to Reproduce

tlauncher > play the game

### Logs

a

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I would need a crashlog - otherwise it's nearly impossible to give assistance. :)

**Comment by rpmaur** [comment]
[novo 1.txt](https://github.com/user-attachments/files/16591094/novo.1.txt)


i coulnd use pastelbin idk if this helps

**Comment by satisfyu** [comment]
It says you don't have Farm&Charm installed

**Comment by rpmaur** [comment]
[crash1.txt](https://github.com/user-attachments/files/16591255/crash1.txt)
does it still say it?

**Comment by satisfyu** [comment]
Mod ID: 'doapi', Requested by: 'bakery', Expected range: '[1.2.3,)', Actual version: '[MISSING]'

Now you're missing the doAPI

**Comment by rpmaur** [comment]
huh strange i do have it downloaded
[novo2.txt](https://github.com/user-attachments/files/16591342/novo2.txt)

**Comment by satisfyu** [comment]
Thats not a crashlog.

**Comment by satisfyu** [comment]
Just make sure you have following Mods installed: 
* Architectury API 
* DoAPI 
* Farm&Charm 
* other let's do mods 

I unfortunately don't really have the time to look at 50 different crashlogs just to fumble and find the next missing mod.
