### ISSUE TITLE
[Camping] Game crashes/freezes when the backpack is in the backpack trinket slot

### ISSUE THREAD

**Issue by fredy667** [satisfyu/Let-s-Do-Hub#187]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The game starts normally, but everything freezes when I equip the backpack in any trinket slot.

### Steps to Reproduce

If the backpack isn´t equiped the game runs normal.
I'm using Fabric loader last release.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Can't reproduce it. 

Tested with multiple modpacks (BCG, AoF, my own) as well as a minimal instance.

**Comment by satisfyu** [comment]
I have improved/refined the entire logic, which should prevent this from happening.

**Comment by fredy667** [comment]
The issue has been solved with the latest update.
Thank you so much!
