### ISSUE TITLE
Can't open Big Barrels with right click

### ISSUE THREAD

**Issue by Darkfiremario** [satisfyu/Let-s-Do-Hub#188]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.9(legacy) & 2.0.1 (Farm&Charm Compat)

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I can't open Big Barrels for storage use.

### Steps to Reproduce

Place down Big Barrel then press right click.

### Logs

https://pastebin.com/mJXckC2r

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
That's not a feature.

**Comment by LoSprema** [comment]
on youtube all the guide shows how can you open the bigbarrels
