### ISSUE TITLE
[Bakery]Crashing while placing small cooking pot

### ISSUE THREAD

**Issue by Beedy1228** [satisfyu/Let-s-Do-Hub#190]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.15

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I run a private multiplayer via bisect and we're using BCG+w/cobblemon modpack, We've reached a point where we started doing Bakery stuff and now everytime we try to place Small cooking pot, it crashes our game, NOTE: it does not crash the server and in singleplayer the cooking pot works just fine. heres the initial error popup we get everytime

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property class_2758{name=damage, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]} to 50 on Block{bakery:small_cooking_pot}, it is not an allowed value

### Steps to Reproduce

Run BCG+w/cobblemon, log in to multiplayer server, try to place small cooking pot on the stove, crash

### Logs

https://pastebin.com/fqtCk1TG

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Check the Modversion you're Server is running.

**Comment by Beedy1228** [comment]
server is running the same mod versions as we are, 1.1.15

**Comment by satisfyu** [comment]
This should be fixed in 2.0.1. Thank you. :)
