### ISSUE TITLE
[Farm & Charm] Scarecrow swing speed increases when placed more

### ISSUE THREAD

**Issue by Tehemo** [satisfyu/Let-s-Do-Hub#191]
### Minecraft Version

1.20.1 Fabric

### Mod

Farm and Charm

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The more scarecrows on the screen, the faster the scarecrows swing.

### Steps to Reproduce

Enter game with farm and charm, place scarecrows, place more of them, swing speed increases.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've fixed this inDev. Thank you!
