### ISSUE TITLE
[Farm & Charm] Stuck on world loading

### ISSUE THREAD

**Issue by oof100200** [satisfyu/Let-s-Do-Hub#192]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When i added this mod on my server, it's just stuck at 100%,Then i deleted this mod it works. 

### Steps to Reproduce

1. Added this mod on server
2. Stuck at 100%
3. In the latest.log I see a lot of Incorrect key about Farm & Charm, would you mind checking that? 

### Logs

https://gist.github.com/oof100200/c90e091b9c876c7306e3d597ee33645b

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Would you mind testing it again when you remove WorldEdit?

**Comment by oof100200** [comment]
> 当您删除 WorldEdit 后，您介意再测试一下吗？

It's still stuck.

**Comment by satisfyu** [comment]
Send me the log please without WorldEdit installed.

**Comment by oof100200** [comment]
> 请将未安装 WorldEdit 的日志发送给我。

I tested it again, but this time it works. Looks like it's a worldedit problem.

**Comment by satisfyu** [comment]
I'll mark it as incompatible.

**Comment by oof100200** [comment]
> 我会将其标记为不兼容。

it will fixed?

**Comment by FatherPigeon** [comment]
I had this same issue a few days ago, really hoping it'll get fixed <3

**Comment by oof100200** [comment]
> 几天前我也遇到了同样的问题，真心希望它能得到修复 <3

Maybe you should try Axiom. it's better than Worldedit. :D

**Comment by FatherPigeon** [comment]
I would, but the mods that I'd like to use with this mod are only available in forge D:

**Comment by oof100200** [comment]
> I would, but the mods that I'd like to use with this mod are only available in forge D:

I also use the neoforge, you can pair it with a connector to use axiom

**Comment by geegehub** [comment]
I am also experiencing issues between WorldEdit and Farm & Charm. 
I have created the following modded instance of Minecraft:
Forge 47.3.0
[Let's Do] API 1.2.15
[Let's Do] Farm & Charm 1.0.1
Architectury API 9.2.14
WorldEdit 7.2.15

The crash report points towards Minecraft timing out while WorldEdit tries to map the instance's blockstates.
I have used WorldEdit with the [Let's Do] mods before, in a modpack with over a hundred mods total without issue. 
However Farm&Charm in specific, with nothing else but its own dependencies and World Edit, cannot load on a server without crashing.

**Comment by satisfyu** [comment]
It would be nice to know because of which exact blockstate.

**Comment by satisfyu** [comment]
I'll do a "Process of elimination" as soon as i have time. But theres currently lots of stuff going on in real life so it might take a bit.

**Comment by satisfyu** [comment]
Short update: 
Already had time to track it down. It's caused by the MincerBlock / CraftingBowlBlock.

**Comment by geegehub** [comment]
That was fast! Thank you for taking a look at this. I talked to a WorldEdit developer prior to posting my comment in order to try to find out what the issue between the two mods was, and of the developers explained that Minecraft was timing out while WorldEdit was listing through block states. I apologize for not being able to point you in the exact direction of what blockstate was the culprit, there wasn't any info on my end that pointed towards a culprit and I don't know enough about java to have dug through your repository looking for the issue.

**Comment by satisfyu** [comment]
I think i've fixed it. I'll do some more testing tomorrow and then release it. Thanks to everyone for participating!

**Comment by sugan-reden** [comment]
Hi, 
I am at a loss at what to do.
I also get this issue where I get stuck at 100% loading, although I can't for the life of me determine what mod it is coming from.
It seems to me that it loads up to a certain point, then gets stuck (or timed?) waiting for something and loops indefinitely.
This was the only place where I found an issue that seemed similar to what I am experiencing.

Here is the latest log:
https://gist.github.com/sugan-reden/fa15de06eeacec7d61e6530ac3847b26

Quick mention for the thread, I am **not** using WorldEdit or Axiom.
Hopefully someone will be able to help.
I greatly appreciate any help I could receive. Keep up the good work!: 👍
