### ISSUE TITLE
[Furniture] gramophone and vinurl compatibility

### ISSUE THREAD

**Issue by glittermutt** [satisfyu/Let-s-Do-Hub#193]
### Mod Name and Version

Furniture

### Suggestion Details

hi! it would be very cool if the gramophone could play music discs created by the [vinurl mod](https://modrinth.com/mod/vinurl)! currently, if you insert a music disc made with this mod into the gramophone, its visually inserted and you can take it out, but the actual music wont start sadly :( would be awesome if it was fully compatible

### Expected Benefits

cool custom music discs that can be played with a cool block :D

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Thats not planned, sorry. :)
