### ISSUE TITLE
[Vinery] Clark Wine shows high Double Jump amplification when it shouldn't

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#194]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.27

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Clark Wine shows that it gives Double Jump VI, but drinking it only gives Double Jump II, which is intended.

I understand why it's intended to receive Double Jump II—I just tested what Double Jump VI was like and oh my goodness 🤣This is just a visual issue is all.
![image](https://github.com/user-attachments/assets/cccc6fad-7152-4010-a473-133b70f09644)

### Steps to Reproduce

1. Drink Clark Wine that has been aged to display the Double Jump effect at an amplification of at least 2 (amplification of 2 displays as "III" in game).
2. Check the effect amplification in your inventory.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Just changed it so it wont be affected by Wine Aging anymore.

**Comment by Cicopath** [comment]
I know you _just_ closed this, but it appears that this is also an issue with `vinery:lilitu_wine` (Partystarter) as well. I don't know if there are any more wines that have restricted effect amplifications. Did you happen to change the aging for these wines too?
