### ISSUE TITLE
[BloomingNature] bloomingnature:sand can float in the air

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#195]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

`bloomingnature:sand` block is not affected by gravity. I know some mods, like Cinderscapes, have similar blocks that get destroyed rather than affected by gravity when the "full" block below it is broken.
![image](https://github.com/user-attachments/assets/9b911ca7-b4db-4183-8c0e-c6310b0d7780)

### Steps to Reproduce

1. Place `bloomingnature:sand` on top of a block, then break the block underneath the sand.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thats intended behaviour. 

Feel free to ask such questions before in the Discord. :)
