### ISSUE TITLE
[Brewery] Hops body loottable and climbable tag for hops

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#196]
### Minecraft Version

Fabric 1.20.1

### Mod

Brewery

### Mod Version

2.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1. hops_crop_body was missing loottable for quite some time, it should probably be similar or identical to hops_crop loottable (drop seeds and hops if there were any).
2. I noticed there is a climbable tag, but it works only for the top part of hops ("brewery:hops_crop"), so if intention was to make it all climbable, then adding "brewery:hops_crop_body" should do it:
![Climbable_tag](https://github.com/user-attachments/assets/019029e1-be86-43d7-8262-e0d0110bc4e2)

### Steps to Reproduce

~

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev.

**Comment by satisfyu** [comment]
Fixed in 2.0.2
