### ISSUE TITLE
[Brewery] The game crashes when Dark Brew is placed

### ISSUE THREAD

**Issue by oof100200** [satisfyu/Let-s-Do-Hub#197]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

2.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

game crashes when Dark Brew is placed.

### Steps to Reproduce

1.place dark brew
2.game crashed

### Logs

https://pastebin.com/KSjNDhSb

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev.

**Comment by satisfyu** [comment]
Fixed in 2.0.2
