### ISSUE TITLE
[Camping] Problems with wearing a backpack on the chest/back slot

### ISSUE THREAD

**Issue by TeaLoVeR113** [satisfyu/Let-s-Do-Hub#198]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

Camping- 1.0.2 - FABRIC - 1.20.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

In this version, in compatibility with the Trinket mod, the backpack can be put on the slot at the back (but then you can’t put on the bib, because for some reason it comes off), but when you open the backpack with the hotkey, its inventory opens, and it disappears forever, with all the things in it.

### Steps to Reproduce

1. Put the backpack into the slot at the back.
1.1. If possible, wear a bib.
2. Open the backpack using the hotkey.
3. Cry.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by leafyp** [comment]
Seconding this issue, just faced this myself. Placing the backpack down works just fine, but the hotkey is bugged.

**Comment by linkagejr** [comment]
Thirding this issue. I can open the backpack screen once, but then the backpack disappears outright from the back slot and can't be open again.

**Comment by satisfyu** [comment]
Took me a bit, sorry. 

This has been fixed inDev.

**Comment by satisfyu** [comment]
Fixed in the latest Update.

**Comment by pinkosushi** [comment]
not fixed for me and im on latest

**Comment by Usolia** [comment]
Same for me. Sooo sad, because they are SO cute!

**Comment by Libby996** [comment]
Me too. On 1.0.3.
