### ISSUE TITLE
Unable to make salt in cooking pot

### ISSUE THREAD

**Issue by despa1r-q** [satisfyu/Let-s-Do-Hub#20]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.10

### Issue Description

When trying to make salt with the cooking pot recipe, using either limestone or calcite, the cooking process begins, but at the end the water bucket is consumed and no salt is produced.

### Steps to Reproduce

1. Place down a stove and cooking pot
2. Light the stove
3. Place the ingredients for salt in the pot (either calcite and water, or limestone and water)
4. Wait for the cooking process to finish
5. Water bucket is consumed, no salt is created

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in 1.3.11 :)
