### ISSUE TITLE
[Beachparty] Players getting Kicked by Radio

### ISSUE THREAD

**Issue by shinei01** [satisfyu/Let-s-Do-Hub#200]
### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When switching the radio channel all players on multiplayer server getting kicked except for one

### Steps to Reproduce

be on an server with multiple people
craft the radio
switch the channel
let the kick roulette begin

### Logs

i'm sorry to say that, but it doesn't create an debug log or crashlog with the issue

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
We are currently reworking Beachparty - this also involves the Radio. Hopefully, this will then be fixed once and for all.

**Comment by satisfyu** [comment]
Beachparty is currently being completely revamped, and as a result, this feature has been slightly modified. Therefore, I will close this issue and kindly ask for your patience—the new version will be released soon. Thank you for your understanding. :)
