### ISSUE TITLE
[Let's do API] Crash on enter a server with cobblemon

### ISSUE THREAD

**Issue by rastered26** [satisfyu/Let-s-Do-Hub#202]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

latest

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Im playing a server hosted in Bisecthosting, I have a modpack with cobblemon and after i manualy added the lets do collection to the server i can't join the world, but in local it works with both mods.

this is the error that appears on my screen when i try enter
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/69cb26db-171e-44a7-837a-b2dfd872b4a3">

its not a compatibily issue between lets do and cobblemon, I did a test with only lets do and cobblemon and it works so I not sure what could be the issue

### Steps to Reproduce

install the modpack https://www.curseforge.com/minecraft/modpacks/new-game-2 
- add cobblemon
- add lets do api
- try enter a server

### Logs

https://gist.github.com/rastered26/9f100ff4334021d814a350ed567b20ef

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
DoAPI is made and maintained by Cristelknight which has its own Repository: 
https://github.com/Team-Let-s-Do/DoAPI/issues
