### ISSUE TITLE
[Farm & Charm] Add effect descriptions via JEED

### ISSUE THREAD

**Issue by Blob336** [satisfyu/Let-s-Do-Hub#203]
### Mod Name and Version

Farm & Charm 1.0.1

### Suggestion Details

[JEED](https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions) allows adding effect descriptions to mods like JEI or REI.
"Modders can easily add such descriptions to their effect by adding the string "effect.[mod_id].[effect_name].description" to their language file." - quote from [here](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)

### Expected Benefits

Players won't have to visit wiki to know what certain effects do.

### Check for Similar Suggestions

- [ ] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
<img width="1512" alt="Bildschirmfoto 2024-08-18 um 15 49 18" src="https://github.com/user-attachments/assets/70e0834e-274b-4466-a43a-3641a7e80fcb">


Implemented. :)
