### ISSUE TITLE
[BloomingNature] Stone type name change

### ISSUE THREAD

**Issue by etherealgears** [satisfyu/Let-s-Do-Hub#204]
### Mod Name and Version

BloomingNature

### Suggestion Details

Not sure if this should be a suggestion or a bug report since I dunno if it's intentional, but I would suggest renaming the stone types "Travertin" and "Laterit" to "Travertine" and "Laterite". Travertine and laterite are actual stone types in the real world, but travertin and laterit don't mean anything. Maybe this is just a spelling mistake? I'd also suggest changing the name of Slate into something else. It's too similar to deepslate despite not looking similar at all. Maybe call it gneiss or something.

### Expected Benefits

I think these changes would result in stone type names that make more sense.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Will be implemented in the next update.
