### ISSUE TITLE
[Camping] Backpacks become invisible on player when equiped to "back" curios slot

### ISSUE THREAD

**Issue by Veynam** [satisfyu/Let-s-Do-Hub#205]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Like the title says, the backpack becomes invisible when equiped to the curios slot. Its still functional and i can open it with H. I just wish I could see on my player model (same as if it was equiped on the chest slot). Pardon If this is intended behavior. I just wish there was a config so we could choose if we want to be vissible or not. I adore your mods, thank you!

### Steps to Reproduce

Equipt backpack to curios "cape" slot.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
There isn't a complete implementation for Curios yet. 

The Forge port is only occasionally available, as mentioned in the description - Camping remains primarily a Fabric mod. However, plans are in place to implement these features in the future.

**Comment by Veynam** [comment]
> There isn't a complete implementation for Curios yet.
> 
> The Forge port is only occasionally available, as mentioned in the description - Camping remains primarily a Fabric mod. However, plans are in place to implement these features in the future.

This is by far the best backpack mod for modern minecraft without any bloat. I adore your mods and I think when you'll add proper curious support, this will be the "go to" mod for backpacks in modern minecraft. Thank you for your response. We will wait patiently

**Comment by satisfyu** [comment]
Fixed in 1.0.4.
