### ISSUE TITLE
[Farm & Charm] Effects

### ISSUE THREAD

**Issue by Saghik** [satisfyu/Let-s-Do-Hub#206]
### Mod Name and Version

Let's do Brewery Forge 1.20.1

### Suggestion Details

Make effects value modifiable, such as duration or power. It would be a great addition for customization

### Expected Benefits

Modpackers could change the duration or the power

### Potential Drawbacks

I don't think there is any drawback

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
> Potential Drawbacks

I really suck at doing configs. :P But i'll look into this.

**Comment by Saghik** [comment]
Thank you! :D
