### ISSUE TITLE
[Candlelight] Bamboo and Basalt stoves not working

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#207]
### Minecraft Version

Fabric 1.20.1

### Mod

Candlelight

### Mod Version

2.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

**Bamboo stove** and **Basalt stove** don't work with any recipes - from Farm&Charm, other compat mods and Candlelight as well.
For example here i tried to make lasagne from Candlelight:
![2024-08-17_21 17 50](https://github.com/user-attachments/assets/5c930b49-57c5-40f9-8eb4-850a57ac616b)

### Steps to Reproduce

~

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
They haven't been properly registered. Fixed inDev. :)

**Comment by satisfyu** [comment]
Fixed in the latest Update.
