### ISSUE TITLE
[Farm & Charm] Mistakes when using a mixing bowl

### ISSUE THREAD

**Issue by Kamas50** [satisfyu/Let-s-Do-Hub#208]
### Minecraft Version

neoforge 1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1. When I try to turn milk into butter or knead dough, the bucket breaks during the kneading process.
2. Dough appears visually during kneading, even if I use an empty bowl or put random objects in it.

### Steps to Reproduce

Described above

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. :)
