### ISSUE TITLE
Some Vinery 1.4.17 issues

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#21]
### Minecraft Version

Fabric 1.20.1

### Mod

Vinery

### Mod Version

1.4.17

### Issue Description

1) "Big dark Cherry Table" d should be capital.
2) Dark cherry barrel displays `block.vinery.dark_cherry_barrel` in game (lang file has old entry of crested barrel).
3) `Stripped_dark_cherry_log` and `Stripped_dark_cherry_wood` have no loottable.
4) Top part of apple press lacks loottable.
5) Advancement menu has missing texture.

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/142563924/4a98580b-ad1c-4f1c-bd7a-8c8e2fa0920e)
6) Config name and entries do not show properly with Mod Menu (at least for fabric).

![2024-04-12_21 57 55](https://github.com/satisfyu/Let-s-Do-Hub/assets/142563924/b8dd0c33-4f0f-4060-aaa4-70d7f1ff49ce)

### Steps to Reproduce

~

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by Tefnya** [comment]
Also wanted to ask if it is okay that I submit a cluster of issues at once?

**Comment by satisfyu** [comment]
It's perfect like this. Will fix these issues later today.

**Comment by satisfyu** [comment]
Everything should be properly fixed in 1.1.18 :)
