### ISSUE TITLE
[Bakery] Bread with Jam and Jam Roll have the same crafting recipe

### ISSUE THREAD

**Issue by temyy** [satisfyu/Let-s-Do-Hub#210]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

2.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

recipe viewers display both items as having the same recipe (a piece of bread + jam) making it impossible to craft both without polymorph
![image](https://github.com/user-attachments/assets/4080d284-6217-4094-bf60-c6fab249596c)
![image](https://github.com/user-attachments/assets/9474ee9b-0e17-42e4-9bec-76f47cd42a60)

### Steps to Reproduce

1. have bakery and its dependencies
2. look at the recipes or use /polymorph conflicts

### Logs

latest.log (probably shouldnt be needed) https://mclo.gs/r49CDVI

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Whoops. Fixed that indev. :) You have to bake the rolls now.

**Comment by satisfyu** [comment]
Fixed in 2.0.1
