### ISSUE TITLE
[Vinery] Minecraft sapling item and block tags not applied to Vinery saplings

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#211]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The dark cherry and apple tree saplings are missing both the `#minercraft:saplings` item tag and `#minercraft:saplings` block tag. See here:
* https://github.com/satisfyu/Vinery/tree/1.20.1/common/src/main/resources/data/minecraft/tags/items
* https://github.com/satisfyu/Vinery/tree/1.20.1/common/src/main/resources/data/minecraft/tags/blocks
Not having these tags is causing numerous incompatibilities.

### Steps to Reproduce

You can see the lack of Minecraft sapling tags in the links above.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. Thank you! :)
