### ISSUE TITLE
[BloomingNature] Ht's Tree chop does not  make the leaves decay on the fir trees

### ISSUE THREAD

**Issue by TRValhalla** [satisfyu/Let-s-Do-Hub#212]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

As the title suggests, when fully cutting a fir tree using Ht's tree chop the leaves do not fall and just stay in the air without ever decaying.

### Steps to Reproduce

I cut wood

Leaves no fall

*sadness*

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Theres no HT Tree Chop implementation yet. It's planned for a future update.
