### ISSUE TITLE
[BloomingNature] (transferred from discord) renaming travertin to travertine

### ISSUE THREAD

**Issue by temyy** [satisfyu/Let-s-Do-Hub#214]
### Mod Name and Version

BloomingNature 1.0.9

### Suggestion Details

this is a very personal nitpick but travertin should be spelled travertin**e**, and this would also allow it to be common tagged with travertine from other mods (eg. natures spirit)

### Expected Benefits

compatibility with tags and peace of mind

### Potential Drawbacks

you might need a datafixer if replacing the whole block id so old worlds with the block dont get corrupted

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
That's actually a duplicated suggestion: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/204
