### ISSUE TITLE
[Camping] Shearing with Multitool

### ISSUE THREAD

**Issue by CrossKnight07** [satisfyu/Let-s-Do-Hub#215]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When shearing a sheep from Meadow (highland, rocky, flecked, etc.) it shears standard white wool instead of the special wool.

### Steps to Reproduce

Shear any meadow sheep with the Multitool from [Let's Do] Camping

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by temyy** [comment]
an addition to this ive noticed using the left click with shears to break leaves/grass/etc appears to not drop anything (as normally would with shears)

**Comment by CrossKnight07** [comment]
Another issue I've seen is when stripping logs, it seems to try and light the log on fire as if flint and steel, but the fire disappears immediately.

**Comment by satisfyu** [comment]
I've reworked it completely. It was a fun idea but unfortunately hard to maintain. :)

**Comment by satisfyu** [comment]
Fixed in the latest Update.
