### ISSUE TITLE
Upgrade support for NutritionZ

### ISSUE THREAD

**Issue by YOUNIN15** [satisfyu/Let-s-Do-Hub#216]
### Mod Name and Version

[Let's Do] Bakery - Farm&Charm Compat, [Let's Do] Bakery - Farm&Charm Compat, [Let's Do] Candlelight - Farm&Charm compat, 

### Suggestion Details

Although this mod has support for NutritionZ, it seems that some items do not have such support, I guess it would not be something difficult to add since the other items do have such support.

### Expected Benefits

It would have more similarity with the other items that do have such support.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Raymind (dev of nutritionz) just confirmed that he will implement this.
