### ISSUE TITLE
(Wilder Nature) Penguins fall in/die in powder snow

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#218]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Penguins can fall in and get killed by powder snow, causing them to die if they roam around close to biomes that can contain some.

### Steps to Reproduce

Spawn a penguin on powder snow

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
That's just the same behaviour as any other Mob in Minecraft. I've checked with Creepers, Horses and Pigs - all of them can fall and get killed by power snow too.

**Comment by Tera458** [comment]
According to the MC Wiki (and verified by myself) [Powder snow](https://minecraft.wiki/w/Powder_Snow) doesn't give any suffocation damage and do not give freezing damage to [snow golems](https://minecraft.wiki/w/Snow_golem), [strays](https://minecraft.wiki/w/Stray), [polar bears](https://minecraft.wiki/w/Polar_bear), [withers](https://minecraft.wiki/w/Wither), and [ender dragons](https://minecraft.wiki/w/Ender_dragon) and only [rabbits](https://minecraft.wiki/w/Rabbit), [endermites](https://minecraft.wiki/w/Endermite), [silverfish](https://minecraft.wiki/w/Silverfish), [shulkers](https://minecraft.wiki/w/Shulker), [vexes](https://minecraft.wiki/w/Vex) and [foxes](https://minecraft.wiki/w/Fox) can walk on it
"Fire-related mobs like [striders](https://minecraft.wiki/w/Strider), [magma cubes](https://minecraft.wiki/w/Magma_cube), and [blazes](https://minecraft.wiki/w/Blaze) take 5♥♥♥ every two seconds (40 game ticks) from freezing." so there is a difference made between cold and hot mobs, considering the environment penguins live in, I still believe they should at least resist to freezing damage
