### ISSUE TITLE
Gravity for sand layers

### ISSUE THREAD

**Issue by Silverbolt666** [satisfyu/Let-s-Do-Hub#219]
### Mod Name and Version

Blooming Nature

### Suggestion Details

Make the sand layers have gravity like effect, so when a block is mined below, they layer falls.

### Expected Benefits

Just a cool feature, with the added benefit of not leaving random sand layers floating around

### Potential Drawbacks

Same as snow, if there is any

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
That's intended behaviour and it's not planned to add gravity, sorry. :)
