### ISSUE TITLE
[Beachparty] Missing hanging coconut name

### ISSUE THREAD

**Issue by Cicopath** [satisfyu/Let-s-Do-Hub#221]
### Minecraft Version

Fabric 1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Hanging coconuts aren't added in the language file.
https://github.com/satisfyu/Beachparty/blob/architectury-1.20.1/common/src/main/resources/assets/beachparty/lang/en_us.json
![image](https://github.com/user-attachments/assets/f1a18b35-184c-4d79-b099-b2b6d6cf4634)

### Steps to Reproduce

1. Have Jade and Beachparty installed
2. Look at the name in the Jade information UI when your character is looking at a `beachparty:coconut_hanging` block
Alternatively, look at the `en_us.json` file.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev.
