### ISSUE TITLE
[Meadow] Incompatible with animal models resource packs

### ISSUE THREAD

**Issue by Leiriad** [satisfyu/Let-s-Do-Hub#223]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I tried to use the resource pack Better Farm animals, but Let's Do Meadow breaks the sheep model and possibly the cow.
![2024-08-20_19 21 22](https://github.com/user-attachments/assets/93a1ed90-fe5f-4288-b900-e01c1115b55d)

### Steps to Reproduce

1. Use minecraft 1.20.1
2. Add Let's Do Meadow
3. Add Better Farm Animal or any resource pack that alter animal models

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Theres no compatibility planned with any resource packs. However, there is a configuration option available to disable the meadow sheep variants.
