### ISSUE TITLE
Buffalo drops raw beef

### ISSUE THREAD

**Issue by benio1394** [satisfyu/Let-s-Do-Hub#225]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Buffalo drops raw beef instead of buffalo meat.

### Steps to Reproduce

1. Kill buffalo

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Can't reproduce it. 

Also loottable shows correct entries. 

https://github.com/satisfyu/Meadow/blob/1.20.1-architectury/common/src/main/resources/data/meadow/loot_tables/entities/water_buffalo.json

**Comment by satisfyu** [comment]
Need more information for this. Otherwise i'll close the issue. The loottable seems to be correct.

**Comment by benio1394** [comment]
I've found a reason - using fleshZ mod cause to overwrite buffalo drop.

**Comment by satisfyu** [comment]
https://github.com/Globox1997/FleshZ/blob/1.21/src/main/resources/resourcepacks/meadow_compat/data/meadow/loot_table/entities/water_buffalo.json

Yep - please report it to fleshz, thank you. :)

**Comment by benio1394** [comment]
Thank you too, I reported  this to Globox
