### ISSUE TITLE
Tables connected textures

### ISSUE THREAD

**Issue by MyreneGourem** [satisfyu/Let-s-Do-Hub#226]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Tables with the Let's Do Candlelight mod and all other tested Let's Do mods does not have properly connected textures, as seen on the image the tables still show the middle legs when in contact with other tables as seen circled in red on the image. 

![2024-08-21_22 06 59](https://github.com/user-attachments/assets/868ded27-5847-4a1a-839e-957e82fe888f)

And on the other side of the table it will still connect as shown on the image here

![2024-08-21_22 14 51](https://github.com/user-attachments/assets/84709a39-59c7-443d-ba7e-289303c8cb43)

### Steps to Reproduce

Create a 2x2 table then two of the four sides will not be properly connected

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Simply because you can't connect them like this - sorry.
