### ISSUE TITLE
Corner connected textures

### ISSUE THREAD

**Issue by MyreneGourem** [satisfyu/Let-s-Do-Hub#227]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

(Also seems to affect at least Bakery, Brewery and Furniture as well) All tested blocks that have connected textures does not have a proper connected texture for corners. This includes but is not limited to Sofas and counters. Here are some images as examples
![2024-08-21_22 29 53](https://github.com/user-attachments/assets/66a1cefc-ef89-4a46-a82c-4aaab7d71aa9)

![2024-08-21_22 30 23](https://github.com/user-attachments/assets/56180641-eb3c-45b2-b78d-b6e19499abc8)

![2024-08-21_22 33 09](https://github.com/user-attachments/assets/6ba2938c-a241-4e0d-884a-e1cacc468710)

And it also seems that Bamboo Counter does not have any connected texture at all as seen on this image

![2024-08-21_22 42 29](https://github.com/user-attachments/assets/7ee96a6c-1802-4ba1-b338-a8c081b71f2e)

### Steps to Reproduce

Place blocks with connected texture like this so that it has a corner

![2024-08-21_22 43 28](https://github.com/user-attachments/assets/1a04e4c3-abb1-415f-9e01-4b0a37cb2769)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
They don't connect like this.
