### ISSUE TITLE
New Sniffer plant.s for Let's Do mods

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#228]
### Mod Name and Version

All

### Suggestion Details

The addition of the Sniffer was welcomed by the community which was soon deceived to only obtain two new decorative plants. I believe the Let's Do mods could use the Sniffer to add rare and unique plants to some of their mods with creative designs and or effects.

### Expected Benefits

Exotic plants could be added and used for original brews/recipes, or simply as imaginative decorations.

### Potential Drawbacks

Considering Sniffers have an 8 minutes cooldown before digging new plants, it could take a while before you obtain a desired seed.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Thats not planned, sorry.
