### ISSUE TITLE
java.lang.IllegalStateException: Duplicate data file ignored with ID vinery:dark_cherry_pressure_plate

### ISSUE THREAD

**Issue by ModernGamingWorld** [satisfyu/Let-s-Do-Hub#23]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

letsdo-vinery-forge-1.4.19

### Issue Description

Launch custom Modpack and crashed

### Steps to Reproduce

1. Update Mod
2. 2 Crash

### Logs

https://gist.github.com/ModernGamingWorld/3ef69bc01c8e4c17c4d3a5a052553ae5

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in the next release. Thank you for your patience.
