### ISSUE TITLE
Typo in an item name

### ISSUE THREAD

**Issue by SamHammie** [satisfyu/Let-s-Do-Hub#230]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.13

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Lasagna is spelled incorrectly and displays as "Lasagne" in game.

### Steps to Reproduce

Craft or otherwise obtain Lasagna.
See the item's name.

### Logs

Not applicable.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I intentionally did not use the distorted American naming conventions. Therefore, no issue.
