### ISSUE TITLE
Lets Do Furniture

### ISSUE THREAD

**Issue by OldPipboy64** [satisfyu/Let-s-Do-Hub#231]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.2 - Fabric

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The music discs from the furniture mod dont have any sound fade so it can be heard from anywhere at max volume if youre within range of the jukebox. This also includes other mods that play the music discs like sophisticated backpacks to be loud when within range

### Steps to Reproduce

Being within range of the jukebox that uses the furniture mod

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Let-s-Do-Hub/issues/177

That's already fixed inDev. I just want to fix another bug first before releasing it.
