### ISSUE TITLE
Advanced fleeing/hunting of scared passive mobs

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#233]
### Mod Name and Version

Wilder Nature

### Suggestion Details

Fleeing passive mobs (like deers and racoons) only run away when you get too close to them. Making it easy to hunt them at a distance.
I believe it would be interesting to make said mobs also flee when one in their group is killed or when a projectile goes near them.

### Expected Benefits

Making groups scatter when one of them is killed and making them flee if you miss your shot would make hunting a bit more intense and interesting in my opinion.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Wont be implemented.
