### ISSUE TITLE
не работает приготовление пищи 

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#234]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Не работает печь для приготовления блюд из мода , не работает жаровая , есть наполовину совместимость с другими модами 

### Steps to Reproduce

пересмотрите работу печи ,жаровни и рецепты крафта 

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Sorry, i dont understand russian.
