### ISSUE TITLE
Добавьте пожалуйста новые культуры  и рецепты 

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#236]
### Mod Name and Version

ферма и очарование 

### Suggestion Details

Томаты и лук уже в моде Восторг фермера ,но никто еще не делал с подобными текстурами и качеством огурцы,перец чили ,голубику, малину,болгарский перец,чеснок ,подсолнечные семечки и шампиньоны.  Есть много игроков кто ищет моды для идеального фермерства , но по культурам мод похож с модом восторг фермера. Из огурцов можно много сделать рецептов например как мариновать огурцы в банке,также можно мариновать помидоры, с огурцами можно придумать рецепт летнего салата из помидоров и огурцов. С помощью  перца чили можно измельчать в мясорубке и получить паприку которую тоже можно использовать в приготовлении новых рецептов ,с помощью голубики и малины можно делать новые пироги,варенье ,тосты с вареньем.С помощью болгарского перца можно сделать салаты,фаршированные перцы, С чесноком можно делать чесночный хлеб, использовать его в маринаде огурцов и томатов, Из подсолнечных семечек можно делать масло для жарки шампиньоны станут разнообразием среди мухоморов и коричневых грибов, из шампиньонов можно делать маринованные шампиньоны ,много новых блюд, 
Примеры текстур 
![photo_2024-08-23_15-24-11](https://github.com/user-attachments/assets/5f1c6bed-b318-4837-8edf-f9e9962c77ec)
![photo_2024-08-23_15-24-37](https://github.com/user-attachments/assets/6be7a5b5-d63b-4c32-97b9-cf542642ebee)
![photo_2024-08-23_15-24-46](https://github.com/user-attachments/assets/b4a66266-bf2e-4ca6-96eb-b2577202bfc3)
![photo_2024-08-23_15-24-54](https://github.com/user-attachments/assets/fe4b2257-9080-41e2-bab5-ab5485fd04c7)
![photo_2024-08-23_15-25-03](https://github.com/user-attachments/assets/8c539d6f-b597-48de-9878-a1de14414e21)
![photo_2024-08-23_15-25-11](https://github.com/user-attachments/assets/64731d8b-1c78-4fb7-ae85-d850244ebd85)
![photo_2024-08-23_15-25-17](https://github.com/user-attachments/assets/65642920-afb4-4e31-a343-b3c132edfeeb)

### Expected Benefits

Мое предложение принесет много преимуществ потому что мод станет намного оригинальней и индивидуальней,интересней. Для любителей хозяйства и огорода станет истинным удовольствием 

### Potential Drawbacks

недостатков нет ;)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Sorry, i dont understand russian.
