### ISSUE TITLE
Please add new cultures and recipes

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#237]
### Mod Name and Version

Farm and charm

### Suggestion Details

Sorry, my English is bad.
Tomatoes and onions are already a farmer's delight, but no one has ever made cucumbers, chili peppers, blueberries, raspberries, bell peppers, garlic, sunflower seeds and champignons with similar textures and quality. There are many players who are looking for mods for perfect farming, but in terms of crops, the mod is similar to the farmer's Delight mod. You can make a lot of recipes from cucumbers, for example, how to pickle cucumbers in a jar, you can also pickle tomatoes, with cucumbers you can come up with a recipe for a summer salad of tomatoes and cucumbers. With the help of chili peppers, you can grind them in a meat grinder and get paprika, which can also be used in the preparation of new recipes, with the help of blueberries and raspberries, you can make new pies, jams, toasts with jam.With the help of bell pepper, you can make salads, stuffed peppers, garlic bread can be made with garlic, use it in a marinade of cucumbers and tomatoes, sunflower seeds can be used to make oil for frying champignons will become a variety among fly agaric and brown mushrooms, mushrooms
Examples of textures
![photo_2024-08-23_15-24-11](https://github.com/user-attachments/assets/5a35d3bd-7edf-427b-a2f7-9c80fb2e2330)
![photo_2024-08-23_15-24-37](https://github.com/user-attachments/assets/ffa1c7c8-071b-4145-9215-d293c3bf74c1)
![photo_2024-08-23_15-24-46](https://github.com/user-attachments/assets/15c943fd-fb6a-41ca-9e3d-c875c4fac211)
![photo_2024-08-23_15-24-54](https://github.com/user-attachments/assets/594fcd3e-9ef0-493c-b2f1-d01c9d6bec81)
![photo_2024-08-23_15-25-03](https://github.com/user-attachments/assets/b958df3a-65ac-49a8-9454-586f289b3686)
![photo_2024-08-23_15-25-11](https://github.com/user-attachments/assets/30c0f7c6-f2da-4217-bac6-3525a06c8f40)
![photo_2024-08-23_15-25-17](https://github.com/user-attachments/assets/6caed86d-7917-4723-bf9b-dfb0476c059d)

### Expected Benefits

My offer will bring many advantages because the mod will become much more original and individual, more interesting. It will be a real pleasure for lovers of farming and gardening

### Potential Drawbacks

there are no disadvantages ;)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Wont be implemented.
