### ISSUE TITLE
Changing/disabling Vinery and Brewery effects

### ISSUE THREAD

**Issue by aercanist** [satisfyu/Let-s-Do-Hub#239]
### Mod Name and Version

Vinery, Bakery 1.20.1

### Suggestion Details

Would it be possible to add an option to change or disable the effects that are applied to the player after consuming wines and beers from the Vinery and Brewery mods?

### Expected Benefits

From what I can see, there's been a lot of messages on Discord asking about the possibility of changing or disabling these effects. In my opinion, most of these effects are just too much, like flying or exploding for example. 
As for me personally, I think these mods are truly great and just perfect for a project that I'm working on (a roleplay medieval server), but these effects ruin it completely.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
I'm sorry to disappoint you, but that is not planned. The effects are the heart of the respective items - in Vinery, even the mod - and without them, they are as useless as a fletching table.

However, you can modify items with mods like KubeJS.
