### ISSUE TITLE
can u make the mugs hallow plz

### ISSUE THREAD

**Issue by monkeybee11** [satisfyu/Let-s-Do-Hub#24]
### Mod Name and Version

brewery

### Suggestion Details

was wondering if you coud make the mug moddels hallow so thing that are tiny are able to fit inside them like the cauldron as a example bc im playing with origen and extra origen im super tiny on my server thort it be funny XD 

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/1711586/4ff6178f-2381-4682-94fb-95713b0670a8)

### Expected Benefits

just some fun for ppl who happen to have tiny things in there world 

### Potential Drawbacks

mite be anoying to code not sure

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
I've implemented this inDev. Will be included in the next update. Have fun hidding! :)
