### ISSUE TITLE
Profession baker

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#240]
### Mod Name and Version

Пекарня 

### Suggestion Details

I'm sorry, my English is bad.
It would be great to add a new profession of a villager as a baker. Baker B could look like an itinerant baker only by already having his own workstation and deals like a baker and could also sell something to him

### Expected Benefits

 I think this is a very good idea because there are already winemaker, brewers, cooks and the like in your other mods. It's also a great idea for those players who like to build villages.
Thank you for the wonderful and high-quality mods, I love them very much and I follow the updates almost every day :)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Wont be implemented.
