### ISSUE TITLE
profession forest medicine man

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#241]
### Mod Name and Version

[Let's Do] HerbalBrews 

### Suggestion Details

I'm sorry, my English is bad.It would be great if, in addition to the cauldron master, a forest healer with a kettle workstation was added, I read in closed sentences that people talked about Earl Grey tea and jasmine tea, so together with these varieties of tea it would be great to add chamomile tea with the effect of soothing or relaxing, mint tea with a calming effect, tea with jasmine with the effect of speed or strength, Earl Grey tea with the effect of good mood :), tea with lemon with the effect of tone (speed and strength), tea with cardamom will get rid of negative effects tea with ginger will get rid of the effect of poisoning, tea with lemon and honey with the effect of restoring health tea with melissa for soothing, tea with thyme. Thus, a forest healer can sell tea with effects and buy herbs and ingredients

### Expected Benefits

I don't want to show that I think your mods are inferior, I just have a lot of ideas and unfortunately I can't create my own mods. I really like all your mods, they are so cool and I want to make suggestions for mods because the author is very nice and responsive. I think with my proposal, the mod will become even more interesting and fits the theme, the effects for tea that I suggested are taken from real life :)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Wont be implemented.
