### ISSUE TITLE
The profession of cheese maker does not work

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#242]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Sorry, my English is bad. When I found out that two professions of a villager were added to the mod, I immediately went to check, but only one profession of a lumberjack works.I tried a lot of items from this mod next to the villager, but nothing worked.:(. It also didn't work to find the cheese maker by tags

### Steps to Reproduce

or has the profession of a cheese maker not been added to the mod, as it should be? if not, please fix it, I have been waiting for a very long time for the profession of cheese maker to appear :(

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Cheesemaker using Cheeseracks, hermit the woodcutter.
