### ISSUE TITLE
Crafting, cooking, and plowing are not working.

### ISSUE THREAD

**Issue by Shade-mine** [satisfyu/Let-s-Do-Hub#244]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I'm sorry, my English is very bad.
Fairova is on the stove, but neither cooking nor the oven and pot are working. All the ingredients required by the crafting recipe are not functioning. The mod description states that the cart and plough are temporarily not working. Either I am doing something wrong, or something is indeed happening.

I would also appreciate if the compatibility with the Farmer's Delight mod could be added, and if it would be possible to place the pitchfork on the ground or a block.

### Steps to Reproduce

There is no answer

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please, stop it. 

Use the discord for things like this and stop spamming questions as issue reports.
