### ISSUE TITLE
[Farm and Charm] The curse of immortality

### ISSUE THREAD

**Issue by DragonRomeo** [satisfyu/Let-s-Do-Hub#245]
### Minecraft Version

1.20.1 

### Mod

Farm and Charm

### Mod Version

1.0.1 - 1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

How to get immortality with smoked mutton ham. (I think problem with buff)

### Steps to Reproduce

1) Eat smoked mutton ham (Копчёный бараний окорок ru_RU)
2) Get buff 'Feast' (Пир ru_RU)
3) We take damage several times until the food level drops to 2 meat legs
4) As long as you have a buff, the food level does not rise above two so that you do not eat
5) When the buff is over, we eat apples until the health level reaches its maximum

_PROFIT_. Now you are Wolverine or Deadpool (Almost immortal). 
Your food bar does not decrease
And u get infinity HP regeneration.
But if you can still die (for example from lava) that curse of immortality is disappearing)
(Drunk milk not helping)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for your patience. I've fixed this and will upload the new version later today.
