### ISSUE TITLE
[Camping] Backpack Conflict with RPG Series Spellbook.

### ISSUE THREAD

**Issue by redbluesky21** [satisfyu/Let-s-Do-Hub#246]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

RPG Series Spellbook item will disappear if backpack taken off the backpack trinket slot.

### Steps to Reproduce

1. Equip backpack in backpack trinket slot.
2. Equip any RPG Series spellbook in the spellbook slot.
3. Click the backpack off the backpack trinket slot.
4. The spellbook will disappear.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update to 1.0.3.
