### ISSUE TITLE
Gramophone: Stackable music disc duplication

### ISSUE THREAD

**Issue by nknobling** [satisfyu/Let-s-Do-Hub#248]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Placing a stackable music disk into the gramophone while holding more than one will result in one disk being removed from the player's inventory.
Removing the disk with sneak + right click gives the player the same number of disks he was holding when he put the disk into the gramophone.

This results in a fast duplication of the used disk, as it is possible to use stacks of 64 disks with some of them.
Which doesn't sound too bad but if you consider Create Mod recycling it becomes an issue fast.

Thank you for your work, me and my community love the mod! :)

### Steps to Reproduce

1. Install [Let's Do] Furniture

2. Install a mod with stackable music discs ([Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries))
3. Place down gramophone
4. Hold a stack of a random stackable music discs (supplementaries:pancake)
5. Place one of the discs in the gramophone
6. Sneak + Right Click to retrieve the disc/s

### Logs

[18:52:32 INFO] [STDOUT]: Popping out record: 64 pancake
[18:52:36 INFO] [STDOUT]: Popping out record: 63 pancake
[18:52:54 INFO] [STDOUT]: Popping out record: 64 pancake
[18:52:57 INFO] [STDOUT]: Popping out record: 64 pancake
[18:53:00 INFO] [STDOUT]: Popping out record: 63 pancake
[18:53:05 INFO] [STDOUT]: Popping out record: 61 pancake

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for your patience. I've just fixed this and will upload the fixed version later today! :)
