### ISSUE TITLE
[Farm & Charm] Unable To Bake Farmer's Bread

### ISSUE THREAD

**Issue by Atsumachi** [satisfyu/Let-s-Do-Hub#251]
### Minecraft Version

1.20.1 [Fabric]

### Mod

Farm and Charm

### Mod Version

v1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Farmer's Bread will not bake in the stove. Other food items can be made in the stove just fine but Farmer's Bread refuses to be baked.

### Steps to Reproduce

1. Place Dough and Water Bucket into Stove
2. Place furnace fuel into bottom slot
3. Progress won't begin in the Stove
![image](https://github.com/user-attachments/assets/3d8b6ae2-96a1-4f65-a4a3-18558d85396e)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update. That was fixed in 1.0.3
