### ISSUE TITLE
[BloomingNature] Large ferns and other plants two blocks high will spawn in snowy taiga like they're cursed.

### ISSUE THREAD

**Issue by oof100200** [satisfyu/Let-s-Do-Hub#254]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Large ferns and other plants two blocks high will spawn in snowy taiga like they're cursed.
![fern](https://github.com/user-attachments/assets/ba1ce823-c8ed-4ae1-a188-cca6a3d231e2)

### Steps to Reproduce

Since you can't grow plants on top of a snow block, it will be chipped off.

### Logs

no

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've fixed that inDev. Will upload the new version later.
