### ISSUE TITLE
[HerbalBrews] Tea Drying in Farm & Charm Silo

### ISSUE THREAD

**Issue by KalWantsPizza** [satisfyu/Let-s-Do-Hub#257]
### Mod Name and Version

HerbalBrews (latest)

### Suggestion Details

Add conditional Farm & Charm drying recipes to HerbalBrews. Consider it a way to add some "fortune" to the dried tea process. Ideas:
1 green tea leaf => 1 dried green tea
1 dried green tea => 1 dried black tea
1 dried black tea => 1 dried oolong tea

### Expected Benefits

Allows for production of tea on a larger scale without automating via create or other methods.

"Fortune" effect for better returns from dried teas

### Potential Drawbacks

Definitely makes getting black and oolong teas much easier than originally intended.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by KalWantsPizza** [comment]
Turns out you can only get one-for-one return in the drying recipe by default. Hmmm....

**Comment by satisfyu** [comment]
Compat addon is planned in the future. Therefore i'll close this suggestion.
