### ISSUE TITLE
Duping with Carry On

### ISSUE THREAD

**Issue by thedreamty** [satisfyu/Let-s-Do-Hub#259]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I found the brewery dupe with Carry On

### Steps to Reproduce

You have to pick up a part of the brewery with Carry On and put it in a different place, after putting the brewery, the past structure remains and so it can be broken like the other part of the brewery (Sorry if it's not clear, I'm using a translator)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Blacklist the brewing station to prevent this.
