### ISSUE TITLE
Loottables, breaking particles and fire logs

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#26]
### Minecraft Version

Fabric 1.20.1

### Mod

Meadow

### Mod Version

1.3.12

### Issue Description

1) No loottables for:
- Rocky bed
- Pine sign and Pine hanging sign (when on walls)
2) `Grain_cheese_block`, `Buffalo_cheese_block` and `Goat_cheese_block` breaking particles are purple.
3) Fire logs can be duplicated (although idk if it is useful in any way).

### Steps to Reproduce

Fire logs duplication:
1. Place one
2. Shift + Right-click
3. Break the remaining part
4. Now we have 2 of them

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in 1.2.13.
