### ISSUE TITLE
[Let's do Vinery] Out of Bounds error when joining servers

### ISSUE THREAD

**Issue by Subthy** [satisfyu/Let-s-Do-Hub#261]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

So, when some (not all for some reason, even tho everyone is using the same pack) players try to join my server with Let's do Vinery, they are met with error
`Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 17067361 out of bounds for length 13` when joining the server, they will show up in chat that they joined, but get automatically disconnected. For some people repairing profile multiple times in a row in CurseFroge app helps, but for some it doesn't.

I am certain that it's this mod, because I cut the modpack that I use in multiple batches and added them one by one in a testing server and made the people that had the issue join. When I added this mod the issue appeared again. Plus I made sure that players that had the issue had the latest GPU drivers and Java 17 installed. I do not think it's the servers fault, as they are able to join on other servers that are hosted on the same machine.

### Steps to Reproduce

1. Setup a server
2. Upload the Let's do Vinery 1.4.28 to it
3. Try joining
4. You might get the error, but you might not.

### Logs

[debug (9).log](https://github.com/user-attachments/files/16828906/debug.9.log)
I am not able to upload the debug to the pastbin.com, as it's too long and crashes the site -_-

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by CryingNova** [comment]
I'm currently experiencing this issue as well on my server.

**Comment by satisfyu** [comment]
Please report it to the DoAPI - it's related to the boat&sign registry, thank you. :)
