### ISSUE TITLE
[Brewery] Brewing station not working

### ISSUE THREAD

**Issue by ghdud1120** [satisfyu/Let-s-Do-Hub#262]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

2.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

An error in which the crafting event does not trigger when adding water and coal ingredients to the Brewingstation

Confirmed to work normally in legacy version 1.1.9

### Steps to Reproduce

After installing the Brewingstation, adding water, hops, oats, etc., and then adding coal, there is no reaction.

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [x] Yes, I have checked for similar issues.

**Comment by Tefnya** [comment]
I just checked with Brewery 2.0.3 and F&C 1.0.3 on both forge and fabric, it seems that everything works.
Make sure you are using latest Farm&Charm version 1.0.3 and lets do api 1.2.15
Also (just in case) legacy recipes won't work in compat version, cause they vere slightly changed: for example for Wheat Beer you need Hops, Dried Wheat and Yeast. All recipes can be viewed with jei or rei installed.

**Comment by ghdud1120** [comment]
OMG! So the recipe for wheat beer is not two dried wheat and one hops, but one dried wheat, hops, and yeast each?

**Comment by Tefnya** [comment]
Yep, exactly)
