### ISSUE TITLE
Dark Cherry Hanging Sign Texture

### ISSUE THREAD

**Issue by StitchLockwood** [satisfyu/Let-s-Do-Hub#266]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The Dark Cherry Hanging Sign has the texture of an Oak Wood Hanging Sign
![2024-09-02_13 43 20](https://github.com/user-attachments/assets/ce2c5500-9e58-4c5b-b9cd-3a022e381ea8)

### Steps to Reproduce

Just place a hanging sign

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/Team-Let-s-Do/DoAPI/issues/35
