### ISSUE TITLE
[Vinery] Perception effect gets stuck If the wearer dies

### ISSUE THREAD

**Issue by NumanSadik** [satisfyu/Let-s-Do-Hub#267]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.2.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The vision is stuck after death
![image](https://github.com/user-attachments/assets/bf0653ae-123d-4ca9-964b-d7ddb82da241)

### Steps to Reproduce

get the effect
then die

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed that inDev. Thank you for your patience!

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29
