### ISSUE TITLE
[Vinery] Modrinth Crash 

### ISSUE THREAD

**Issue by calamitemu** [satisfyu/Let-s-Do-Hub#269]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![image](https://github.com/user-attachments/assets/e57fb42f-9c8e-43fe-a84b-c756282df5f7)
 I have the most recent version of Java, every other mod (including the other Let's Do mods) seems to be fine. I tried both the latest version on the modrinth app and the latest downloaded directly from the site, both give this exact message.

### Steps to Reproduce

- make modrinth modpack
- add vinery (latest)
- make the modpack for 1.20.1
- try to open it 

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I need a crash or latest log.
