### ISSUE TITLE
Fir Leaves do not decay correctly

### ISSUE THREAD

**Issue by tanyan-tanyan** [satisfyu/Let-s-Do-Hub#27]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Issue Description

When chopping down Fir trees, the leaves transition into their "snowless" texture and then they stay on forever. They do not decay.
This happened in a custom modpack, but I verified that this happens in a minimal instance with just REI and the mod itself.

### Steps to Reproduce

1. Grow a Fir Tree from BloomingNature
2. Cut down the logs
3. Ideally set gamerule randomTickSpeed to 100, etc
4. Watch the leaf blocks transition to their snowless texture
5. Nothing happens afterwards. Expected the leaves to decay

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev.
