### ISSUE TITLE
[Wilder Nature] Unlabled Rare Contract

### ISSUE THREAD

**Issue by TheToyDev** [satisfyu/Let-s-Do-Hub#271]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

[Wilder Nature] 1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![image](https://github.com/user-attachments/assets/53f82d37-bc49-4d5d-8a72-6550203ef021)
After taking this contract, killing cod through any method does not increase the counter.

### Steps to Reproduce

Take a rare contract involving killing 200 cod with no name and attempt to complete it.

### Logs

https://pastebin.com/EVEM86Bg

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update WilderNature - you're still one version behind and im 100% certain this was fixed.

**Comment by TheToyDev** [comment]
> Please update WilderNature - you're still one version behind and im 100% certain this was fixed.

Ah, Modrinth only has up to 1.0.2- thats probably why.
