### ISSUE TITLE
[Wilder Nature] Crash with Concurrent Chunk Management Engine (C2ME)

### ISSUE THREAD

**Issue by Lumnyl** [satisfyu/Let-s-Do-Hub#273]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Completing a contract on the bounty board causes an error that boots you back to the menu, if C2ME is installed.

Link to the mod : https://modrinth.com/mod/c2me-fabric

### Steps to Reproduce

1. Install C2ME
2. Complete any contract

### Logs

https://pastebin.com/yMhfxVKq

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
The threading issue causing a `ConcurrentModificationException` when completing a bounty board contract with C2ME installed has been resolved by ensuring the `onFinish` method executes on the server thread. You should be able to finish contracts now without being disconnected. :) Will upload the fixed version later today.
