### ISSUE TITLE
[WilderNature 1.0.3][Fabric 0.16.3][1.20.1]

### ISSUE THREAD

**Issue by NFLD99** [satisfyu/Let-s-Do-Hub#274]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Error when spawning a red wolf via spawn egg
* only happens in our modpack [Fluffcraft](https://www.curseforge.com/minecraft/modpacks/fluffcraft/files/5712736), not happening in a standalone instance

### Steps to Reproduce

Try to spawn a red wolf via a spawn egg

### Logs

https://gist.githubusercontent.com/NFLD99/2c8ec15749ea2ad9074bc362c5f86d32/raw/59d12121f99073d97574c6875217df307c80c93f/latest%20-%20Copy.log

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you very much for your patience!

The error should be fixed in the next update.
