### ISSUE TITLE
Backpacks not compatible with custom player animations [NO CRASH / LOG] - [ONLY VISUAL BUG]

### ISSUE THREAD

**Issue by ThatsCube** [satisfyu/Let-s-Do-Hub#275]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

v1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Not exactly a serious 'bug,' but more of a **visual issue**. There are various resource packs available that add **animations to players**, and with all the ones I've tested, some backpack mods **work fine while others don't**. Let me explain: both **Inmis** and **Quark**, which add **backpacks**, follow the **player's back** perfectly according to the **animation**, but unfortunately, the '**Camping**' mod **does not :(** - (I've attached a video as reference).

**Quark** and **Inmis** **_don't have any official compatibility_**, so I assume it's just a matter of **how the backpack's code is managed** (though I have no technical knowledge in this regard, so I'm _just speculating_). Could it simply be a matter of allowing the **Camping mod** to follow any **player model** regardless of its default animation? Is there a way to fix this by yourself? (obviously keeping the player animations)

Also, is it possible to know if compatibility will be added in the future? Thanks!
VIDEO EXPLANATION: [https://imgur.com/a/5dg2TzN](https://imgur.com/a/5dg2TzN)

### Steps to Reproduce

**Resource Pack Player Animations**: Early Access Fresh Animations (**but the problem also occurs with other similar ones by other creators**) - Powered by Mod: **Entity Model Features** & **Entity Texture Features**

VIDEO EXPLANATION: [https://imgur.com/a/5dg2TzN](https://imgur.com/a/5dg2TzN)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You're using forge?

**Comment by ThatsCube** [comment]
> You're using forge?

Yes, Forge + [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector) 1.20.1.  But I don't think it's related to Sinytra because I encounter this issue even when only using the fabric loader and Camping mod. The problem is purely 'visual'.

**Comment by SaltSouls** [comment]
I should also note that while partially unrelated to this issue, the backpacks don't render while in the curios slot, despite the mod actively supporting curios.

**Comment by ThatsCube** [comment]
> I should also note that while partially unrelated to this issue, the backpacks don't render while in the curios slot, despite the mod actively supporting curios.

+1, I noticed that too and forgot to mention it. Thanks for the note!

**Comment by satisfyu** [comment]
There is currently no Curios integration for rendering the model, only for managing slots.

As a result, this is a dual report: https://github.com/satisfyu/Let-s-Do-Hub/issues/205
