### ISSUE TITLE
brewery station not working

### ISSUE THREAD

**Issue by Corncakez** [satisfyu/Let-s-Do-Hub#277]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

2.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

i've only gotten the brewery station to work once i will put 2 things of dried wheat the a hop, added some water put in the coal and it acts as if i didn't put the ingredients in

### Steps to Reproduce

i don't know

### Logs

.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please check if you have used a valid recipe.

**Comment by satisfyu** [comment]
Alright, it seems we both have been inactive for a while, and based on your description as well as the lack of further details, I will close this issue.

Dried Wheat + Hops is not a valid recipe. For most recipes, you also need Yeast.

You can find also all recipes here: 
https://github.com/satisfyu/Brewery/tree/1.20.1-farmandcharm-compat/common/src/main/resources/data/brewery/recipes/brewing
