### ISSUE TITLE
[Wilder Nature] Hedgehogs don't breed when fed.

### ISSUE THREAD

**Issue by CrossKnight07** [satisfyu/Let-s-Do-Hub#278]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When fed Rotten Flesh, Hedgehogs will not proceed breeding and will simply stand still.

### Steps to Reproduce

1. Spawn in 2 Hedgehogs
2. Feed both Rotten Flesh
3. Nothing happens after

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
`BreedGoal` was missing. I've added it. Thank you for pointing out!
