### ISSUE TITLE
Strawberry Missing Tag

### ISSUE THREAD

**Issue by LightMakerStudios** [satisfyu/Let-s-Do-Hub#279]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

Forge

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Strawberry is missing the proper Strawberry forge tag

### Steps to Reproduce

It's just missing the tag

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/FarmAndCharm/blob/e2fcc73e6b017e21a6b014d73e02d82ef2675a67/common/src/main/resources/data/forge/tags/items/strawberry.json

Isn't this here the proper tag? :) 

However, i've also added the `forge:strawberries` tag.
