### ISSUE TITLE
Chef boots make the game crash

### ISSUE THREAD

**Issue by MikroChris** [satisfyu/Let-s-Do-Hub#28]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.11

### Issue Description

The item "chef boots" make the game crash when wearing them and opening the inventory

### Steps to Reproduce

1. Create or take a chef boots from creative
2. Put them on your boots slot
3. Then it crashes for no reason

### Logs

[crash-2024-05-09_11.50.28-client.txt](https://github.com/satisfyu/Let-s-Do-Hub/files/15265920/crash-2024-05-09_11.50.28-client.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Update DoAPI.

**Comment by MikroChris** [comment]
It crashes with the newest versions of the mods, 
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/136250376/1991bdba-d323-4829-8782-a89c2554c69b)

**Comment by satisfyu** [comment]
Update DoAPI to 1.2.11, update meadow to 1.3.12 - you're meadow version is pretty old and therefore incompatible with newer versions of the API.

**Comment by MikroChris** [comment]
Updated it to newer versions but still crashes, now says this
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/136250376/8e695c6c-d330-48e6-ba47-f64ad5467c6d)

**Comment by MikroChris** [comment]
These are the mods i'm using

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/136250376/c5e87caa-6e08-4351-bb69-0cbdf66d5979)

**Comment by satisfyu** [comment]
Now youre getting the same crash as reported here: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/30

Which has been fixed with version 1.2.13.1: 
https://legacy.curseforge.com/minecraft/mc-mods/lets-do-meadow/files/5333404
https://modrinth.com/mod/lets-do-meadow/version/1.3.13.1

Thank you so much for your patience! :)
