### ISSUE TITLE
Crash when hovering over some items & when the effects of the wine will run out of time.

### ISSUE THREAD

**Issue by X-Machiavelli** [satisfyu/Let-s-Do-Hub#280]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

letsdo-vinery-neoforge-1.5.0-beta-release.jar, letsdo-API-forge-1.3.0-beta-release-forge.jar, architectury-13.0.6-neoforge.jar

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

env: neoforge_21.1.54 client side

The title says it all. I've attached the crash report and log here.
[crash-2024-09-18_00.12.03-client.txt](https://github.com/user-attachments/files/17030773/crash-2024-09-18_00.12.03-client.txt)
[latest.log](https://github.com/user-attachments/files/17030775/latest.log)

This is probably in the same context as the issue in this link. https://github.com/architectury/architectury-api/issues/547

### Steps to Reproduce

The bundle of mods listed above is sufficient for reproduction.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
