### ISSUE TITLE
ServerSide Packet Registries error

### ISSUE THREAD

**Issue by TheoEN22** [satisfyu/Let-s-Do-Hub#281]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When I have Vinery installed on my server, the loading process stalls out during the ServerSide Packet Registries loading process. This doesn't occur when just Farm&Charm and the API are downloaded.

### Steps to Reproduce

Add vinery to the server, start up

### Logs

https://pastebin.com/4vTAu6vV

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by TheoEN22** [comment]
Looking into it (I just have basic modding knowledge), it seems like there's something wrong with either the constructor or the code for generating fluid particles (see [link](https://maven.fabricmc.net/docs/yarn-23w14a+build.6/net/minecraft/client/particle/BlockLeakParticle.html) for the only thing I could find in the documentation that seemed semi-relevant. 

Also, to clarify, this doesn't make my server crash, it just is unable to process the mod so its loading process doesn't continue. This only occurs with my server, not my singleplayer client.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
