### ISSUE TITLE
[F&C] 1.21.1 Crafting Bowl not Crafting (Fabric & Neo)

### ISSUE THREAD

**Issue by KalWantsPizza** [satisfyu/Let-s-Do-Hub#284]
### Minecraft Version

1.21.1

### Mod

Farm and Charm

### Mod Version

1.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Crafting Bowl recipes are registered but do not actually craft in the bowl.

### Steps to Reproduce

place milk bucket in crafting bowl, then attempt to mix. Bowl shows it should be done, but milk bucket remains in bowl and butter is not crafted. Attempted with both Fabric & NeoForge.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
