### ISSUE TITLE
[Vinery] A bug that the age of wine do nothing to buff adding

### ISSUE THREAD

**Issue by BurnedChickens** [satisfyu/Let-s-Do-Hub#285]
### Minecraft Version

1.20.1 forge

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The age of vine didn't work, a 10year age wine give 2 lv buff, an new wine give 2 lv buff too.Also when i changed its config file to lengthen buff duration, it didn't worked too

### Steps to Reproduce

use command to get wine or just get it from Aging Barrel, drink it and check the buff

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed indev.

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29
