### ISSUE TITLE
The model rendering of the bounty board is very strange.

### ISSUE THREAD

**Issue by GTX1080TiBOOM** [satisfyu/Let-s-Do-Hub#287]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Model disappearance

### Steps to Reproduce

https://github.com/user-attachments/assets/5a342b41-4449-493e-9605-b37786f54412

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
The BountyBoard isn't a Block, it's a Model.

Minecraft only renders the parts of the world that are within the camera's field of view. Once a part of an object or model is outside this field of view, it can be hidden or clipped. This is an optimization technique to improve performance, as only what the player directly sees is rendered.  See Frustum Culling.

**Comment by GTX1080TiBOOM** [comment]
Excuse me, how can I modify Frustum Culling? Only when my perspective looks up a little will it be eliminated, and there will be no such problem if I look left, right and down.
