### ISSUE TITLE
[Farm&Charm][1.21.1]Game crash when placing storage pot

### ISSUE THREAD

**Issue by mariaester174** [satisfyu/Let-s-Do-Hub#289]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Game crashes when storage pot is placed on any block. The error is the one below:

The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid block entity doapi:cabinet // de.cristelknight.doapi.common.block.entity.CabinetBlockEntity state at BlockPos{x=-800, y=71, z=-79}, got Block{vinery:storage_pot}[facing=west,open=false]

### Steps to Reproduce

Place the storage pot item on any solid block.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
