### ISSUE TITLE
Crash With Cheeseracks

### ISSUE THREAD

**Issue by Fyoncle** [satisfyu/Let-s-Do-Hub#29]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.12

### Issue Description

Crashes when a cheese rack in meadow village right clicked

### Steps to Reproduce

1. Locate a meadow village
2. Enter a house with bookshelfs
3. Right click a cheese rack with bare hand.

### Logs

https://mclo.gs/STMpYai

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for your bug report. Just fixed this inDev. :) 

https://github.com/satisfyu/Meadow/commit/9057be249f5592294aa14464c6a55c282fd8b91e

**Comment by Fyoncle** [comment]
> Thank you for your bug report. Just fixed this inDev. :)
> 
> [satisfyu/Meadow@9057be2](https://github.com/satisfyu/Meadow/commit/9057be249f5592294aa14464c6a55c282fd8b91e)

Thank you so much for the fash answer :D
