### ISSUE TITLE
Wines created with create machines do not age.

### ISSUE THREAD

**Issue by luisbrandao** [satisfyu/Let-s-Do-Hub#291]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Wines mixed with create machines are allways made "in the current year", and the number auto-update every year.
Is this intentional?

### Steps to Reproduce

Use a mechanical mixer to make a bunch of any wine (like cherry or magnetic)
Note the wine and current year. (lets say, 20)
Wait a couple of days.
See that that the current year will get something else (lets say 30) and the wine age will have turn to 30 too

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Wines created with anything other than the fermentation barrel wont give the wine any nbt data.
