### ISSUE TITLE
[Brewery] all buckets in hand get deleted when taking water during minigame

### ISSUE THREAD

**Issue by YackMyGack** [satisfyu/Let-s-Do-Hub#292]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

Brewery - 1.1.9 - FORGE 1.20.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

During the minigame, all of the empty buckets in my hand got deleted when I took water from the kettle during the water boiling event in the minigame.

### Steps to Reproduce

have multiple empty buckets in your main hand, and when the brewing minigame gives the boiling event, use the bucket on the kettle. All of the buckets previously held get deleted, replacing them with a single water bucket in your hand.

### Logs

none

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Brewery/commit/bee6c97d956ed307cb8494e52c9fda63faae4b8c

@CebularzPawel fixed this Issue a few days ago. I'll upload the fixed version today / tomorrow. Thank you for your patience.
