### ISSUE TITLE
[Bakery] Stuffed Cornet and Jam Rolls Incompatability

### ISSUE THREAD

**Issue by Styxx0803** [satisfyu/Let-s-Do-Hub#293]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I'm trying to make a stuffed cornet to get the completionist banner, but whenever I try to make cornet rolls, they automatically finish as jam rolls. I try selecting the cornet rolls recipe while looking at the recipe book in the stove, but to no avail. I think it's because Let's Do: Farm and Charm has Apple Jam as a viable crafting ingredient and the recipes are exact, with the only difference being that stuffed cornet can only be made one way (with apple jam) and jam rolls can use a variety (anything using #bakery:jam)

### Steps to Reproduce

1. Place Apple Jam, Sweet Dough, and Sugar into a Let's Do: Farm and Charm Stove with fuel.
2. Select the "Stuffed Cornet" recipe in the stove view, in the recipe book
3. Wait for recipe to finish
4. Obtain Jam Rolls

### Logs

I'm not a server admin in the modpack we're using, I don't have access to logs.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Whoops - yep, they both share the same recipe! Thank you for pointing out. 

I will upload a fixed Version later today. :)
