### ISSUE TITLE
[Vinery] Mule won't disappear with Wandering Winemaker

### ISSUE THREAD

**Issue by ssfwuu0721** [satisfyu/Let-s-Do-Hub#296]
### Currently no capacity for new suggestions.

- [x] I understand that my suggestion might be deleted.

### Mod Name and Version

Vinery-1.20.1-1.4.28

### Suggestion Details

in vanilla Trader Llama will disappear with Wandering Trader, but trader Mule won't
And you can ride Mule when he is tied by winemaker, also not like llama

### Expected Benefits

I think it's an issue in fact. i always found several mules around my house, be abandoned by his owner :(

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Fixed indev. Thank you for your patience! :)

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29
