### ISSUE TITLE
[Meadow] limestone lacks forge tags used for mod compatibility.

### ISSUE THREAD

**Issue by Edulml** [satisfyu/Let-s-Do-Hub#298]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Not having the forge:stone tag on limestone leads to incompatibilities with certain mining tools, two examples I'm facing in my setup being Tetra's Cthonic Extractors shot out of a crossbow and Iron's Spells and Spellbooks not breaking limestone with the spectral hammer spell. 

Blooming Nature also has this issue with its stones.

### Steps to Reproduce

-

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Meadow/commit/7bbbbe2eb4f618ff3140a3ad8e10a0f8907122db

Fixed for the next version. Thank you for pointing out!
