### ISSUE TITLE
[Vinery] Let's Do Vinery causes issues with Croptopia

### ISSUE THREAD

**Issue by JustAshadowScrub** [satisfyu/Let-s-Do-Hub#299]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

It deletes all the recipes in croptopia that involve grapes, seems like a tag issue

### Steps to Reproduce

Croptopia + Vinery = Croptopia recipes break

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Leafsong88** [comment]
Hello I'm having the same issue 

Reported in Croptopia Github.

https://github.com/ExcessiveAmountsOfZombies/shoppy/issues/33

![image](https://github.com/user-attachments/assets/72857d02-3e6f-409c-a1f9-9e0b17616a00)

The mod breaks some recipes like the Croptopia Guide and the recipes that uses grapes

**Comment by satisfyu** [comment]
Fixed indev. Thank you for your patience!
