### ISSUE TITLE
Meadow failed to load correctly

### ISSUE THREAD

**Issue by Greg727** [satisfyu/Let-s-Do-Hub#30]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.13

### Issue Description

Every time I try to load my game, it says I failed to load it correctly.

### Steps to Reproduce

Install the mod, update forge to the latest version, run the game.

### Logs

[crash-2024-05-10_09.59.03-fml.txt](https://github.com/satisfyu/Let-s-Do-Hub/files/15275903/crash-2024-05-10_09.59.03-fml.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by serioos** [comment]
I have this problem too after the latest update.

[crash-2024-05-10_18.23.19-fml.txt](https://github.com/satisfyu/Let-s-Do-Hub/files/15276431/crash-2024-05-10_18.23.19-fml.txt)

[latest.log](https://github.com/satisfyu/Let-s-Do-Hub/files/15276433/latest.log)

**Comment by satisfyu** [comment]
Fixed in version 1.2.13.1: 
https://legacy.curseforge.com/minecraft/mc-mods/lets-do-meadow/files/5333404
https://modrinth.com/mod/lets-do-meadow/version/1.3.13.1
