### ISSUE TITLE
[Vinery] Server crash when Vinery Trader try to spawn in

### ISSUE THREAD

**Issue by Crowzya** [satisfyu/Let-s-Do-Hub#301]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0-beta

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I was playing on my solo modded world for a little bit, calmly building something, then my game froze and crashed. I saw the report mentioning the Vinery wandering merchant trying to appear.

Seems like someone else got the same issue before, but it ended up closing for lack of follow-up on the OP. 

I want to also mention that while Farm and Charm works well for 1.21.1, I have not seen anything related to Vinery into my world. However looking into creative mode, Vinery seems to be active, but nothing spawns into the world (no trees, no grape shrubs, now crashes upon spawning the WM).

### Steps to Reproduce

- Open Minecraft
- Load into world
- Play until Winemaker trader tries to pop in
- Crash

### Logs

https://pastebin.com/Ktj0Dcv9

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
