### ISSUE TITLE
Game Crashes because of "Vanilla Refresh"

### ISSUE THREAD

**Issue by AvaAsUsual** [satisfyu/Let-s-Do-Hub#302]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Whenever consuming some drinks, depending on if they give an effect or not "Vanilla Refresh" will cause them to crash

I already made a bug report to the Vanilla Refresh team and they responded with this:
![image](https://github.com/user-attachments/assets/98529aa9-7d2a-4f27-af25-4e0f06cc23a4)

Sorry for any trouble, I hope this gets fixed :( 

### Steps to Reproduce

How to recreate:
Make a new modpack and install "Architectury API", "Fabric API", "Vanilla Refresh", "[Let's Do] API", and "[Let's Do] Vinery"

Make any world

Give yourself "Creeper Crush"

Drink it and crash

### Logs

https://mclo.gs/f0lQWFW
[crash-2024-09-29_09.00.18-server.txt](https://github.com/user-attachments/files/17179515/crash-2024-09-29_09.00.18-server.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Let-s-Do-Hub/issues/280

Please check for similar issues next time, thank you.
