### ISSUE TITLE
Unkown version sides on modrinth

### ISSUE THREAD

**Issue by izmystic** [satisfyu/Let-s-Do-Hub#303]
### Minecraft Version

1.20.1

### Mod

Farm and Charm, WilderNature, and Furniture

### Mod Version

latest

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I am unable to add the following mods to a modpack due to the packwiz error `Failed to add project: version doesn't have a side that's supported. Server: unknown Client: unknown`
- [[Let's Do] Farm & Charm](https://modrinth.com/mod/lets-do-farm-charm)
- [[Let's Do] Bakery - Farm&Charm Compat](https://modrinth.com/mod/lets-do-bakery-farmcharm-compat)
- [[Let's Do] Brewery - Farm&Charm Compat](https://modrinth.com/mod/lets-do-brewery-farmcharm-compat)
- [[Let's Do] Candlelight - Farm&Charm compat](https://modrinth.com/mod/lets-do-candlelight-farmcharm-compat)
- [[Let's Do] WilderNature](https://modrinth.com/mod/lets-do-wildernature)
- [[Let's Do] Furniture](https://modrinth.com/mod/lets-do-furniture)

### Steps to Reproduce

`packwiz mr add [any project above]`

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thanks for the hint. It has been added! :)
