### ISSUE TITLE
Crash when drinking Miss Lilitus wine

### ISSUE THREAD

**Issue by Snoteleks** [satisfyu/Let-s-Do-Hub#304]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0-beta-release (fabric)

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Upon drinking the Miss Lilitus Wine, the game crashes, and the launcher appears displaying this exit code:

> The game crashed whilst saving entity nbt
> Error: java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@vinery:party_effect

I have tried drinking other wines and none of them have made the game crash except this one, so far. Fortunately, even if the game crashes, the save remains intact and I can still open the world and play it, until I drink the wine again.

### Steps to Reproduce

1. Open inventory in Creative mode
2. Select Miss Lilitus Wine
3. Right-click to drink the wine
4. Crash happens

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Snoteleks** [comment]
Update: it happens with more wines too. I just attempted the same with the Mellohi Wine and this is the crash log:

> The game crashed whilst saving entity nbt
> Error: java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@vinery:health_effect

The issue is not at all consistent. Some wines such as the Cherry Wine give the intended effect without crashing. Other wines such as the Magnetic Wine do not give any effects but also do not crash.

**Comment by satisfyu** [comment]
Hey 

this has already being reported here: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/280

Therefore i'll close this issue. Should be fixed soon (hopefully :))
