### ISSUE TITLE
Backpacks disappearing when put in its trinkets slot 1.20.1

### ISSUE THREAD

**Issue by AloysBizarreAdventure** [satisfyu/Let-s-Do-Hub#305]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When i put the backpack inside its trinkets slot, items in it or not doesn't matter and then close out of my inventory it erases itself

### Steps to Reproduce

1. take the small backpack or the travelers backpack (not sure if applies to other backpacks)
2. put them in its trinkets slot
3. close inventory
4. open it again and check the slot, its gone

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue.
