### ISSUE TITLE
Discs Playing Loudly

### ISSUE THREAD

**Issue by DannyDevito747** [satisfyu/Let-s-Do-Hub#306]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Discs from this mod play incredibly loudly from Sophisticated Backpacks mobs, with no way of turning these discs off. They dont function like normal discs, and play in stereo at full volume regardless of distance.
While the discs are quite nice, they play loudly enough to cause pain when played through these mobs. Some way to fix this to be able to enjoy the discs without random pain later, or a way to disable the discs themselves would be appreciated. 

### Steps to Reproduce

Load only Furniture and Sophisticated backpacks, wait.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for your patience. This will be fixed in 1.0.3 - i will upload it in a few minutes.
