### ISSUE TITLE
[Vinery] Flow mod Duplicated UI and Apple Press acts as two stations

### ISSUE THREAD

**Issue by MateusFolletto** [satisfyu/Let-s-Do-Hub#308]
### Minecraft Version

1.21.x

### Mod

Vinery

### Mod Version

1.5.0-beta-release

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1 - When opening the apple press or aging casket UI while having flow installed, the game will render a static UI instantaneously in the center of the screen, and then another one will scroll over it.

2 - The apple press acts as two different stations when interacting with the top and bottom halves of it. Both halves work separately, allowing for double mash production, but it's not intended and ugly. 

### Steps to Reproduce

1 - Install flow and simply interact with the caskets and presses.

2 - Simply right-click the top of the press, add apples, then right-click the bottom half of the press and notice there are no apples being processed.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
