### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'nethervinery'!

### ISSUE THREAD

**Issue by Rhazio** [satisfyu/Let-s-Do-Hub#313]
### Minecraft Version

1.20.1

### Mod

NetherVinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

FABRIC - 1.20.1 

I was trying to launch Fabric server and suddenly come across this issue when launching. I updated Nether Vinery and Vinery to the latest version, as well as Let's Do API as well.

I haven't launched my server since August and returned to it today. Unfortunately, this error is causing the server to not turn on 

This was working in August.

### Steps to Reproduce

Launching server

### Logs

https://pastebin.com/EaagZFSd

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
This is a duplicated Issue of: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/269

Therefore i'll close this one here.
