### ISSUE TITLE
[API] placing a flower into any of the modded flower pots while using the mod tinted crashes the game and softlocks player of the world

### ISSUE THREAD

**Issue by Kynz0** [satisfyu/Let-s-Do-Hub#315]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When i have all the let's do mods and tinted installed and try to place a flower into anything a flower can be placed into (the flower boxes, big flower pots or even the beer mug) it crashes the game and doesnt let me rejoin the world.
iam using all the newest versions of all the mods as of today.

I know this mod series is being discontinued but iam still making this issue in the hopes someone might pick up the work, cus i love this series with all my heart <3

### Steps to Reproduce

Install any/all of the let's do mods that have some kind of a flower block (vinery, meadow, brewery, bloomingnature)
Install the [Tinted mod](https://modrinth.com/mod/tinted) (iam using the 1.1 version)
go into any world and place a flower into any of the modded flower pots, boxes, beer mugs...

### Logs

crashlog: https://pastebin.com/YPRqb1ku

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed indev. I've added checks to prevent crashes when certain data is missing.

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29
