### ISSUE TITLE
Oven Interface not opening

### ISSUE THREAD

**Issue by Saiyasha** [satisfyu/Let-s-Do-Hub#32]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.1.9

### Issue Description

Rightclicking on the Brick Oven does not open the Interface. 

This only happens when Farmers delight is also an active mod. I wills till post this here, just to make sure you guys know, but I know that this then is a mod dependency thing...

### Steps to Reproduce

Place Brick Oven 
Right Click on it

### Logs

https://pastebin.com/DYb9BD1Y

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in 1.1.10.
