### ISSUE TITLE
[Beachparty] Can't open parasol

### ISSUE THREAD

**Issue by dodo698** [satisfyu/Let-s-Do-Hub#320]
### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Can't open parasol

### Steps to Reproduce

I place a parasol and I shift right click the top half and nothing happens.

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Beachparty is currently being completely revamped, and as a result, this feature has been slightly modified. Therefore, I will close this issue and kindly ask for your patience - the new version will be released soon. Thank you for your understanding. :)
