### ISSUE TITLE
Vinery causing server crashes

### ISSUE THREAD

**Issue by AbigailPwrRose** [satisfyu/Let-s-Do-Hub#321]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

So basically Im trying to run a server on Aternos with my friends, and we're trying to install vinery on it. However, it keeps crashing when Vinery is installed and giving a very long crash reason that I can't understand. It works on single player and none of the other mods are causing this issue, further more we've tried removing Vinery and the server works just fine even with Let's Do API still installed

### Steps to Reproduce

Have Aternos server
Install latest Fabric API
Install latest Architectury
Install latest Let's Do API
Install latest Let's Do Vinery
Start server

### Logs

https://pastebin.com/Wch68XGe

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue.
