### ISSUE TITLE
[WilderNature] Trinkets isnt marked as a dependency

### ISSUE THREAD

**Issue by nailuj9002** [satisfyu/Let-s-Do-Hub#322]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

WilderNature 1.0.2 (you didnt add wilder nature as an option for mod)

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Wilder nature requires Trinkets which fabric doesnt detect as a dependency so you dont get the fabric error of missing dependencies

### Steps to Reproduce

1. Install [Let's Do] Wilder Nature 2.Install dependencies except trinkets 3.Launch minecraft

### Logs

https://pastebin.com/tZw2bsLU

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Added it! :) Thank you.
