### ISSUE TITLE
[Let's Do: Farm and Charm Compat] Feast Buff Issues

### ISSUE THREAD

**Issue by Styxx0803** [satisfyu/Let-s-Do-Hub#328]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

2.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I was reading through the [github](https://github.com/satisfyu/FarmAndCharm/wiki/Effects#Feast) Farm and Charm wiki effects for Feast, and I got cooking. This takes place on a modded server and has not been tested in a single-player environment.

After eating Stuffed Rabbit or Stuffed Chicken, no indicator that a buff has been applied is present. If you're already damaged and low on hunger when it's consumed, the hunger bars tick down and regen health like normal based off of hunger levels. Hunger levels drop like normal and are not impacted by the consumption of these Feast items.

The feast buff is present after eating Baked Lamb Ham or Roasted Corn - the buff is applied. It appears to work at first, but if you take continuous damage for a few seconds while it's trying to work, your hunger bar drops almost instantly and is fixed at 1.5 hunger. You do not regen any health beyond the first few seconds. If you try to consume any other food to bring your hunger up, it does not stay. The hunger drops back down, nearly instantly, to 1.5 hunger.

### Steps to Reproduce

For Stuffed Rabbit/Chicken Issue
1. Have your hunger and health about half.
2. Place Stuffed Rabbit/Chicken on any surface.
3. Right click to "eat" the food
4. No buff is applied, hunger bar fills, health is regenerated based off of hunger levels.

For Baked Lamb Ham/Roasted Corn
1. Have your hunger and health about half
2. Be in a position to receive continuous damage (drowning, mobs, etc)
3. Eat Baked Lamb Ham or Roasted Corn
4. Feast buff is applied, begins to regenerate health
5. Hunger drops to 1.5 and health no longer regenerates.
6. After buff ends, eat until your hunger is restored
7. Hunger and health is permanently lowered by 1.5 until you rejoin the server.

### Logs

I am not a server admin and do not have access to the logs.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You're using an outdated version. This bug has already been reported and fixed.
