### ISSUE TITLE
[Camping] Sheep bag dissapears when opening through keybind

### ISSUE THREAD

**Issue by sola-22** [satisfyu/Let-s-Do-Hub#329]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.4

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When the sheep bag is equipped, opening it with the "open backpack" keybind removes the sheepbag and its contents from your inventory

### Steps to Reproduce

Equip sheepbag, press keybind to open the bag, press escape to close the bag

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
And i thought i had fixed that. It was at least not reproducible in a dev environment. :/ Sorry for the inconvenience.

I'll look into this again during the week

**Comment by satisfyu** [comment]
Phew. Thank god. :D
