### ISSUE TITLE
Hanging birch leaves are still flat even with the bushy leaves texturepack.

### ISSUE THREAD

**Issue by vinnyg0621** [satisfyu/Let-s-Do-Hub#330]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

hanging birch leaves aren't showing up as bushy in the built-in texture pack

![2024-10-22_21 23 00](https://github.com/user-attachments/assets/85bc8e00-e3ae-440d-8827-fd8c70f98740)

### Steps to Reproduce

1. enable "meadow/better_leaves" resource pack
2. look at pine leaves, they are bushy, but hanging birches aren't

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey hey :) 

Thats actually intended. In my opinion it doesnt look good when these leaves have the 'exented leaves' at the bottom + the bushy texture overlay.
