### ISSUE TITLE
Farm & Charm bug #1

### ISSUE THREAD

**Issue by RuinedEclipse87** [satisfyu/Let-s-Do-Hub#331]
### Minecraft Version

1.21

### Mod

Farm and Charm

### Mod Version

1.2.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

cannot open ui interface and place pot correctly for the cooking pot. crashes game everytime i try to use it or place it down on any block. gives code error:
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: blue/endless/jankson/JsonElement

### Steps to Reproduce

craft farm & charm pot
place down pot onto farmer's delight stove (crashed at this step first)
re-open minecraft
see that pot has been placed
try to click onto pot to use it to make food
game crashes again

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by RuinedEclipse87** [comment]
forgot to mention tho that im on neoforge

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
