### ISSUE TITLE
Let's do farm & charm bug #2

### ISSUE THREAD

**Issue by RuinedEclipse87** [satisfyu/Let-s-Do-Hub#332]
### Minecraft Version

1.21

### Mod

Farm and Charm

### Mod Version

1.2.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

mixing bowl doesn't work to mix ingredients properly to make cat food, when trying to make cat food and use the mixing bowl it will only make a yellow liquid in the bowl and not the proper food.

### Steps to Reproduce

craft mixing bowl
search on JEI for cat food recipe
place down bowl
add in ingredients listed on JEI to make cat food
click on bowl to use it to mix ingredients to make food
end result is just a bowl full of what looks to be liquid dough like when trying to make dough for pies
tried to cook some ingredients and it turned out to be the same result
no cat food comes out of bowl

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Let-s-Do-Hub/issues/284

Check for Similar Issues doesn't exist just for fun; it's actually there to minimize my workload.
