### ISSUE TITLE
Farm & Charm | Forge resource tags wipe

### ISSUE THREAD

**Issue by SADOMEN** [satisfyu/Let-s-Do-Hub#333]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

1.0.4

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Upon loading into single player, I found the resource tags in forge were empty. I found this through testing multiple mods and narrowed it down to Farm & Charm.

### Steps to Reproduce

Install Farm & Charm 1.0.4.jar through Curseforge and load into a single player world on 1.20.1

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Sorry - please help me briefly: What exactly is the 'resource' tag?

**Comment by satisfyu** [comment]
After some troubleshooting, the problem appears to be with the Let's Do Compat Mod.  

Please [report it here](https://github.com/Ninjdai1/letsdo-addon-compat/issues), thank you! 😊

**Comment by GlauberBlox** [comment]
lol bro just have removed the 1.21.1 versions of all his mods of madness

**Comment by GlauberBlox** [comment]
bro removed 1.21.1 versions because couldn't fix and "not an issue"😭😭💀💀
and removed my comment because got mad 😭😭💀💀💀
🗣️🗣️🗣️🗣️🗣️
