### ISSUE TITLE
Create support for Let's Do block entities

### ISSUE THREAD

**Issue by cshcrafter** [satisfyu/Let-s-Do-Hub#334]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

All of the Above

### Suggestion Details

Hello from a Create mod collaborator! It would seem that users are unable to add/remove items automatically from block entities from the Let's Do series via funnels, chutes, or otherwise. Hopefully this could be changed!

### Expected Benefits

It would be great to have this functionality for improved automation gameplay!

### Potential Drawbacks

The added development overhead involved with redoing things, but the benefits far outweigh that in my humble opinion.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Implemented for Vinery.

**Comment by satisfyu** [comment]
Implemented for Farm&Charm and its compat addons. Will close this therefore as completed.
