### ISSUE TITLE
[Camping]Don't know how to craft some of the backpacks

### ISSUE THREAD

**Issue by ToastyHawk** [satisfyu/Let-s-Do-Hub#335]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.4

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I have jei installed but it will only give me the recipes for the bundle, small backpack, standard backpack, and the sheepbag. Can't see recipes for any of the other ones. Are they craftable and my jei is bugged? Or are they only lootable? Thanks in advance.

### Steps to Reproduce

Have the mod and jei installed, Both up to date.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Some of them can be found as a Loot in structures, others have to be traded or are a reward for specific advancements.
