### ISSUE TITLE
Duplicated Items With The Graveyard Mod (Video)

### ISSUE THREAD

**Issue by CaoTrongThang** [satisfyu/Let-s-Do-Hub#337]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.2.15

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

My Friend is getting this issue with The Graveyard mod, you can see in the video.

### Steps to Reproduce

https://github.com/user-attachments/assets/351338f3-9372-464b-b0ec-0e6fe5684af6

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev, thank you.

**Comment by CaoTrongThang** [comment]
can i get the download link?
