### ISSUE TITLE
Make tents bigger or left 4 free blocks inside.

### ISSUE THREAD

**Issue by josemunoz18** [satisfyu/Let-s-Do-Hub#338]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

Let's do Camping

### Suggestion Details

The tent may only use for decorative, but if the space inside was been usable, you could uses as temporary house.

### Expected Benefits

It was useful if you could put a bed inside or a craft table, something like that. Also you may integrate some doors to the tent to protect you from the outside.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Hey!

Thank you for your suggestion. The tent is currently being reworked, which makes the enlargement unnecessary. It will include a crafting bench and a furnace.
