### ISSUE TITLE
Server fails to load using the latest Neoforge version for 1.21.1

### ISSUE THREAD

**Issue by darock830** [satisfyu/Let-s-Do-Hub#339]
### Minecraft Version

1.21.1

### Mod

Vinery

### Mod Version

1.5.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Cannot load the server with the Vinery mod.

### Steps to Reproduce

1. Install Vinery and its dependencies.
2. Crash

### Logs

https://pastebin.com/4pAU60Z5

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Check for similar issues please.
