### ISSUE TITLE
blooming nature red oat grass issues

### ISSUE THREAD

**Issue by kolosstm** [satisfyu/Let-s-Do-Hub#340]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

fabric 1.0.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

when red oat grass is bonemealed, vanilla tall grass grows instead of tall red oat grass, additionally, all red oat grass variants dont generate in savannas when nature's spirit is installed

### Steps to Reproduce

place red oat grass > bone meal it > cry

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thats simply because Natures Spirit and BloomingNature both overhaul the savanna biome. Either you disable it from BloomingNature or NaturesSpirit in the config, or unfortunately, you'll have to live with it. Sorry.

**Comment by kolosstm** [comment]
@satisfyu what about the bonemealing part? is that due to nature's spirit too?

**Comment by satisfyu** [comment]
The symbol is not inverted. Tall grass, flowers, etc., each use the top part of the block as the item.

**Comment by kolosstm** [comment]
got it, thank you for your replies
