### ISSUE TITLE
Found a random bug with yeast recipe

### ISSUE THREAD

**Issue by GlauberBlox** [satisfyu/Let-s-Do-Hub#345]
### Minecraft Version

1.21

### Mod

Farm and Charm

### Mod Version

1.20 Neoforge

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

farm and charm flour on yeast thing
![image](https://github.com/user-attachments/assets/8ac0a4c3-618a-4b74-b4cc-e96494e2b0ba)

### Steps to Reproduce

1 - try to craft

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Let-s-Do-Hub/issues/333

Duplicated Issue, going to close this one here. Thank you :)
