### ISSUE TITLE
Excavated Variants Support

### ISSUE THREAD

**Issue by UdderlyEvelyn** [satisfyu/Let-s-Do-Hub#346]
### Currently no capacity for new suggestions.

- [x] I understand that my suggestion might be deleted.

### Mod Name and Version

Let's Do Meadow

### Suggestion Details

Add support for Excavated Variants for Limestone. 
https://www.curseforge.com/minecraft/mc-mods/excavated-variants

### Expected Benefits

Since it's just one block it shouldn't be too hard to add. It makes it so that ores that spawn in limestone would show up with limestone texture around them and blend in nicely.

### Potential Drawbacks

Tiny amount of time to make a texture and maybe a text file?

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Thats currently not planned, sorry.
