### ISSUE TITLE
Stove texture and light

### ISSUE THREAD

**Issue by Elnhomantia** [satisfyu/Let-s-Do-Hub#347]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.3.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

It's a detail, but I think the whole texture of the stove emits light, making the texture lighter than their counter and sink counterpart. It's especially visible with shaders.

![image](https://github.com/user-attachments/assets/37b56c07-aeb3-4507-a544-1acf7632e66f)
![image](https://github.com/user-attachments/assets/79bf2f8a-1e51-4ebe-8f3b-a2949feb5417)

### Steps to Reproduce

Just place the blocks

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
This is due to Minecraft's light engine, and I don’t believe there's any way to work around it.

Sorry.
