### ISSUE TITLE
Meadow Outpost Generate Leveled

### ISSUE THREAD

**Issue by HellimsProjects** [satisfyu/Let-s-Do-Hub#348]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The outpost generated wrongly.

### Steps to Reproduce

Find an outpost in meadow biome
![2024-11-06_00 08 14](https://github.com/user-attachments/assets/81dedbdb-e87a-48bd-a3fc-609286816b3f)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Meadow doesnt add any outposts. Check your other mods please.

**Comment by satisfyu** [comment]
https://github.com/Ninjdai1/letsdo-addon-structures/issues
