### ISSUE TITLE
Suggestion for WilderNature (Raccoons)

### ISSUE THREAD

**Issue by fridaisy** [satisfyu/Let-s-Do-Hub#349]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

WilderNature 1.20.1

### Suggestion Details

taming raccoons by breeding them (like foxes) and they don't run away anymore!

compatibility with domestication innovation would also go so hard

### Expected Benefits

"tamed" raccooons, happy players who love to collect animals (me)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Raccoons are not pets, sorry! :P

I might consider the idea of taming them temporarily, during which they could give a gift.

Thanks for the suggestion, though!
