### ISSUE TITLE
"[Let's Do] Candlelight - Farm&Charm compat" on CurseForge should be called "[Let's Do] Candlelight - Farm&Charm Compat"

### ISSUE THREAD

**Issue by JohnnyDabb2** [satisfyu/Let-s-Do-Hub#352]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

You forgot to capitalize the "c" in "compat" in the name of the mod on CurseForge.  This isn't an issue with the mod itself but it really bugs me nonetheless.  Would it be okay if you fixed it?  Please and thank you!

### Steps to Reproduce

N/A

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Done.
