### ISSUE TITLE
Compatibility for [Let's Do] Furniture and various [Let's Do] modded wood types

### ISSUE THREAD

**Issue by Arrowpuppet** [satisfyu/Let-s-Do-Hub#353]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

N/A

### Suggestion Details

Add Furniture block variants for the wood types introduced by Vinery, Meadow, BloomingNature, BeachParty, etc.

### Expected Benefits

Better cohesion and immersion between [Let's Do] mods when installed together.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Thats already planned for early 2025 :)
