### ISSUE TITLE
ko_kr update

### ISSUE THREAD

**Issue by VoxelShape** [satisfyu/Let-s-Do-Hub#354]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

[Let's Do] Brewery

### Suggestion Details

I hope [Let's Do] Brewery mod will add support for the Korean language in the lang file
Here is translation.
[ko_kr.json](https://github.com/user-attachments/files/17730880/ko_kr.json)

### Expected Benefits

It would provide convenience for Korean-speaking users.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Added it, will be in the next release. Thank you!
