### ISSUE TITLE
[Vinery] Alternate Fruit Leaf Texture

### ISSUE THREAD

**Issue by dandy-is-lion** [satisfyu/Let-s-Do-Hub#355]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

Vinery 1.4.28

### Suggestion Details

I've been working on a resource pack for Vinery's bushy leaves that makes them more varied with budding leaves displaying their fruits below them (like Pam's Trees)

Test world setting:
![2024-11-13_08 33 40](https://github.com/user-attachments/assets/a2ca2d1b-5ee1-41ca-9953-6cb965b238e5)

Real world setting:
![2024-11-12_23 26 31](https://github.com/user-attachments/assets/99f3b5dc-c15a-448c-af4b-fae7918a411a)

### Expected Benefits

The bushy part of the leaves are more varied to avoid Z-fighting. The fruits are displayed below instead of on the side for less visual noise, to blend nicer with the environment, and to make it easier to differentiate the budding leaves. (Unrelated but I made the leaves opaque for the Cull Leaves mod)

### Potential Drawbacks

This is a suggested alternate texture to be added to the base mod. Though I'd completely understand if you'd rather keep this separate (and if you want to delete this suggestion). If the latter, I'd like your permission to release this texture pack instead (with full credits to you of course)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Feel free to release it as a TexturePack. :) You dont need to give me credits for this.

**Comment by dandy-is-lion** [comment]
Alright, thank you!
