### ISSUE TITLE
Grass can spread onto waterlogged dirt slabs

### ISSUE THREAD

**Issue by PollyThePancake** [satisfyu/Let-s-Do-Hub#356]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.5.0-beta-release

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Grass blocks can spread to waterlogged dirt slabs, unlike how underwater dirt cannot be spread to

![2024-11-14_21 46 35](https://github.com/user-attachments/assets/3a893a07-f097-4d12-abcd-a630eb3d55af)

### Steps to Reproduce

1. Place a grass block next to dirt slabs
2. Wait for the grass to spread onto the dirt slab

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

Sorry for the inconvenience. For now, I’ve removed the 1.21 versions due to the many small issues and will be revisiting everything over the coming weeks.

Thank you for your understanding. :)
