### ISSUE TITLE
Add dirt path slabs

### ISSUE THREAD

**Issue by PollyThePancake** [satisfyu/Let-s-Do-Hub#357]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

Vinery

### Suggestion Details

It would be really neat to have dirt path slabs that can be made by right clicking dirt slabs with a shovel

### Expected Benefits

I usually use a different block to ease in the full block gap between dirt path blocks of different heights, having a slab would be really useful to keep the aesthetic

### Potential Drawbacks

Possibly difficult to program considering dirt paths arent a full block

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Implemented. Will be included in the 1.4.29 update.

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29

**Comment by satisfyu** [comment]
Implemented in 1.4.29
