### ISSUE TITLE
Let's do Brewery 1.21.1 asking for Let's do API 1.3.0 (which is not existing) and refusing 1.3.0-beta

### ISSUE THREAD

**Issue by Goldocelot** [satisfyu/Let-s-Do-Hub#358]
### Minecraft Version

Neoforge 1.21.1-21.1.77

### Mod

Brewery

### Mod Version

2.1.0

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The mod is asking for a non-existing version of the letsdo-API.

### Steps to Reproduce

1) Download the latest version of let's do brewery
2) Download the latest version of let's do API (1.3.0-beta)
3) Getting a mod loading error where let's do berwery ask for let's do API 1.3.0 and not 1.3.0-beta

### Logs

https://pastebin.com/0YwzE1xD

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
The 1.21.1 ports were unfortunately not made by me and are still quite buggy. For the moment, I have removed them. Sorry for the inconvenience.
