### ISSUE TITLE
How do I get black and oolong tea in Herbal Brews?

### ISSUE THREAD

**Issue by Blayung** [satisfyu/Let-s-Do-Hub#359]
### Minecraft Version

1.20.1

### Mod

HerbalBrews

### Mod Version

1.0.8.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Don't know how to craft it.

### Steps to Reproduce

1. Start the game

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
This is not the place for questions regarding the mods: GitHub is only used for issues and suggestions. Questions can either be asked on Discord or may already be answered in the Wiki.

https://github.com/satisfyu/HerbalBrews/wiki/Drying#Drying-Blocks

https://discord.com/invite/Vqu6wYZwdZ
