### ISSUE TITLE
Request for 

### ISSUE THREAD

**Issue by Swifty744** [satisfyu/Let-s-Do-Hub#36]
### Mod Name and Version

Vinery 1.20.1 Forge

### Suggestion Details

Would love to see compat with this and Farmers delight since Farmers is used quite often nowadays. 

### Expected Benefits

Compat with all the let's do mods with farmers delights if it isn't already.

### Potential Drawbacks

Time

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
What kind of compatibility are you looking for? :) Ingredients can already be used across different mods. For the cooking pot and various recipes, there is the following addon:
https://www.curseforge.com/minecraft/mc-mods/lets-do-addon-compat

**Comment by Swifty744** [comment]
Ahh that's brilliant thank you. I believe I saw that mod quite a while ago and forgot about it but I always worry about adding mods that aren't made by the official author of the original
