### ISSUE TITLE
Bug with Knife

### ISSUE THREAD

**Issue by Val3for** [satisfyu/Let-s-Do-Hub#360]
### Minecraft Version

2.9.0

### Mod

Bakery

### Mod Version

1.1.15

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

When using knife to cut meat on the chopping board, it only works if the knife is at full durability. As soon as you use it once, it will no longer recognise it as the correct tool and will tell you to try using a different one.

### Steps to Reproduce

Add partial durability knives as an accepted tool to cut meat?

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey!

There is no special logic for the Breadknife and the ChoppingBoard - I assume you are referring to the ones from Farmer's Delight. They simply accept tools that use the `knives` tag.
