### ISSUE TITLE
Let's Do Bakery: Small Cooking Pot Crafting Not Working

### ISSUE THREAD

**Issue by Narwholphin** [satisfyu/Let-s-Do-Hub#361]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.0.4

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Unable to craft the item: small_cooking_pot

I've delved in to the mod jar file, found the recipe for it and made sure it matched what I was trying. Nothing shows up when entering the crafting recipe.

### Steps to Reproduce

Just try crafting. 4 iron ingot 2x2 followed by a single wood slab to the right

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Cannot be reproduced. The recipe is correct. Tested inDev, in a modpack with around 150 different mods, as well as in a minimal instance outside of the DevEnv.

Please check the logs.
<img width="1512" alt="2024-11-1717 42 13" src="https://github.com/user-attachments/assets/caf5bd21-89ea-4a7a-acd7-e9602a33eeda">

**Comment by satisfyu** [comment]
No further information received. Therefore, it will be closed. Thank you.
