### ISSUE TITLE
Mod Incompatibility: ItemPhysic does not allow coconuts to break

### ISSUE THREAD

**Issue by son0fether** [satisfyu/Let-s-Do-Hub#364]
### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

1.1.5

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The ItemPhysic mod includes an option, enabled by default, to prevent items from being destroyed by fire, lava, or cactus, except under certain circumstances.  https://modrinth.com/mod/itemphysic

While it's funny to have coconuts need to be thrown to be broken, this conflict prevents that, and similar physics mods likely would as well.

I tried placing the coconut on the ground and breaking it with an axe, but that actually didn't drop anything.  I can see that that was fixed in an upcoming version, but I don't think it will result in coconut halves: https://github.com/satisfyu/Let-s-Do-Hub/issues/105

The only workaround I have right now is to add a datapack that will provide a regular crafting recipe.  I'm also going to add a Create sawing recipe, which I would recommend as a sensible option.

### Steps to Reproduce

Install ItemPhysic and Let's Do Beachparty.  Throw a coconut.  Be sad.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev.
