### ISSUE TITLE
Fish Tank Crash World

### ISSUE THREAD

**Issue by iamazzy** [satisfyu/Let-s-Do-Hub#365]
### Minecraft Version

1.20.1

### Mod

Furniture

### Mod Version

1.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When I place down either iron fish tank or copper fish tank, the game crashes and I am unable to join world again.

### Steps to Reproduce

Place down either iron fish tank or copper fish tank

### Logs

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-23 09:53:51
Description: Ticking entity

java.lang.ClassCastException: class com.berksire.furniture.client.entity.FakeFishTankEntity cannot be cast to class net.minecraft.class_1309 (com.berksire.furniture.client.entity.FakeFishTankEntity and net.minecraft.class_1309 are in unnamed module of loader 'knot' @4f7d0008)
	at knot//net.minecraft.class_1297.handler$hgf000$mythic_charms$drownedFreedomEffectTouch(class_1297.java:26833)
	at knot//net.minecraft.class_1297.method_5799(class_1297.java:1318)
	at knot//net.minecraft.class_1297.method_5876(class_1297.java:1362)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:503)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:474)
	at knot//com.berksire.furniture.client.entity.FakeFishTankEntity.method_5773(FakeFishTankEntity.java:59)
	at knot//net.minecraft.class_638.method_18646(class_638.java:272)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1901)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_1297.handler$hgf000$mythic_charms$drownedFreedomEffectTouch(class_1297.java:26833)
	at knot//net.minecraft.class_1297.method_5799(class_1297.java:1318)
	at knot//net.minecraft.class_1297.method_5876(class_1297.java:1362)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:503)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:474)
	at knot//com.berksire.furniture.client.entity.FakeFishTankEntity.method_5773(FakeFishTankEntity.java:59)
	at knot//net.minecraft.class_638.method_18646(class_638.java:272)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)

-- Entity being ticked --
Details:
	Entity Type: furniture:fake_fish_tank (com.berksire.furniture.client.entity.FakeFishTankEntity)
	Entity ID: 1618
	Entity Name: entity.furniture.fake_fish_tank
	Entity's Exact location: 119.50, 73.00, 21.50
	Entity's Block location: World: (119,73,21), Section: (at 7,9,5 in 7,4,1; chunk contains blocks 112,-64,16 to 127,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_638.method_32124(class_638.java:255)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_638.method_18116(class_638.java:251)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1901)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['{MINECRAFT_USERNAME}'/185, l='ClientLevel', x=121.89, y=73.00, z=21.37]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5501 game time, 29501 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:821)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, seasons:seasonal_lush_caves, Moonlight Mods Dynamic Assets, continuity:default, continuity:glass_pane_culling_fix, file/FreshAnimations_v1.9.2.zip, file/animated-items-1_20-1 - 1_4.zip, file/crops-3d.zip, file/Stargazer (1.2.1) [Resources].zip, diagonalblocks:default_block_models, replaymod_lang, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.13, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 2858430488 bytes (2726 MiB) / 12918456320 bytes (12320 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900F
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2882
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6603
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 69350.05
	Virtual memory used (MB): 59715.55
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 198.55
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementframes: advancementframes 1.20-2.2.7
		advancementscreenshot: Advancement Screenshot 4.9
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		amendments: Amendments 1.20-1.2.12
		anim_origins_nx95: Animal Origins 2.0.0
		anthropophagy: Anthropophagy 1.20-4
			midnightlib: MidnightLib 1.4.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		archers: Archers (RPG Series) 1.2.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		architectury: Architectury 9.2.14
		armor_visibility: Armor Visibility 9.0.1+1.20.1
		ash_api: Ash API 3.0.2+1.20.1
		athena: Athena 3.1.2
		azurelib: AzureLib 2.0.39
		azurelibarmor: AzureLib Armor 2.0.12
		bakery: [Let's Do] Bakery 2.0.3
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beachparty: [Let's Do] Beachparty 1.1.5
		betteradvancements: Better Advancements 0.4.2.10
		bettercombat: Better Combat 1.8.6+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterend: Better End 4.0.11
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bewitchment: Bewitchment 1.20-10
			impersonate: Impersonate 2.10.3
				fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			playerabilitylib: Pal 1.8.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
		bewitchmentz: LevelZ Bewitchment Compatibility 1
		biomesoplenty: BiomesOPlenty 19.0.0.91
		bloomingnature: [Let's Do] BloomingNature 1.0.9
		bookshelf: Bookshelf 20.2.13
		brewery: [Let's Do] Brewery 2.0.3
		camping: [Let's Do] Camping 1.0.4
		candlelight: [Let's Do] Candlelight 2.0.2
		cat_jam: cat_jam 1.3.1
		charmonium: Charmonium 6.0.7
			charmony: Charmony 6.12.0
			charmony_api: Charmony API 6.7.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chestedcompanions: Chested Companions 1.3.1
		chipped: Chipped 3.0.7
		cicada: CICADA 0.9.1+1.20.1
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		clutter: Clutter 1.20-0.6.0
		collective: Collective 7.87
		commonnetworking: Common Network 1.0.5-1.20.1
		continuity: Continuity 3.0.0-beta.5+1.20.1
		couplings: Couplings 1.9.5+1.20
		cpm: Customizable Player Models 0.6.19a
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_tags: Porting Lib Tags 3.0
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
		ctov: ChoiceTheorem's Overhauled Village 3.4.10
		deeperdarker: Deeper and Darker 1.3.2.1
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		diagonalfences: Diagonal Fences 8.1.5
			diagonalblocks: Diagonal Blocks 8.0.6
		diagonalwalls: Diagonal Walls 8.0.4
		diagonalwindows: Diagonal Windows 8.1.5
		dimdoors: DimensionalDoors 5.4.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.0
			cardinal-components-item: Cardinal Components API (items) 5.2.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			mm: Manningham Mills 2.3
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		doapi: [Let's Do] API 1.2.15
		doggytalents: Doggy Talents Next 1.18.32
		dramaticdoors: Dramatic Doors (QuiFabrge) 1.20.1-3.2.8
		easy_npc: Easy NPC 5.7.6
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		effectdescriptions: Effect Descriptions 8.0.2
		effective: Effective 2.3.2-1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
			lodestone: Lodestone 1.20.1-1.6.2.3f-fabric
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
				porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			satin: Satin 1.14.0
		elementa: Elementa 670
		enchdesc: EnchantmentDescriptions 17.1.19
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 1.3.5.3
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		extraalchemy: Extra Alchemy 1.10.0
		extraorigins: Extra Origins 1.20-8
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallingtree: FallingTree 4.3.4
		farm_and_charm: [Let's Do] Farm & Charm 1.0.4
			blue_endless_jankson: jankson 1.2.3
		fin_better_end_z: Better EndZ 1.2
		fin_better_netherz: Better NetherZ 1.0
		fin_deep_and_darkz: DeeperZ and DarkerZ 1.0
		forgeconfigapiport: Forge Config API Port 8.0.1
		friendsandfoes: Friends & Foes 3.0.6
		furnish: Furnish 26
		furniture: [Let's Do] Furniture 1.0.3
		galosphere: Galosphere 1.20.1-1.4.1
		gazebo: Gazebos 1.1.1+1.20.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		glitchcore: GlitchCore 0.0.1.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
			net_jodah_typetools: typetools 0.6.3
		herbalbrews: [Let's Do] HerbalBrews 1.0.8.1
		hybrid-aquatic: Hybrid Aquatic 1.3.4
		icarus: Icarus 2.10.0
		immersive_aircraft: Immersive Aircraft 1.1.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		immersive_melodies: Immersive Melodies 0.3.0+1.20.1
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		indium: Indium 1.0.34+mc1.20.1
		inventory_sort: Chai's Inventory Sorter 1.2.4+1.20
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 11.12.0+fabric
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.20.0.105
		jewelry: Jewelry (RPG Series) 1.3.7+1.20.1
		levelz: LevelZ 1.4.13
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.3.3
		luphieclutteredmod: Cluttered 2.1.0+1.20.1
		mca: Minecraft Comes Alive 7.5.21+1.20.1
		mcwbridges: Macaw's Bridges 3.0.0
		mcwdoors: Macaw's Doors 1.1.1
		mcwfences: Macaw's Fences and Walls 1.1.2
		mcwfurnitures: Macaw's Furniture 3.3.0
		mcwholidays: Macaw's Holidays 1.1.0
		mcwlights: Macaw's Lights and Lamps 1.1.1
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.5
		mcwroofs: Macaw's Roofs 2.3.1
		mcwstairs: Macaw's Stairs and Balconies 1.0.0
		mcwtrpdoors: Macaw's Trapdoors 1.1.3
		mcwwindows: Macaw's Windows 2.3.0
		meadow: [Let's Do] Meadow 1.3.19
			mixinsquared: MixinSquared 0.1.2-beta.5
		medievalorigins: Medieval Origins Revival 6.4.6+1.20.1-fabric
			apugli: Apugli 2.10.2+1.20.1-fabric
			autotag: AutoTag 2.0.2+1.20
			projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		mes: Moog's End Structures 1.3.1-1.20-fabric
		minecraft: Minecraft 1.20.1
		mns: Moog's Nether Structures 1.0.1-1.20-fabric
		moblassos: Mob Lassos 8.0.1
			extensibleenums: Extensible Enums 7.0.1
		mobs_of_mythology: Mobs of Mythology 2.0.3
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.13.28
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_stargazer_origin: Origins: Stargazer 2.3.2
		mr_tidal_towns: Tidal Towns 1.3.3
		mr_vanilla_refresh: Vanilla Refresh 1.4.19h
		mss: Moog's Soaring Structures 1.1.2-1.20-fabric
		mutantmonsters: Mutant Monsters 8.0.7
		mvs: Moog's Voyager Structures 4.1.2-1.20-fabric
		mythic_charms: Mythic Charms 1.2.2
		mythicmetals: Mythic Metals 0.19.9+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			common-protection-api: Common Protection API 1.0.0
		mythicmounts: Mythic Mounts 1.20.1-7.2
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nethervinery: [Let's Do] NetherVinery 1.2.14
		notenoughanimations: NotEnoughAnimations 1.8.1
		org_jetbrains_annotations: annotations 23.0.0
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				calio: Calio 1.11.0
		originsumbrellas: Origins: Umbrellas 1.5.6
		owo: oωo 0.11.2+1.20
		paladins: Paladins & Priests (RPG Series) 1.3.1+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		puzzleslib: Puzzles Lib 8.1.25
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		ranged_weapon_api: RangedWeaponAPI 1.1.4+1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replaymod: Replay Mod 1.20.1-2.6.20
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rogues: Rogues & Warriors (RPG Series) 1.1.0+1.20.1
		runes: Runes 0.9.13+1.20.1
		seasons: Fabric Seasons 2.4.2-BETA+1.20
		seasonsextras: Fabric Seasons: Extras 1.3.2-BETA+1.20
		shield_api: Shield API 1.0.1+1.20.1
		simplyswords: Simply Swords 1.56.0-1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		skinlayers3d: 3d-Skin-Layers 1.7.2
		smallships: Small Ships 2.0.0-b1.4
		smartbrainlib: SmartBrainLib 1.15
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spell_engine: Spell Engine 0.15.11+1.20.1
		spell_power: Spell Power Attribute 0.12.0+1.20.1
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supplementaries: Supplementaries 1.20-3.1.8
		sushi_bar: Sushi Bar 0.2.2+1.20
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		terrablender: TerraBlender 3.0.1.7
		trinkets: Trinkets 3.7.2
		universalcraft: UniversalCraft 365
		vanillatweaks: VanillaTweaks 1.5.71
		vigilance: Vigilance 306
		vinery: [Let's Do] Vinery 1.4.28
		voicechat: Simple Voice Chat 1.20.1-2.5.26
		waystones: Waystones 14.1.6
		wildernature: [Let's Do] WilderNature 1.0.4
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		yungsapi: YUNG's API 1.20-Fabric-4.0.6
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungscavebiomes: YUNG's Cave Biomes 1.20.1-Fabric-2.0.0
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.03, NVIDIA Corporation
	Window size: 2560x1369
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, seasons:seasonal_lush_caves, Moonlight Mods Dynamic Assets, continuity:default, continuity:glass_pane_culling_fix, file/FreshAnimations_v1.9.2.zip, file/animated-items-1_20-1 - 1_4.zip, file/crops-3d.zip, file/Stargazer (1.2.1) [Resources].zip (incompatible)
	Current Language: en_us
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900F
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/185, l='ServerLevel[New World]', x=121.89, y=73.00, z=21.37]]
	Data Packs: vanilla, fabric, lithostitched:breaks_seed_parity, dimdoors:classic (incompatible), dimdoors:default (incompatible), Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. Thank you for your patience.

**Comment by satisfyu** [comment]
Fixed in 1.0.4
