### ISSUE TITLE
JEED descriptions for Vinery, Brewery, and Nether Vinery

### ISSUE THREAD

**Issue by Puggicorn** [satisfyu/Let-s-Do-Hub#366]
### Currently no capacity for new suggestions.

- [X] I understand that my suggestion might be deleted.

### Mod Name and Version

Vinery, Brewery, and Nether Vinery (All Latest 1.20.1)

### Suggestion Details

Simply adding JEED effect descriptions so people understand what the drinks do :)

### Expected Benefits

Better comprehension and user accessibility 

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Implemented for Vinery.

**Comment by satisfyu** [comment]
Implemented for NetherVinery and Brewery. Thank you for your suggestion! :)
