### ISSUE TITLE
Wooden bucket is able to pickup everything bucketable except lava

### ISSUE THREAD

**Issue by Lucky-56** [satisfyu/Let-s-Do-Hub#37]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.13.1

### Issue Description

any modded fluid and powdered snow is able to be picked up by the wooden bucket, which in turn gives a filled regular bucket

### Steps to Reproduce

1. get wooden bucket
2. place powdered snow
3. right click powdered snow with wooden bucket
4. get powdered snow bucket

### Logs

https://pastebin.com/weWDC8mX

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. 

https://github.com/satisfyu/Meadow/commit/1fb371e1aa71501e9b7f0f1a0bfd68a18f7d20f5

**Comment by Lucky-56** [comment]
still able to pickup modded fluids with wooden buckets (meadow 1.3.14)
![2024-05-24_10 54 38](https://github.com/satisfyu/Let-s-Do-Hub/assets/55949451/65132a42-162b-47d0-9b34-aa5411ad2bdd)
![2024-05-24_10 54 39](https://github.com/satisfyu/Let-s-Do-Hub/assets/55949451/544d0a7c-705e-4f86-b8ab-9e8636afbcab)

**Comment by Lucky-56** [comment]
@satisfyu please reopen, as this is still an issue
