### ISSUE TITLE
Mod Crashes Essential Servers

### ISSUE THREAD

**Issue by Uno1487** [satisfyu/Let-s-Do-Hub#370]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

1.0.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

when hosting server, if one person equips backpack server will crash

### Steps to Reproduce

equip backpack

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I need a crashlog. No wizards here.

**Comment by satisfyu** [comment]
This issue is being closed due to missing and unsubmitted information, particularly because no crash log was provided.

Feel free to reach out once you can provide a crash log, and I will reopen the issue.

**Comment by Uno1487** [comment]
Here's the log file (backpack also duplicated the chestplate i was wearing and remains after sever restart. would perpetually saves, and server crashes only when putting backpack on back
[log (2).txt](https://github.com/user-attachments/files/18048710/log.2.txt)
