### ISSUE TITLE
Grille burns people

### ISSUE THREAD

**Issue by whydm2003724** [satisfyu/Let-s-Do-Hub#371]
### Minecraft Version

1.20.1

### Mod

Camping

### Mod Version

 letsdo-camping-fabric-1.0.4

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Getting close to the grill can cause burns, but standing on it won't. I hope you can fix it.
Thank you for these works, they are all amazing and have brought me a lot of joy:)

### Steps to Reproduce

1. Put down the grill in the module
2. Get close to it (injured), then jump on it (nothing happens)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev. Thank you for your bug report! :)

**Comment by whydm2003724** [comment]
> Fixed inDev. Thank you for your bug report! :)

Thank you too, my friend :)
