### ISSUE TITLE
Vinemaker spawning despite config set to 0

### ISSUE THREAD

**Issue by zeroneon** [satisfyu/Let-s-Do-Hub#376]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Vinemaker is still spawning despite setting the chance to 0

### Steps to Reproduce

set config to 0, watch him spawn

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in 1.4.29
