### ISSUE TITLE
Meadow: Missing Container Labels

### ISSUE THREAD

**Issue by avilonlegends** [satisfyu/Let-s-Do-Hub#378]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Hi there! Your mods are amazing!

I just happened to notice that for Meadow, it appears that 3 out of 4 container interfaces are missing a header label; the Fondue, the Cheese Press/Cheese Form, and the Cooking Cauldron. The Woodcutter actually has a header label.

I've attached pics to show where I assume the labels should be, as well a picture of the woodcutter interface which does have a label.

![woodcutter](https://github.com/user-attachments/assets/c4efce14-8180-41a6-9fab-a6f5fa88764a)
![cookingcauldron](https://github.com/user-attachments/assets/37fa4dda-311e-4578-a13b-1385c25b9112)
![cheeseform](https://github.com/user-attachments/assets/85c9e220-df2d-477d-9fa0-0e51de4d2695)
![fondue](https://github.com/user-attachments/assets/cbb6f0e5-5f1f-4841-81ab-3096d8ec92bd)

Could you perhaps look into this, please?
In any case, thank you!

### Steps to Reproduce

1. Open Minecraft with Meadow (and dependables) installed
2. Open the GUI/Interface of either the Cooking Cauldron, the Cheese Form/Cheese Press, or the Fondue.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in the next release, thank you! :)
