### ISSUE TITLE
[Vinery] Fermentation barrel doesn't work at all

### ISSUE THREAD

**Issue by eilamg** [satisfyu/Let-s-Do-Hub#379]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.29

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Using the latest version of Vinery (1.4.29) for Forge (47.3.12), the fermentation barrel doesn't actually do anything.

* Recipes without fluid input simply don't work. (e.g. apple mash + wine bottle => apple juice), Progress bar not moving, "Crafting Time" stuck on "5:00 Seconds", nothing happens.
* Impossible to try recipes with fluid input, as the fluid input functionality seems broken. An empty barrel will take a single bottle (e.g. white grapeJuice) from the input slot and empty the bottle, but the tooltip still says "The fermentation barrel is empty", and no further liquid can be added.

Tested on a minimal instance including only JEI, Jade, Vinery, and Architectury.

### Steps to Reproduce

Place apple mash and wine bottle in a fermentation barrel.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I forgot to remove the fermenting recipe for Apple Juice. Apple Juice is now crafted exclusively using the Apple Press.

The Fluid Input functionality has been fixed.

**Comment by satisfyu** [comment]
Fixed in 1.4.30.
