### ISSUE TITLE
Aging Barrel mod conflict

### ISSUE THREAD

**Issue by Xephorian** [satisfyu/Let-s-Do-Hub#38]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

forge-1.4.14

### Issue Description

So i noticed that with handcrafted installed i could not craft the storage pot, as it defaulted to the wooden cup. I installed polymorph mod, which allows swapping recipes that are the same among different mods. upon installing the aging barrel stopped functioning and i was not able to open it at all.

### Steps to Reproduce

1. run a profile with handcrafted and vinery installed
2. craft aging barrel
3. open aging barrel
4. close minecraft
5. add polymorph to profile
6. run profile with polymorph added
7. attempt to open aging barrel
8. UI does not open
9. close minecraft
10. remove polymorph
11. aging barrel opens fine

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Have you ensured that all components are updated to their latest versions?

I have attempted to replicate the issue multiple times without success. The Aging Barrel functions correctly and opens as expected - with and without Polymorph / Handcrafted installed.

**Comment by satisfyu** [comment]
@Xephorian 
Can you please test this again with the latest version? I can't reproduce it.
