### ISSUE TITLE
[Let's Do] NetherVinery: Error loading mods during loading.

### ISSUE THREAD

**Issue by nullasciz** [satisfyu/Let-s-Do-Hub#380]
### Minecraft Version

1.20.1

### Mod

NetherVinery

### Mod Version

1.2.14

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When loading mod screen on Forge launcher, says "Error loading mods" with error "Caused by 0: java.lang.NoClassDefFoundError: net/satisfy/vinery/registry/GrapeTypeRegistry".

Unable to load instance to play screen.

Latest MultiMC Launcher, 1.20.1 instance with latest Forge version for the instance version. Latest versions for dependencies installed.

### Steps to Reproduce

>Open MultiMC
>Create 1.29.1 instance
>Install Forge 47.3.0
>Install [Let's Do] Vinery
>Install [Let's Do] NetherVinery
>Install latest dependencies
>Launch instance
>Instance error during "Mod Gather: dispatching CONSTRUCT"
>Error screen in instance
>Close instance

### Logs

https://pastebin.com/NQPSrGr3

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
As stated in the latest log, the version section and in the discord: it's currently not compatible due to intern refactors.
