### ISSUE TITLE
Problem with harvesting berry-like crops

### ISSUE THREAD

**Issue by Patatone51** [satisfyu/Let-s-Do-Hub#381]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.28

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I'm playing on a heavily modded modpack on curseforge, the problem is that whenever i right click on fully grown white and red taiga berries, the plant gets "resetted" and it only gives me seeds. I don't have right click harvest mod so I don't know. I already played this mod previously on another modpack exactly the same 1.20.1 version and i didn't have the issue.

### Steps to Reproduce

Right click on a berry

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I just tested it in my own modpack (about 150 mods) and couldn't reproduce it. Further Informations needed.
