### ISSUE TITLE
Hibiscus Bone Meal Crash

### ISSUE THREAD

**Issue by Cowsticker** [satisfyu/Let-s-Do-Hub#384]
### Minecraft Version

1.20.1

### Mod

HerbalBrews

### Mod Version

1.0.8.1 

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Bone mealing hibiscus crashes the server. Does not occur in single player and without any dependencies.

### Steps to Reproduce

Bone meal hibiscus flower block and it causes a ticking error.

### Logs

[crash-2024-12-05_23.12.00-server.txt](https://github.com/user-attachments/files/18033527/crash-2024-12-05_23.12.00-server.txt)
[crash-2024-12-05_23.13.25-server.txt](https://github.com/user-attachments/files/18033528/crash-2024-12-05_23.13.25-server.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Cowsticker** [comment]
Only occurs in multiplayer, singleplayer there is no issue with bonemealing hibiscus

**Comment by satisfyu** [comment]
Thats related to vinery, not herbalbrews. :) 

Same issue as here: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/382

Please continue there.
