### ISSUE TITLE
Vinery mod wine broken in multiple ways

### ISSUE THREAD

**Issue by Joe-Moe** [satisfyu/Let-s-Do-Hub#388]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.32

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Winemaking now has a bunch of issues that I have found through minimal testing:
- When aging, even if the tooltip says that the wine lasts for X minutes and has Y power, you only get the base duration and power. So aging does nothing.

- The recipe Book is missing from the fermentation barrel GUI, so there is no way of knowing recipes with the mod only.
- In JEI, there is no indication of what grape juice is needed, only color (white, red, apple). It's a guessing game on whether you need to use jungle grapes, taiga ones, normal ones, etc. _(On further examination, there IS actually somewhere that specifies the grape type, but you have to hover over a specific pixel in the recipe GUI, not anywhere on the juice bar.)_

- For some reason, when on the non-minimal instance I was first testing on, a single juice bottle fills the juice meter fully and, after the first wine bottle is produced, it cannot refill because the meter hasn't gone back down to 0. 

- Stal wine has no effect name (effect.vinery.health_effect).

- Hoppers extract inputs of the barrel, not outputs.

- Lamrock Reserve (not sure if that was exactly the name) doesn't exist anymore, and some other wines that I don't remember may also have disappeared.

- (It's not really a bug, but it feels wrong for instant health to now require a rabbit's foot. That should go for a luck-related effect.)

### Steps to Reproduce

The description should be detailed enough not to need reproduction steps.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
1. was clearly an issue that i just fixed, thanks! :)

2. the recipe book was part of the doapi, which was removed with version 1.4.29. unfortunately, it was not really well-optimized in terms of performance and caused several issues, so we decided not to use it anymore. rei/jei are recommended.

3. i refined it a bit. it should now display everything as it should! :)

4. it might be that you still have an old config file. until version 1.4.31, `maxfluidlevel` and `maxfluidperjuice` were not separated. please check if both are present. if not, it should be enough if you delete the config file.  
`maxfluidlevel` determines the juice capacity of the fermentationbarrel.  
`maxfluidperjuice` determines how much of the capacity is filled.

5. was added, including jeed support.

6. was also added.  
you can now fill wine bottles and juice from above.  
you can now fill ingredients and wine bottles from the side.  
you can now extract output from the side and bottom.

7. they, along with their effects, were completely removed. these were items for former patreons who requested that these items no longer remain in the game.

**Comment by satisfyu** [comment]
Fixed in 1.4.33.
