### ISSUE TITLE
some items missing and can't place the wine on wine bottle storage

### ISSUE THREAD

**Issue by Josee-commits** [satisfyu/Let-s-Do-Hub#389]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.32

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I can't place the wine bottles on wine bottle storage & wine box

### Steps to Reproduce

meow

### Logs

<html>
<body>

[08Dec2024 20:17:27.948] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
--
49 | vinery:calendar: 1217
50 | vinery:count_roleester_shiraz: 1257
51 | vinery:knulp_wine: 1204
52 | vinery:lamroc_wine: 1256
53 |  
54 | [08Dec2024 20:17:27.950] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:item
55 | vinery:calendar: 1521
56 | vinery:count_roleester_shiraz: 1591
57 | vinery:knulp_wine: 1587
58 | vinery:lamroc_wine: 1592
59 |  
60 | [08Dec2024 20:17:27.950] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:mob_effect
61 | vinery:shiraaz_effect: 44
62 | vinery:staggering: 52
63 | vinery:trading: 40
64 | vinery:trippy: 39

</body>
</html>[08Dec2024 20:17:27.948] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:block
	vinery:calendar: 1217
	vinery:count_roleester_shiraz: 1257
	vinery:knulp_wine: 1204
	vinery:lamroc_wine: 1256

[08Dec2024 20:17:27.9[50](https://aternos.org/log/#L50)] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:item
	vinery:calendar: 1[52](https://aternos.org/log/#L52)1
	vinery:count_roleester_shiraz: 1591
	vinery:knulp_wine: 1587
	vinery:lamroc_wine: 1592

[08Dec2024 20:17:27.950] [main/ERROR] [net.minecraftforge.registries.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:mob_effect
	vinery:shiraaz_effect: 44
	vinery:staggering: 52
	vinery:trading: 40
	vinery:trippy: 39

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
These are just items and their effects that were removed, mostly Patreon-exclusive items. You can ignore this. 

You can only place wine bottles with the `'small_wine_bottle'` tag inside the Wine Box. Ensure you're clicking on the straw section and that the box is open.
