### ISSUE TITLE
Turkey eggs?

### ISSUE THREAD

**Issue by Kutomi1** [satisfyu/Let-s-Do-Hub#39]
### Mod Name and Version

BloomingNature 1.0.7

### Suggestion Details

Turkeys drop vanilla eggs, which hatch into chickens, making turkey farms a bit of a pain since the only way to get more turkeys is breeding with seeds or bringing new ones. This would be fixed if they dropped their own kind of egg that hatches into turkeys.

### Expected Benefits

Keeping turkeys would actually function the same as keeping chickens, as intended (I assume), instead of forcing you to also create a chicken farm if you wanna use their eggs. lol

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
They are currently being reworked! :)

**Comment by Kutomi1** [comment]
yippee!

**Comment by satisfyu** [comment]
Will be fixed in the next major BN update. :)
