### ISSUE TITLE
Candlelight Missing Tags - Forge - Lasagne

### ISSUE THREAD

**Issue by Zykana** [satisfyu/Let-s-Do-Hub#391]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

2.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Trying to make lasagne, the recipe says empty tag for pasta and cheese.

### Steps to Reproduce

Look up recipe for lasagne.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Any chance you're using the lets do addon compat mod?

**Comment by Zykana** [comment]
Yes

**Comment by satisfyu** [comment]
Remove it. :) It currently breaks Farm&Charm Tags.
