### ISSUE TITLE
Uncraftable apple juice

### ISSUE THREAD

**Issue by FO13E** [satisfyu/Let-s-Do-Hub#392]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.32

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Apple mash cannot be placed in a fermentation barrel.

### Steps to Reproduce

1. Take apple mash;
2. Put it in a fermentation barrel.
![Снимок экрана 2024-12-09 213351](https://github.com/user-attachments/assets/41eb08f0-ea6b-4da3-a092-5198376b9593)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by H0bbitBaron** [comment]
Hello, @satisfyu! Can you help to understand how to make "Apple Juice"? "Apple Press" doesn't work with/without empty bottle:
<img width="300" alt="Screenshot 2025-01-01 at 14 55 55" src="https://github.com/user-attachments/assets/6912fa4d-dbda-458a-85a5-8da669d2bbf6" />
And JEI integration looks broken https://github.com/satisfyu/Let-s-Do-Hub/issues/408.

Tested on minimal instance:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/13d64c52-dbad-42e0-a348-fc96c2135f5c" />
