### ISSUE TITLE
Apple Wood: Visual Bug

### ISSUE THREAD

**Issue by mewnn** [satisfyu/Let-s-Do-Hub#395]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Visual bug with Apple Wood addon for Vinery.
Apple Lattice makes the adjacent block transparent. Other wood types are fine.
![image](https://github.com/user-attachments/assets/a35cbf32-71f7-4ea8-b287-448137601bf9)

### Steps to Reproduce

1. Place the Apple Lattice.
2. Done lmao

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed inDev, thank you.

**Comment by satisfyu** [comment]
Fixed in 1.0.3.
