### ISSUE TITLE
Wines not consumed when drank in survival

### ISSUE THREAD

**Issue by Mr-Dutch-Wolf** [satisfyu/Let-s-Do-Hub#397]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.33

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

After drinking any of the wines from the mod it gives back a wine bottle without consuming the drink.
Apple juice and Grape Juices don't do this.

### Steps to Reproduce

start a world and obtain any wine, mead, or cider (Apple juice and Grape Juices don't do this) drink it in survival and it should give an empty wine bottle but keep the drink.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.4.34.
