### ISSUE TITLE
should i use this mod along WWOO?

### ISSUE THREAD

**Issue by VaporeonScripts** [satisfyu/Let-s-Do-Hub#401]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

latest

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

is it good to use both this mod and William Wythers' overhauled overworld?

### Steps to Reproduce

a

### Logs

a

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by VaporeonScripts** [comment]
Might as well give a response tbf

**Comment by satisfyu** [comment]
This Page here is for Issues and Suggestions. Not for general Questions about the Mods. 

The answer for it can even be found on the mod page: 
https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature
https://modrinth.com/mod/lets-do-bloomingnature
