### ISSUE TITLE
[Brewery] Gingerbread item is non-functional

### ISSUE THREAD

**Issue by son0fether** [satisfyu/Let-s-Do-Hub#403]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

2.0.3

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The "Gingerbread" item, brewery:gingerbread, does not appear to have any functionality.  It cannot be eaten or placed.  It has no item tags.

### Steps to Reproduce

1. Obtain brewery:gingerbread (villager trade or crafting)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You can place it on walls. It's not edible.
