### ISSUE TITLE
HerbalBrews

### ISSUE THREAD

**Issue by ledokua** [satisfyu/Let-s-Do-Hub#404]
### Minecraft Version

1.20.1

### Mod

HerbalBrews

### Mod Version

1.0.8.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Tea and coffe have insane regeneration effect speed

### Steps to Reproduce

1. Set your hp to 1 of 100 or any other.
2. Drink any tea or coffe with regeneration effect

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Copied Issue: 
https://github.com/satisfyu/Let-s-Do-Hub/issues/363
