### ISSUE TITLE
[Camping] DUPE all items 

### ISSUE THREAD

**Issue by Palitraq** [satisfyu/Let-s-Do-Hub#406]
### Minecraft Version

forge 1.20.1

### Mod

Camping

### Mod Version

1.0.4

### Latest Version

- [x] Yes. I'm using the latest Version.

### Issue Description

Duplicating with Backpacks

youtube - https://www.youtube.com/watch?v=LPNfGsgI5I4

### Steps to Reproduce

1. Open a backpack containing resources.
2. Drop the backpack from your inventory.
3. Take items from the dropped backpack.
4. Pick up the dropped backpack.
5. Open the backpack; you have now become a duper.

### Logs

N/A

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Duplicated Issue.

**Comment by Palitraq** [comment]
How soon will it be fixed?

**Comment by ROBGUI09** [comment]
> Duplicated Issue.

first issue id?

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Camping/issues/13
