### ISSUE TITLE
Farm&Charm 0.0.2 issues

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#41]
### Minecraft Version

Fabric 1.20.1

### Mod

Farm and Charm

### Mod Version

0.0.2

### Issue Description

1) Having any item from Farm&Charm in inventory triggers "harvest of the wilds" advancement. 
2) There is definitely something wrong with sprinklers: the more we place the faster they spin. (i placed so many of them that they even started to spin in opposite direction)
3) I think carts are supposed to stop at some point, right? Cause when disassembled while moving they continue to slowly move in that direction forever. (They even climb blocks themselves lol)
4) Roaster needs to be minable faster with pickaxe.
5) Scarecrow has no loottable.
6) Cluck effect is named `effect.farm_and_charm.chicken`, instead of `chicken` should be `cluck`. Otherwise it doesn't show in game properly.
7) Dog food effect has no translation in lang file among other effects.
8) Cat food effect does not restore health.
9) I haven't found even a single item that uses grandma's blessing effect (maybe should be grandma's cake?) 
10) Even though in lang file and on the wiki i saw keybinds, but i haven't seen them in minecraft settings.
11) 3 big tea jugs lose their handle when looked at from behind.

Questionable:
12. Now we are getting 3 achievements from different lets do mods for placing the stove.

Suggestion:
- Placing tea (tall ones) with shift+right-click (just like meals), cause it would be a bit disappointing if someone will place it on accident while intending to drink it. (since all we get for breaking it is empty bottle)

Side note:
 While adoring new stuff noticed that BloomingNature banner has Strength mispronounced as Strenght

### Steps to Reproduce

For 3: Get any of 2 carts in hands -> disassemble while in motion -> it rolls forever
For 11: Place one of 3 tea jugs -> come around it -> part of handle becomes invisible

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by Tefnya** [comment]
Haven't tested a lot of stuff like crafting recipes or general compatibility with other lets do mods, cause im a bit short on time. But i enjoyed it a lot!

**Comment by satisfyu** [comment]
Fixed. :)
