### ISSUE TITLE
Leaves decay

### ISSUE THREAD

**Issue by Tera458** [satisfyu/Let-s-Do-Hub#44]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Issue Description

The decaying of leaves is troubling, sometimes, natural trees will decay almost entirely despite respective logs being near, causing lots of items to drop, like spruce trees, while some other won't decay at all, like fir trees.

### Steps to Reproduce

Grow a fir and or spruce tree sapling.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
fixed in 1.1.8
