### ISSUE TITLE
[Compatibility issue] Game crashes when you use a Muddy Pig as a conductor for create's trains

### ISSUE THREAD

**Issue by JpnRndr01** [satisfyu/Let-s-Do-Hub#45]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Issue Description

Minecraft crashes when you try to use a Muddy pig as a train conductor for Create's trains. Only happens with the muddy pig, assuming its because of the flower hat it has

### Steps to Reproduce

Step 0: Have Blooming Nature, Let's do API, Architectury and Create
Step 1: build a basic train and get a muddy pig to sit in a seat behind a train controls
Step 2: Give the muddy pig a schedule to turn it into a conductor mob
Step 3: Crash

### Logs

https://mclo.gs/fePsyBd

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in the next release.
