### ISSUE TITLE
Cant find Warped wooly cows

### ISSUE THREAD

**Issue by JmanGaming** [satisfyu/Let-s-Do-Hub#46]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.14

### Issue Description

me and my friends have searched all through out the meadows, and nether. We can't seem to find them anywhere at all!
We have even tried breeding the wooly cows in the warped biome, but to no avail. Please tell me how we can get the warped wooly cow.

### Steps to Reproduce

Load a world and look, there are no warped wooly cows!

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by JmanGaming** [comment]
Also you cant make the cakes, cookies or cupcakes, because the recipe is overided by each other :/ They all share the exact same recipes.

**Comment by satisfyu** [comment]
https://github.com/satisfyu/Meadow/wiki/mobs#wooly-cows

https://github.com/satisfyu/Bakery/wiki/Blocks#Caking-Station

Feel free to check out the wiki.
