### ISSUE TITLE
Villager's Fright will use more emeralds than recipe requires

### ISSUE THREAD

**Issue by JohnW1455** [satisfyu/Let-s-Do-Hub#47]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.14

### Issue Description

When creating "Bottles of 'Villager's Fright'", the aging barrel will take up to 4 emeralds per bottle instead of 2, like the recipe says. This means if you place two 64 stacks of emeralds in with a 64 stack of the appropriate grape juice you'll only end up with 32 bottles. 

### Steps to Reproduce

Place a juice bottle in the aging barrel, then place 2 stacks of 2 emeralds in the appropriate locations. When the recipe completes, instead of having 2 emeralds left, you'll be left with none.

### Logs

It's not a crashing issue, so I don't know how to get the logs.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Using the same ingredients multiple times somehow never works. :) I have therefore adjusted the recipe, and it now works as it should.

This will be fixed with the next update.
