### ISSUE TITLE
Config to disable mobs?

### ISSUE THREAD

**Issue by xAlicatt** [satisfyu/Let-s-Do-Hub#48]
### Mod Name and Version

Blooming Nature/Meadow

### Suggestion Details

I'm using a custom farm animal resource pack and I'm fairly sure that the variant sheep added by these mods is conflicting with it. I was wondering why there is no config file to disable mobs.

### Expected Benefits

Provide a way to keep the other features of this mod, without the addition of extra mobs.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
https://imgur.com/a/xvrDQzC

Will be possible in a future update. :) Still WIP.
