### ISSUE TITLE
Cooking Pot: Can't use bottles as containers

### ISSUE THREAD

**Issue by Ninjdai1** [satisfyu/Let-s-Do-Hub#49]
### Minecraft Version

1.20.1

### Mod

Farm and Charm

### Mod Version

0.0.2

### Issue Description

Glass bottle are not usable as container in the cooking pot which prevents from making strawberry tea
Tested on the community server

### Steps to Reproduce

* Open a cooking pot
* Try placing glass bottles in the container slot

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 0.0.3.

**Comment by SeraphinFosfato** [comment]
Same issue here with the Fabric 1.20.1 on mod ver : [1.2.13]

I can't place bottles or Jars
