### ISSUE TITLE
Crash on Heavynode hosted SMP during startup

### ISSUE THREAD

**Issue by katubug** [satisfyu/Let-s-Do-Hub#50]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Issue Description

Meadow (version 1.3.14) and Vinery are crashing on multiplayer in forge 1.20.1 - but the weird thing is that they're only crashing on ONE of my servers. The one hosted by Akliz is fine. The one hosted by Heavynode is crashing.

I've deleted and reuploaded all the config, mod, and script files a few times and it hasn't fixed it. I'm not sure what's up. I also tried just deleting the Meadow and Vinery config folders, no dice.

I haven't tested this in a minimal instance - I'm sure it doesn't occur without the full modpack, but I need to get it working IN the pack, haha. Can you offer me any suggestions? I will also contact my host for support.

### Steps to Reproduce

Attempt to start server.

### Logs

https://gist.github.com/katubug/16f01b5370d4fdefa9ee883eb71bf338

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
@katubug  can i hit you up on discord? I can't replicate it so i would need your help testing potential solutions.

**Comment by katubug** [comment]
Definitely! It's HeyKatu over there

**Comment by satisfyu** [comment]
Fixed with 1.3.15.
