### ISSUE TITLE
The Stoves are too loud

### ISSUE THREAD

**Issue by Datboiii3** [satisfyu/Let-s-Do-Hub#52]
### Mod Name and Version

Let's Do Bakery and Let's Do Herbal Brews Fabric 1.20.1

### Suggestion Details

The stove block in both mods is too loud relative to the rest of the game, and the sound is not configurable independent from the base game's "blocks" sound bar. This seems like a simple solution would be to either decrease the noise of the block or create settings in the menu in order to determine the volume. A more interesting solution would be to be able to turn off the stove manually.

### Expected Benefits

My bakery will not sound like a forest fire.

### Potential Drawbacks

Sort of qol.

### Check for Similar Suggestions

- [x] Yes, I've looked for similar ideas.

**Comment by Datboiii3** [comment]
Additionally, the fuel timer is not visible, so I cannot determine whether I need more or less fuel in order to power the stove.
The stove doesn't accept sticks or wooden tools, despite being valid fuel sources for furnaces.
Placed stoves burn indefinitely if not interacted with.

**Comment by satisfyu** [comment]
i've just implemented new sounds for the stove - it's much more subtle and quiet.
