### ISSUE TITLE
[1.20.1] Grass Slabs taking up memory

### ISSUE THREAD

**Issue by Epik-B0mber** [satisfyu/Let-s-Do-Hub#53]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Issue Description

I have noticed via the Spark profiler that the trigger or value satisfyu.vinery.block.SpreadableGrassSlab.trySpread() is utilizing a whopping 4.15% of my server's memory, and was wondering if something could be done about it. Furthermore, I have other mods that add grass block slabs, so it would be very nice if this block could be made toggleable in the config so I don't have 3 copies of grass slabs. Thanks!

### Steps to Reproduce

1. Play game
2. Run profiler
3. See dump even though there shouldn't be any of those in the world hopefully

### Logs

Doesn't create any errors or anything just memory.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
have optimized the trySpread method to minimize object creation and redundant checks, avoiding unnecessary re-fetching of block states and directly updating blocks when conditions are met - this should reduce the memory usage.
