### ISSUE TITLE
Gold Ring does not apply Luck when in Ring Slot (Trinkets [Fabric])

### ISSUE THREAD

**Issue by applesos** [satisfyu/Let-s-Do-Hub#54]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.2.12

### Issue Description

When Golden Ring is equipped to the Ring Slot the luck status effect is not applied

### Steps to Reproduce

- Equip to either Ring Slot
- No Luck Effect
- Equipped to Chestplate
- Luck Effect Applied

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
When you're wearing it on the ring slot the luck attribute will be granted through the attributemodifier: 
https://github.com/satisfyu/Candlelight/blob/architectury-1.20.1/fabric/src/main/java/satisfy/candlelight/fabric/api/RingItem.java
