### ISSUE TITLE
Most Recent Forge Version has Incorrect Title on Curseforge

### ISSUE THREAD

**Issue by DunsparceMeta** [satisfyu/Let-s-Do-Hub#56]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.12.1

### Issue Description

The filename on Curseforge says fabric, despite the file being for forge and being tagged correctly.

### Steps to Reproduce

Go to Curseforge page -> Files -> Mod version 1.2.12.1 for Forge is named incorrectly

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed.
