### ISSUE TITLE
Duplicating Basket

### ISSUE THREAD

**Issue by Fyoncle** [satisfyu/Let-s-Do-Hub#57]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.10

### Issue Description

When basket clicked with bare hand, it duplicates forever and drops infinite trays

https://github.com/satisfyu/Let-s-Do-Hub/assets/63975256/9b5f061b-20ae-411d-a441-0f2c2f148e7c

Also same goes for the chocolate boxes.

https://github.com/satisfyu/Let-s-Do-Hub/assets/63975256/d8e673eb-ee42-4c05-9498-1b6489c0b9c2

Also same goes for the placed breads and MORE...

### Steps to Reproduce

1. Open a debug world
2. Go to the let's do items
3. Go to the basket and click a empty basket with bare hand
4. See it dropping trays in every right click
5. (do the same for chocolate box)

### Logs

I cannot post it here, its 490000 lines and mclo.gs limits it, either file size is insanely huge.

But heres some parts of it 
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/63975256/dae5307f-f269-4c51-9630-3f4be6fd6272)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Not reproducible. Neither inDev nor in a small modpack.

When I reproduce the steps, the item is consumed / loses a stack and drops the required crafting item (tray / chest) when the stack size reaches 0.

Keep in mind that its default behaviour that these blocks dropping these items on stacksize 0.

**Comment by satisfyu** [comment]
Alright, thats definitely related to the debug world. 

> World behavior
> 
> It is impossible to change, place or remove any block, even by the game itself.


Since the block can't be removed it just drops its Item.
