### ISSUE TITLE
API Block Log Spam

### ISSUE THREAD

**Issue by Fyoncle** [satisfyu/Let-s-Do-Hub#58]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

It's the API

### Issue Description

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/63975256/04a13ba5-0078-4f50-b780-574c3f01e201)
Lot of Let's Do blocks and an API block is causing log spam, and theres very similar log spam like this, the logs are over 193,000 lines.

### Steps to Reproduce

1. Create a debug world
2. Find the doapi:standart block
3. See the logs

### Logs

Too long, but i showed the part that is required above.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please report it to the DoAPI Issue tracker since its related to it. 
https://github.com/Team-Let-s-Do/DoAPI/issues
