### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by arvenyon** [satisfyu/Let-s-Do-Hub#59]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Issue Description

Crash after various playtime. Seems to be linked to Big FlowerPots?

### Steps to Reproduce

Generate a new world. Depending on the biome you spawn, the game either crashes immediately or after travelling a few biomes in the direction of ungenerated terrain.

### Logs

https://pastebin.com/CDiiGZtY

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Please update doAPI to the latest version. Thats a really old issue which got fixed weeks ago.
