### ISSUE TITLE
Compats/patches with Farmers delight?

### ISSUE THREAD

**Issue by Kindredphoenix** [satisfyu/Let-s-Do-Hub#60]
### Mod Name and Version

Vinery, Bakery, Candlelight.

### Suggestion Details

I'm playing with Bakery and farmers delight, it would be awesome if there was a patch that would incorporate even the ovens from Farmers delight to be used to heat up the small cooking pot from bakery, making it easier to make jams and breads. Furthermore various baking recipes from both mods could be cool to, since I know farmers delights adds a lot of new foods that could work well with all of the lets do mods that involve food.

### Expected Benefits

By combining the foods from farmers delight and the Lets Do series it could greatly improve player experiences, creating an every expanding options for making good, displaying food and sweets, maybe even having chef shops, restarunts etc.

### Potential Drawbacks

It may take awhile, I dont know anything about modding, so i dont know what it would take to make a patch between the two mods.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Theres no additional compat planned than sharing tags. 

You can check out Ninidajs Compat addon which covers a few of your ideas :): 
https://www.curseforge.com/minecraft/mc-mods/lets-do-addon-compat
