### ISSUE TITLE
server crashing on startup with newest herbalbrews version

### ISSUE THREAD

**Issue by temyy** [satisfyu/Let-s-Do-Hub#63]
### Minecraft Version

1.20.1

### Mod

HerbalBrews

### Mod Version

1.0.8

### Issue Description

server fails to boot up and crashes midway through, downgrading to 1.0.7 prevents this from occurring

### Steps to Reproduce

1. have herbalbrews 1.0.8 with its dependencies
2. launch server
3. crash

### Logs

https://pastebin.com/qvkMBZGf

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.0.8.1
