### ISSUE TITLE
compatibility issues with Let's do api

### ISSUE THREAD

**Issue by AtomicDesignz** [satisfyu/Let-s-Do-Hub#64]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.2.10

### Issue Description

I'm trying to download let's do bakery (i've tried a large numbger of versions and it doesn't fix it.) but when I attempt to download it I have issues with the Let's do api compatibility. if I  get lets do api version 1.2.10 then Candlelight (1.2.5) stops working and minecraft crashes. If I  do version 1.2.4 of api then candlelight works but lets do bakery has issues and minecraft crashes. How do I fix? (candlelight and api [1.2.4] works fine with out bakery)

### Steps to Reproduce

 With Fabric, download lets do api version 1.2.10 with Candlelight (1.2.5) then download lets do bakery (I copied my logs below)

### Logs

 Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[21:13:57] [ForkJoinPool-1-worker-3/WARN]:
 Mod nicemod uses the version 1.4.1 - 1.20 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string ' 1.20'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:13:57] [main/INFO]:
 Loading 98 mods:
	- architectury 9.0.8
	- bakery 1.0.0
	- beautify 1.1.0+1.20
	- candlelight 1.2.5
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clutter 1.20-0.5.8
	- couplings 1.9.5+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- cozy 1.1.1
	- cristellib 1.1.2
	   \-- blue_endless_jankson 1.2.1
	- decomod 1.0.2+blanketcon
	   |-- advanced_runtime_resource_pack 0.6.7
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	- doapi 1.2.4
	   \-- terraform-wood-api-v1 7.0.1
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   \-- com_eliotlash_mclib_mclib 20
	- java 17
	- mcwbridges 3.0.0
	- mcwdoors 1.1.0
	- mcwroofs 2.3.0
	- mcwwindows 2.2.1
	- minecraft 1.20.1
	- moonlight 1.20-2.5.4
	- moremobvariants 1.2.2
	- mr_gardeners_dream 1
	- mr_ketkets_furnicraft 2.3
	- nicemod 1.4.1 - 1.20
	- pfm 1.2.1
	- resourcefullib 2.0.8
	- supplementaries 1.20-2.5.2
[21:14:10] [Render thread/INFO]:
 Registering Item Groups for dustydecorations
[21:14:10] [Render thread/ERROR]:
 No data fixer registered for handcrafted
[21:10:16] [Render thread/ERROR]:
 No data fixer registered for bomb
[21:10:16] [Render thread/ERROR]:
 No data fixer registered for rope_arrow
[21:10:16] [Render thread/ERROR]:
 No data fixer registered for slingshot_projectile
[21:10:16] [Render thread/INFO]:
 Initialized color sets in 53ms
[21:10:16] [Render thread/INFO]:
 Finished mod setup in: [0, 0, 16, 0, 1, 0, 0, 5, 1] ms
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
[21:00:03] [Worker-Main-1/WARN]:
 Unable to load model: 'candlelight:item/food/lettuce_tomato_1' referenced from: candlelight:lettuce_tomato#inventory: java.io.FileNotFoundException: candlelight:models/item/food/lettuce_tomato_1.json
[21:00:03] [Worker-Main-1/WARN]:
 Unable to load model: 'candlelight:item/food/lettuce_tomato_2' referenced from: candlelight:lettuce_tomato#inventory: java.io.FileNotFoundException: candlelight:models/item/food/lettuce_tomato_2.json
	- mcwpaintings 1.0.5
[21:14:10] [Render thread/ERROR]:
 No data fixer registered for doapi:chair
    minecraft:textures/atlas/blocks.png:exlinefurniture:blocks/zombie_arm
[21:00:10] [Worker-Main-1/WARN]:
 Missing textures in model exlinefurniture:zombie_arm#inventory:
	- mcwfurnitures 3.2.2
[21:14:09] [Render thread/INFO]:
 [Clutter] Finished initializing.
[21:14:10] [Render thread/INFO]:
 Hello Fabric world!
[21:00:10] [Worker-Main-1/WARN]:
 Missing textures in model exlinefurniture:zombie_arm#facing=east:
	- farmersdelight 1.20.1-1.4.3
[21:14:12] [Render thread/INFO]:
 Loaded config supplementaries-common.json
[21:14:12] [Render thread/INFO]:
 Loaded config supplementaries-client.json

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Candlelight wont work wirk newer Version of the API just as Bakery wont work with older Versions of it. Use the latest version of both and stop using massively outdated versions. 

The latest bakery version is 1.1.11
The latest candlelight version is 1.2.11
The latest doAPI version is 1.2.12
