### ISSUE TITLE
[Request] Brewery Hops compatibility with other types of Farmland

### ISSUE THREAD

**Issue by katubug** [satisfyu/Let-s-Do-Hub#65]
### Mod Name and Version

Brewery for 1.20.1 forge

### Suggestion Details

Hi! I have Farmer's Delight in my modpack and found that I can't plant Hops on Rich Soil Farmland, which can't be trampled and provides a growth boost to your crops. Is it possible to make them compatible? I also have farmland from Swampier Swamps, the Aether, and Regions Unexplored - so if I could add them all to a tag to make them compatible, that would be ideal.

### Expected Benefits

I think it will provide wider compatibility with other mods.

### Potential Drawbacks

It could be frustrating to maintain a comprehensive list of every type of farmland from multiple mods (but with a tag system, us modpack makers could easily alter this for our packs).

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Implemented.

**Comment by katubug** [comment]
Hooray, thank you!
