### ISSUE TITLE
Wine not aging on server

### ISSUE THREAD

**Issue by mkern1200** [satisfyu/Let-s-Do-Hub#66]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Wine seems to be aging correctly in a singleplayer world, but when on a server with the same modpack (aside from a few server-side-only mods), the "Year of Production" shown in the tooltip always updates to the current in-game day, so it never actually increases in age.  Full server modpack list included in attached file (mods under "Server-Side Mods" were not tested in singleplayer but are on the server where we tested this issue, so one of them could be at fault).

[Mods List.txt](https://github.com/user-attachments/files/15746107/Mods.List.txt)

### Steps to Reproduce

1.  Install the modpack on a server.
2.  Create or /give a player wine (Solaris used in testing, not sure if other wines are affected).
3.  Place the wine in a container or keep in player's inventory for one "year" or longer (year length set to 1 day in config for testing purposes).
4.  The "Year of Production" shown in the tooltip will keep changing to match the current year, and the wine's effect never increases in strength.

### Logs

None applicable

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by mkern1200** [comment]
Apologies, but I only have the one server, so I was not able to test this on a minimal instance, as doing so would have caused a lot of damage to our server when removing all other installed mods.

**Comment by satisfyu** [comment]
Just to clarify how wine years work:
Wine years simply sync with the time of your world.

So if you have a mod that changes any of your worlds time settings as well as any commands like /time set or /time add do not work with wine aging and will reset the current time of your wine. 

Also some Wines made with Creates Mixer or other methods wont get any nbt tags which makes it impossible for the wine to age.

**Comment by mkern1200** [comment]
Ah, I think I see what you mean.  It turns out the player who encountered this issue was using a Create mechanical mixer, so that would indeed be the reason.  Is there any way to correct that in a future update, or is this an issue Create would need to fix?

Also, when I try to craft the Solaris wine using an aging barrel, it gives me this (default config settings as far as year length/effect, and this is day 2899 in-game).  So the year of production is being counted correctly that way, but the effect is still maxed-out as soon as the wine is done in the aging barrel.  Is that the intended function, or am I missing something else?

![2024-06-09_16 43 23](https://github.com/satisfyu/Let-s-Do-Hub/assets/36843625/63154845-fcd0-4bee-96a5-514e535e1576)

**Comment by satisfyu** [comment]
Nope - thats actually completely on my side. No reason to bother create devs with it. :)

**Comment by mkern1200** [comment]
Ah, gotcha. Did you happen to know anything about the second part of my last message? Where the wines made in the aging barrel have the max effect as soon as it's crafted even when it shows the correct year of production?

**Comment by satisfyu** [comment]
Thats not the intended behaviour but i also haven't being able to reproduce it.
