### ISSUE TITLE
[Vinery 1.4.21] Straw hat crashes game when rendered on entity

### ISSUE THREAD

**Issue by Polaria1** [satisfyu/Let-s-Do-Hub#68]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.21

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When its model is rendered, the Vinery straw hat causes an immediate crash with the message 'java.util.NoSuchElementException: Can't find part top_part'.

Logs are below. This only seems to happen with the 3D rendered model, not the inventory sprite. All other Let's Do hats were tested and seem to work fine. Running Embeddium 0.3.20 and Oculus 1.7.0, tested both with and without. The issue persisted regardless of whether a shaderpack was enabled. Also tested on the newest Forge version without Embeddium.

Tested on Forge 47.2.0 (with a full modpack complement and Embeddium) and 47.3.1 (both with modpack and standalone, only with dependencies, both with and without Embeddium).

With the testing I have done I have nearly full confidence it is a Vinery issue.

### Steps to Reproduce

1. Install Vinery and its dependencies
2. Boot Minecraft
3. Open a world and put on the straw hat
4. hit F5 or go into inventory - i.e., enter any situation where the 3D model is rendered
5. The game will crash, 100% of the time

### Logs

https://pastebin.com/m8rWb70a - crash report on 47.2.0 forge with embeddium 0.3.20
https://pastebin.com/Hr0yxtrc - crash report on 47.3.1 forge, standalone and only with dependencies

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by mkern1200** [comment]
This crash occurs on Fabric with Minecraft 1.20.1 and Vinery 1.4.20 as well.

**Comment by satisfyu** [comment]
Fixed in 1.4.22
