### ISSUE TITLE
Filling Wooden Bucket with water Bug

### ISSUE THREAD

**Issue by jimmytrouser** [satisfyu/Let-s-Do-Hub#69]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.16

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

If I make two buckets and don't separate them when I fill them with water the buckets turn into a single bucket.

Essentially 2 buckets are turning into 1 as 1 is deleted.  Works even if I have a stack of buckets.

https://github.com/satisfyu/Let-s-Do-Hub/assets/7896905/ee95e469-dc47-42e2-9278-b848280743a0

### Steps to Reproduce

Make two or a stack of buckets and fill with water.

### Logs

https://pastebin.com/W9dXtkNa

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.3.17
