### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by AsimutMLS** [satisfyu/Let-s-Do-Hub#70]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

letsdo-brewery-forge-1.1.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

A bug happened!
mod
letsdo-brewery-forge-1.1.8

### Steps to Reproduce

I put 3 hops in the brewery
when I filled the water, the server went into a crash, which was repeated every time I entered it (if it does not enter, it did not crash)

### Logs

[crash-2024-06-09_14.05.19-server.txt](https://github.com/user-attachments/files/15765985/crash-2024-06-09_14.05.19-server.txt)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Should be fixed in 1.1.9
