### ISSUE TITLE
Bottled Water for Bakery Oven

### ISSUE THREAD

**Issue by jimmytrouser** [satisfyu/Let-s-Do-Hub#71]
### Mod Name and Version

Let's Do Bakery 1.1.11

### Suggestion Details

To be able to use a stack of bottled water instead of a bucket of water.  

### Expected Benefits

Makes the recipe for baking bread easier.  More immersive as bottles make sense and can be stacked up.

### Potential Drawbacks

Use of sand to make bottles.  Also, do the bottles get used up or are they ejected to be reused?

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
Currently not planned - mainly due to my lack of skills regarding craftremainders.

It used to be possible; however, it always consumed the entire stack to return the stack remainder (in this case, the glass bottle).
