### ISSUE TITLE
Block{bloomingnature:flower_pot_big} causing crash.

### ISSUE THREAD

**Issue by FloppSlopp** [satisfyu/Let-s-Do-Hub#72]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Whilst walking through a village my game froze and crashed, with the crash report stating it is from the flower pots. Now everytime I load the world the game crashes as soon as the screen switches off the loading screen, so I see the world for a second.

### Steps to Reproduce

It was completely random in my world where I was adventuring for some time before the crash, but I created a new world and it crashed straight away.

### Logs

https://pastebin.com/jJTPm4CM

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You're definitely not using the latest version. 
> 		doapi: [Let's Do] API 1.2.10
				
This Issue got fixed in 1.2.11 - the current version is already 1.2.13. Update doAPI.
