### ISSUE TITLE
bushes everywhere

### ISSUE THREAD

**Issue by Vikthos** [satisfyu/Let-s-Do-Hub#73]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.22

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

there are way too much berry bushes being generated. Almost every chunk has berry bushes. This may also be caused by an incompatibility with Regions Unexplored. Not sure

### Steps to Reproduce

- Generate chunks
- way too many bushes

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
What iind of berry bushes? :)

**Comment by Vikthos** [comment]
thanks you are awesome
