### ISSUE TITLE
Foods with raw chicken and potion as ingredients get Hunger Debuff

### ISSUE THREAD

**Issue by TechnoSparks** [satisfyu/Let-s-Do-Hub#74]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.12

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

I notice that when cooking "Chicken Alfredo", they keep having Hunger while at very rare times they dont. I checked with Minecraft wiki and it seems raw chicken can give Hunger debuff at 30% chance. I think Candlelight may be assigning the Hunger debuff based on this. **But** the chicken is being cooked on a pan and therefore is not raw anymore. 

I think this is a bug. I also checked with "Chicken with Vegetables" and got the same outcome. After further testing it seems that any recipe that requires a raw chicken and any potion will yield this behaviour. If the recipe does not require potion, the food will not have any effects.

### Steps to Reproduce

- Use cooking pan
- Put Chicken Alfredo Recipe
- Wait for output

### Logs

not relevant?

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [x] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for the detailed explanation. Thanks to this, I was able to identify the problem quickly. It is fixed with the 1.2.13 update. :)

**Comment by TechnoSparks** [comment]
Thank **you** for creating such a fun mod 😄
