### ISSUE TITLE
Unnecessary translation lines and few loottables

### ISSUE THREAD

**Issue by Tefnya** [satisfyu/Let-s-Do-Hub#76]
### Minecraft Version

Fabric 1.20.1

### Mod

BloomingNature

### Mod Version

1.0.8

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

1) There are few **probably** useless lines in en_us lang file: 613-615, 597-599, 584-586, 571-573. Each one of them has already working counterpart in the same file.
2) Blocks with no loottables:
- Mossy travertin bricks
- Mossy travertin brick slab
- Mossy travertin brick stairs
- Mossy travertin brick wall
--
- Mossy slate bricks
- Mossy slate brick slab
- Mossy slate brick stairs
- Mossy slate brick wall
--
- Mossy laterit bricks
- Mossy laterit brick slab
- Mossy laterit brick stairs
- Mossy laterit brick wall

I didn't test config a lot, so can't say much about it 😅

### Steps to Reproduce

～

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed.
