### ISSUE TITLE
Crash when killing wine mule - 1.20.1 Forge

### ISSUE THREAD

**Issue by vivagabe** [satisfyu/Let-s-Do-Hub#77]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.22

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

My game crashes when killing wine mule.
[crash-2024-06-14_18.02.00-client.txt](https://github.com/user-attachments/files/15845082/crash-2024-06-14_18.02.00-client.txt)

### Steps to Reproduce

Kill wine mule crashes the game.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.4.23
