### ISSUE TITLE
Noir wine gives instant health for a duration

### ISSUE THREAD

**Issue by Joe-Moe** [satisfyu/Let-s-Do-Hub#79]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.23

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Noir wine has a duration on instant health, instead of making it instant, rendering you invincible

### Steps to Reproduce

Drink noir wine, try to die to a monster

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.4.24
