### ISSUE TITLE
Meadow's Pine Trees HT's Tree Chop incompatibility

### ISSUE THREAD

**Issue by jimmytrouser** [satisfyu/Let-s-Do-Hub#8]
### Minecraft Version

1.20.1

### Mod Name and Version

Meadow 1.3.8

### Issue Description

Seems pine trees are not compatible with HT's tree chop (version 0.19.0) but all other trees from meadows are.
I've tried adding logs to the HT's cfg file but nothing seems to work.
Any suggestions?

### Steps to Reproduce

I've tried adding logs to the HT's cfg file but nothing seems to work.

### Minimal Instance Test

- [X] Yes, I've tested this on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by SugarDaddii** [comment]
[treechop_meadowfix.zip](https://github.com/satisfyu/Let-s-Do-Hub/files/15181489/treechop_meadowfix.zip)
try this

**Comment by satisfyu** [comment]
Other priorities mostly. ;) 

Also the original made compat was fixed by HT himself so i thought it would work. He also mentiod, that `#treechop:chopped_logs` isn't needed. 

https://github.com/satisfyu/Meadow/pull/16

**Comment by satisfyu** [comment]
@SugarDaddii Is it okay for you if I take over the datapack, or could you contribute it via a PR? That would be nice and would solve the problem

**Comment by SugarDaddii** [comment]
no its okay ... take it hold it love it ... hopefully you dont get any reports of this again <3

**Comment by satisfyu** [comment]
Thank you! 

Proper HT's Tree Chop compat will be added in 1.2.9

**Comment by jimmytrouser** [comment]
Thank you, worked like a charm.

**Comment by hammertater** [comment]
Hey y'all, I'm a little late here, but maybe this will help in the future - for TreeChop to work with modded trees, all you need is for log blocks to have the `#minecraft:logs` tag and for leaves blocks to have the `#minecraft:leaves` tag. Feel free to @ me if something ever isn't working :)
