### ISSUE TITLE
Let's do and Valkyrien Skies Incompatability on a server (applies to some farmers delight addons and maybe supplementaries as well)

### ISSUE THREAD

**Issue by Skidouche** [satisfyu/Let-s-Do-Hub#80]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

latest version of the api 

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When setting up a server with the [Let's do] mods on forge, players are unable to join, receiving an error such as the ones below.
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/69219938/fa232b14-7839-4d70-96a8-89b667d57dc7)
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/69219938/ad76d959-3c34-4d90-8cf5-20f43c50f5ea)
sometimes they'll have slight variations or a different ID error but it's always one of these two. However, it runs fine on single player.

### Steps to Reproduce

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/69219938/ae88f7a5-67cc-4e57-9713-e01e52e164bf)
Here is the list of mods I used. Server was made through Oracle cloud on forge version 47.2.17. Connect to a server with this list of mods and it should recreate the error.

### Logs

https://pastebin.com/xrqT3KQP

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
https://github.com/Team-Let-s-Do/DoAPI/issues

The API is not maintained by me and has its own issue tracker. Please report there, thank you. :)

**Comment by Skidouche** [comment]
> https://github.com/Team-Let-s-Do/DoAPI/issues
> 
> The API is not maintained by me and has its own issue tracker. Please report there, thank you. :)

ah, sorry about that.
