### ISSUE TITLE
[Vinery] Infinite recursion in `TraderMuleEntity#remove`

### ISSUE THREAD

**Issue by Shadows-of-Fire** [satisfyu/Let-s-Do-Hub#81]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.24

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Vinery triggers infinite recursion if a trader mule is discarded on the server for any reason.  The offending code is here 
https://github.com/satisfyu/Vinery/blob/4a11ab3dbc419889ba29636269c938abbd3149f9/common/src/main/java/satisfyu/vinery/entity/TraderMuleEntity.java#L74-L76

This entire override for `TraderMuleEntity#remove` should just be deleted.

### Steps to Reproduce

Spawn in a trader mule entity and do something that triggers a discard (i.e. having the mob despawn)

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
I've removed it. Will upload it later today.
