### ISSUE TITLE
Cabinet's storage space is small considering its recipe

### ISSUE THREAD

**Issue by TechnoSparks** [satisfyu/Let-s-Do-Hub#82]
### Mod Name and Version

Candlelight 1.2.13 & Bakery 1.1.11

### Suggestion Details

In Candelight and Bakery, [wall] cabinets' recipes require 2 barrels.

A vanilla barrel has **3x9** storage space
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/6072210/8f7572bb-d1f8-45bc-ad47-3bd7da4a902d)

However cabinets from Candlelight and Bakery only has **2x9** storage space
![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/6072210/c9044549-48ba-457d-86b1-ffea3db12218)

Because the recipe for cabinets call for 2 barrels, I suggest for the cabinets in Candlelight and Bakery to have twice the space of a vanilla barrel. That means **6x9**. If that's too big (because it equals to a double chest) then maybe make it similar to a barrel (3x9) and make the recipe only call for 1 barrel.

### Expected Benefits

It makes sense due to how the recipe uses 2 barrels.

### Potential Drawbacks

- Developer's time :(
- Can be too big because now it acts like a double chest for just a single block space (i proposed an alternative to only call recipe for 1 barrel and space adjusted to be the same as barrels)

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
I've just implemented and tested it. It has now a 5x9 storage space and won't wipe out any contents already inside the cabinets. :) 

I'll upload it later today.

**Comment by TechnoSparks** [comment]
Wow I wasn't even done writing my draft. Really appreciate with the change! 

The whole reason for this suggestion is because a third party mod's cabinet may have different properties set to them, thus [ContainerSearcher](https://modrinth.com/mod/csearcher) doesn't work on them. Your cabinets does work with the ContainerSearcher, but I long for the space!

Again, thank you for creating such a fun mod
