### ISSUE TITLE
Noir wine doesnt heal

### ISSUE THREAD

**Issue by Joe-Moe** [satisfyu/Let-s-Do-Hub#83]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.24

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Noir wine doesn't heal

### Steps to Reproduce

- Get hurt
- Drink noir wine

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Will be fixed in the next update. Thank you for your bugreport! :)
