### ISSUE TITLE
Podzol Slab please?

### ISSUE THREAD

**Issue by jimmytrouser** [satisfyu/Let-s-Do-Hub#85]
### Mod Name and Version

Vinery

### Suggestion Details

Love to bits the dirt slab, would be great to see a podzol and rooted version.

### Expected Benefits

Builder's paradise.

### Potential Drawbacks

None other than someone has to make it.

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
They are actually planned to be implemented in BloomingNature. :)
