### ISSUE TITLE
Stove cook need to isburing and the fuel slot must be has item 

### ISSUE THREAD

**Issue by Azumic** [satisfyu/Let-s-Do-Hub#86]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

1.1.11

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![31843b553c9a276eb337bfd7af4c8c18](https://github.com/satisfyu/Let-s-Do-Hub/assets/95330698/5704341c-b751-4054-a901-70131166d5f5)
stove is buring, but not cook, it need the fuel slot has item at the same time.

### Steps to Reproduce

1.insert the recipe ingrentdient 
2.insert the fuel lava bucket
3.extract the fuel solt item -- bucket

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.1.12.
