### ISSUE TITLE
Glass bottle duplication / infinite grape juice

### ISSUE THREAD

**Issue by kreffox** [satisfyu/Let-s-Do-Hub#87]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

forge-1.4.24

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Drinking a bottle of grape juice of any kind does not remove the full bottle of juice from the players inventory.
A glass bottle does appear though which results in infinite glass bottles.

### Steps to Reproduce

1. Fresh Install of Forge (Versions tested: 47.3.1 + 47.3.0)
2. Install Version 1.4.24 of the vinery mod (and only the vinery mod)
3. Get any bottle of grape juice (ex. Red Grape Juice)
4. Drink it.

There are no errors in the latest log but I provided it anyway.

### Logs

https://pastebin.com/RYYwGeq7

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed. Will uploaded the fixed version later today.
