### ISSUE TITLE
How to pick up item?

### ISSUE THREAD

**Issue by chillicheesee** [satisfyu/Let-s-Do-Hub#9]
### Minecraft Version

1.20.1

### Mod Name and Version

Barkey, 1.1.8 Forger

### Issue Description

How do you pick up items from the caking station after you've made them? I can't pick up cakes to put them in the display, nor can I make cupcakes at all. 

### Steps to Reproduce

I did download older versions, but they don't have the cupcake displays.

### Minimal Instance Test

- [ ] Yes, I've tested this on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hey 

please check the wiki for more informations on how to use the caking station: 
https://github.com/satisfyu/Bakery/wiki/Blocks#Caking-Station

After you have successfully crafted your cake, cupcakes or cookies you can simply right-click on the resp. block to pick it up.
