### ISSUE TITLE
Bakery's strawberry uses a wrong tag

### ISSUE THREAD

**Issue by wasdspace** [satisfyu/Let-s-Do-Hub#91]
### Minecraft Version

1.20.1

### Mod

Bakery

### Mod Version

forge-1.1.12.1

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The strawberries' tag should be "forge:fruits/strawberry" not "forge:fruits/strawberries", because tag just represents the type and not the quantity

### Steps to Reproduce

N/A

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by Ninjdai1** [comment]
As a heads up, while this is currently true in forge 1.20.1, starting with neo and fabric 1.20.5, c:fruits/strawberries would actually be the correct standard

**Comment by satisfyu** [comment]
Fixed inDev.
