### ISSUE TITLE
Vinery - FORGE - Fermenting Barrel Problems

### ISSUE THREAD

**Issue by Sourceshard** [satisfyu/Let-s-Do-Hub#93]
### Minecraft Version

1.19.2

### Mod

Vinery

### Mod Version

1.3.12b

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The inventory item boxes on the fermenting barrel float off to the side of the background image. 

When fermenting for example using apple mash to make apple juice. The resulting item does not stack in the Fermenting barrel causing the barrel to stop producing after one item is produced.

The Fermenting Barrel cannot be properly automated. When using hoppers Items can go into the wrong slots stopping the barrel from fermenting. Also when a hopper is placed underneath the barrel to pull out produced product it instead pulls out the empty wine bottles from the wine bottle slot. 

### Steps to Reproduce

Place and access barrel. 

Attempt to automate feeding and pulling out items from the Fermenting Barrel.

I am using the mod in the Monumental Experience 2.2.170 Modpack from Curseforge. 

https://www.curseforge.com/minecraft/modpacks/monumental-experience

### Logs

No errors were generated. Nothing to log.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
The modpack uses its own texture for the GUI or changes the one from Vinery - you should report this to the modpack creator.

In version 1.19.2, there is no active hopper support - this was introduced with 1.20.1.
