### ISSUE TITLE
Meadow wooden buckets doesn't have proper forge tags

### ISSUE THREAD

**Issue by M0l1bden** [satisfyu/Let-s-Do-Hub#94]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.17

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

![image](https://github.com/satisfyu/Let-s-Do-Hub/assets/162787928/54cb6cb9-9f0a-4aa9-a47c-aa54142b080f)

### Steps to Reproduce

Add forge:buckets and forge:buckets/empty tags to empty wooden bucket
Add forge:buckets/milk to wooden milk(default milk/any milk) bucket
Add forge:buckets/water to wooden water bucket

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Added all these tags in 1.3.18
