### ISSUE TITLE
Noir wine can't be placed in big wine racks/storage

### ISSUE THREAD

**Issue by Joe-Moe** [satisfyu/Let-s-Do-Hub#95]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.25

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Even though noir wine has the right bottle shape, and used to be able to, it can no longer be placed inside any wood variant of the big wine racks, nor can it be placed in the small ones.

### Steps to Reproduce

Try placing a bottle of noir wine in a small or big rack.

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Fixed in 1.4.26
