### ISSUE TITLE
straw hat crash

### ISSUE THREAD

**Issue by sargeow** [satisfyu/Let-s-Do-Hub#96]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.21

### Latest Version

- [ ] Yes. I'm using the latest Version.

### Issue Description

crashes when hovering over straw hat item in EMI

### Steps to Reproduce

download EMI and vinery, hover over straw hat item in EMI, crash, sulk.

### Logs

[crash-2024-07-01_15.50.07-client.txt](https://github.com/user-attachments/files/16058493/crash-2024-07-01_15.50.07-client.txt)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
No comment.
