### ISSUE TITLE
Parsing error loading recipe on all Let'do mods with FD and Addons

### ISSUE THREAD

**Issue by HellimsProjects** [satisfyu/Let-s-Do-Hub#97]
### Minecraft Version

1.20.1

### Mod

Candlelight

### Mod Version

1.2.13

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

We getting ton of error messages on server about "Parsing error loading recipe" on all Let'do mods with FD and Addons

### Steps to Reproduce

Start server.

### Logs

[latest.log](https://github.com/user-attachments/files/16079869/latest.log)
[[072547] [mainERROR] Parsing error .txt](https://github.com/user-attachments/files/16079892/072547.mainERROR.Parsing.error.txt)

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Not related to any of my Mods. 

Might be caused by the letsdoaddon-compat - update it. 

It these errors persist, report it to here: 
https://github.com/Ninjdai1/letsdo-addon-compat/issues
