### ISSUE TITLE
BloomingNature logs can't be burnt into charcoal

### ISSUE THREAD

**Issue by VoxSomniator** [satisfyu/Let-s-Do-Hub#98]
### Minecraft Version

1.20.1

### Mod

BloomingNature

### Mod Version

1.0.7

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The logs added by BloomingNature can't be smelted into charcoal like Minecraft's other logs.
The issue seems to be a missing item tag- Adding "minecraft:logs_that_burn" to these items makes them a valid ingredient for the existing log-smelting recipe.

### Steps to Reproduce

Put a log from BloomingNature in a furnace, it doesn't smelt

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thats already fixed inDev. The next update will feature some bigger changes - therefore it might take a bit until its release.
